### ISSUE TITLE
Feature request: Export Hyper-V CPU usage

### ISSUE THREAD

**Issue by sandersaares** [martinlindhe/wmi_exporter#101]
CPU usage of Hyper-V virtual machines does not appear on any metrics exported by the WMI exporter - the CPU time used by virtual machines is counted under "idle". It would be desirable to also see Hyper-V CPU metrics.

Potentially relevant: https://blogs.msdn.microsoft.com/tvoellm/2008/07/14/how-to-get-processor-utilization-for-hyper-v-via-wmi/

See also: https://stackoverflow.com/a/36005302/2928

**Comment by martinlindhe** [comment]
Someone using Hyper-V, feel free to look into this one!

**Comment by carlpett** [comment]
Fixed by #150.

**Comment by carlpett** [comment]
Hm. That would mean that the `Win32_PerfRawData_PerfOS_Processor` WMI class we use for the CPU collector doesn't include the VM's consumption in its' stats. Did you have a look at the new `wmi_hyperv_host_cpu*` metrics? In particular, it would be interesting to see how `wmi_cpu_time_total` and `wmi_hyperv_host_cpu_total_run_time` relate.

**Comment by externl** [comment]
I haven't enabled the `hyperv` metrics since I'm just interested in the host cpu. I can try later.

**Comment by externl** [comment]
Should I start a new issue or should this be reopened? Or am I mis understanding 'idle'?

**Comment by sandvige** [comment]
@carlpett Did you find anything explaining why `Win32_PerfRawData_PerfOS_Processor` is excluding VMs consumption? Is it also the same issue with all `Win32_PerfRawData_PerfOS_*`, like network consumption and Disk IO?
