### ISSUE TITLE
Service Failed to start - InSufficient privileges

### ISSUE THREAD

**Issue by Ajeyprabhu** [martinlindhe/wmi_exporter#104]
When I pass the arguments of iis or os, to execute the wmi_exporter-0.2.3-386.msi it works well, but when I pass the args as "process" it gives insufficient privileges error - Verify that you have sufficient privileges to start system services. 

Please advise what is getting missed out (or) what should be the special privilege for the userid.

**Comment by carlpett** [comment]
Are you running the service as a non-default user?

**Comment by carlpett** [comment]
Also, the process collector was added in 0.2.6, so are you using the correct version there?

**Comment by Ajeyprabhu** [comment]
Am running the service as a Admin user.

**Comment by Ajeyprabhu** [comment]
0.2.6 worked out .. Thanks a lot, Carl ..
