### ISSUE TITLE
Doc Request: Cannot get "-collector.process.processes-where" flag to work

### ISSUE THREAD

**Issue by vbeausoleil** [martinlindhe/wmi_exporter#105]
Hi,

Would it be possible to have a filter example for the "-collector.process.processes-where" flag? I can't seem to get it to work.

I get the following errors when I open localhost:9182/metrics

time="2017-08-09T16:32:16-04:00" level=error msg="[ERROR] failed collecting process metrics: <nil> Exception occurred. (Invalid query )" source="process.go:142"

time="2017-08-09T16:32:16-04:00" level=error msg="ERROR: process collector failed after 0.008049s: Exception occurred. (Invalid query )" source="exporter.go:90"

Thank you!

**Comment by martinlindhe** [comment]
Indeed, this feature is pretty low level so an example would be good.

You can do something like

`.\wmi_exporter.exe "-collectors.enabled" "process" "-collector.process.processes-where" "Name='firefox'"`
or
`.\wmi_exporter.exe "-collectors.enabled" "process" "-collector.process.processes-where" "IDProcess=1128"`

The available columns are documented in https://msdn.microsoft.com/en-us/library/aa394323(v=vs.85).aspx

**Comment by martinlindhe** [comment]
@vbeausoleil I hope the added example are useful, if not please reach out again!

**Comment by vbeausoleil** [comment]
It works! Thank you for the quick reply @martinlindhe

Are there any plans to implement a similar filter feature for the service collector? If not, I might give it a shot when I have some free time.

**Comment by martinlindhe** [comment]
Nothing planned at the moment, but if it is a useful feature then it would be very welcome!
It should be quite similar to what's already implemented in collector/process.go
