### ISSUE TITLE
Grafana ( and prometheus )

### ISSUE THREAD

**Issue by roiromanoclick** [martinlindhe/wmi_exporter#117]
I have some issue with calculation query with wmi\node exporters from Prometheus to grafana. I have a multi graph with wmi, and now I have more new Linux instances. How can I add the ” label_values (node_boot_time, name)” with the wmi together?

**Comment by martinlindhe** [comment]
Hello @roiromanoclick 

General prometheus usage questions belong elsewhere, see https://prometheus.io/community/
