### ISSUE TITLE
Automatically convert WMI metrics to prometheus

### ISSUE THREAD

**Issue by martinlindhe** [martinlindhe/wmi_exporter#12]
@brian-brazil wrote in #5 
> I'm still perusing the docs, but I have a crazy idea.

> It looks like it's possible to get to CounterType with WMI (though we'll need to use a different WMI library). Given that and presuming that metric naming is relatively consistent we may be able to fully automate the transformation of metric names and the user would only have to provide a WMI class name. We'll likely still need some hardcoded rules to fix e.g. bytes->megabytes.

> I also note we cannot completely rely on documentation alone for CounterTypes - several of the ones in this PR changed in Windows 2000 (which means this won't quite work on XP).

> The counter types is what changed between versions.

> What I'd see happening for IIS/SQL is that you'd run the WMI exporter but with different flags just pulling in IIS/SQL metrics.

**Comment by martinlindhe** [comment]
@brian-brazil wrote
> What I'd see happening for IIS/SQL is that you'd run the WMI exporter but with different flags just pulling in IIS/SQL metrics.

Would this satisfy the above wish? #17 
It now works like the node_exporter, taking a `--collectors.enabled` flag

**Comment by brian-brazil** [comment]
#17 still requires code to be written per WMI class. What I'm proposing is that you'd only have to pass in the WMI class, and everything else (as much as practical) is automatic.
