### ISSUE TITLE
tooling: use dep

### ISSUE THREAD

**Issue by martinlindhe** [martinlindhe/wmi_exporter#121]
I've started the process of using [dep](https://github.com/golang/dep) for vendoring in some of my golang projects, and want to bring it up here.

Pros for using `dep` as compared to other solutions:
* Is on the way to becoming merged in `go`, possibly around go 1.10.
* `dep prune` removes unnessecary files from the `vendor` folder such as text files, making it smaller
* Many others, see the project homepage

Cons:
* The `dep` tool requires go 1.8+, but is only required to use for updating vendored dependencies.

We currently use govendor iirc.

The `vendor` folder is automatically used as of go 1.6 (or 1.5 using the GOVENDOREXPERIMENT=1 env)

Any thoughts about this @carlpett or @brian-brazil ?

For example, does any parts of the rest of prometheus ecosystem embrace `dep`, or any other vendoring tools?

**Comment by carlpett** [comment]
I personally use `dep` as well for new projects. The main objection so far is that it isn't exactly fast at this point. But wmi_exporter doesn't have _that_ many dependencies anyway, so I don't think it will be much of an issue.
I don't have any strong feelings either way.

**Comment by martinlindhe** [comment]
Note: the `vgo` development might retire `dep`, I've no idea what will happen at this point. :-)

https://research.swtch.com/vgo

**Comment by martinlindhe** [comment]
Another note from #166:
