### ISSUE TITLE
Malfunction: query processes with the same name returns one process.

### ISSUE THREAD

**Issue by mikalais** [martinlindhe/wmi_exporter#123]
E.g. I would like to enable process collector and specify a custom query:

`.\wmi_exporter.exe "-collectors.enabled" "process" "-collector.process.processes-where" "Name='firefox'"`

Even if there are 4 processes with the same name 'firefox', wmi_exporter returns metrics for only one of them.

**Comment by martinlindhe** [comment]
To get all the processes, you need to change the where-clause to Name LIKE 'firefox%'

**Comment by mikalais** [comment]
oh.. I tried ='%firefox%'. Shame on me. Thank you!

**Comment by martinlindhe** [comment]
No worries, it has confused me too :-)
