### ISSUE TITLE
WMI Exporter - wmi iis worker request errors tatal 

### ISSUE THREAD

**Issue by roiromanoclick** [martinlindhe/wmi_exporter#124]
Hi Marthin , i installed the latest ver(2.7) wmi exporter on my machines and i see only 4 status code (403,500,401,404) , why i didnt see 503 , 200, 499 ?
Thank you.

**Comment by carlpett** [comment]
Hi @roiromanoclick,
These are the only error codes that IIS has counters for, sadly. You'll need to check the log files if you want all the actual responses. Check out [stream_exporter](https://github.com/carlpett/stream_exporter) or [mtail](https://github.com/google/mtail) to do log file metrics.
