### ISSUE TITLE
installation procedure shall include configuration of the firewall

### ISSUE THREAD

**Issue by marcseguin** [martinlindhe/wmi_exporter#130]
it would be nice if the installation procedure would include the configuration of the windows firewall and opens it for the ports or exe.

**Comment by carlpett** [comment]
@marcseguin It _should_ already do this... (Specifically [this line](https://github.com/martinlindhe/wmi_exporter/blob/master/installer/wmi_exporter.wxs#L37) if you know WiX)

Do you have some system details from where this does not work?

**Comment by marcseguin** [comment]
I installed it on a Windows 10, 1709 built when I had the issue. I repeated now on a Windows Server 2016 where it worked!
I will make another attempts on Windows 10 - even if this is not necessary the target environment ;-)

**Comment by carlpett** [comment]
Ok, let me know how it goes :) Perhaps the firewall isn't enabled for the profile (private/domain/public) of the network you are on?

**Comment by martinlindhe** [comment]
@marcseguin did you resolve your issue about the win10 firewall?

**Comment by marcseguin** [comment]
Hello, the issue is solved. Thx Marc
