### ISSUE TITLE
IIS Collector fails, when Application has more than one worker processes.

### ISSUE THREAD

**Issue by icanit** [martinlindhe/wmi_exporter#131]
If IIS App was multiple worker processes for one application, then wmi_exporter fails to collect (exporter returns http 500), because it tries add metrics for each worker with same app name label.

One of solutions could be to use pids as additional label for worker's metrics to separate them, as i implemented here: https://github.com/icanit/wmi_exporter/commit/6e54dc59d54d272e02883850b6cdda073bf481fe

If this is acceptable solution i can make pull reqest with it, or lets discuss another solution of this issue.

**Comment by martinlindhe** [comment]
Looks like a good solution to me, but I would hope for @carlpett to have a say, since he originally wrote the iis code in https://github.com/martinlindhe/wmi_exporter/commit/bf8c9228fbebc93d6bbd8f080190abd592fe110d

**Comment by carlpett** [comment]
I'm not really a fan of pid labels, but I guess there isn't much else to distinguish the workers... One alternative would be to pre-aggregate across all workers, but that isn't very nice either.
I'll have a look at the PR!

**Comment by roccozanni** [comment]
Hi there, thanks for the amazing work!

Any change to have a new release of the exporter now that #132 is merged?

**Comment by martinlindhe** [comment]
@roccozanni thanks for the reminder!

Released v0.2.8 https://github.com/martinlindhe/wmi_exporter/releases/tag/v0.2.8

**Comment by icanit** [comment]
Hello, @VR6Pete 

I am using following setup for monitoring IIS state across two web servers via grafana:
![image](https://user-images.githubusercontent.com/2733119/36297659-05d65040-1305-11e8-84da-62cb5f7d0ca2.png)


With queries:
IIS connections: `wmi_iis_current_connections{instance="etaper01"}`
IS Worker Threads Count: `wmi_process_thread_count{process="w3wp"}`
Worker PIDs (with disables Axes): `sum by (app) (wmi_iis_worker_threads{instance="etaper01"})`
IIS Worker CPU: `sum by (process_id) (rate(wmi_process_cpu_time_total{instance="etaper01",process="w3wp"}[5m]))`
IIS Worker RAM: `wmi_process_private_bytes{instance="etaper01",process="w3wp"}`

I am using "Worker PIDs" panel for manualy connecting pid with pool name, when alert happens, thanks for this pull request  changes now wmi_iis_worker_threads contains pairs of pid and pool name.

I hope this will be useful for You.

**Comment by VR6Pete** [comment]
Hi @icanit  That's a great bit of information I have now got a nice set of dashboards.

It's a pity that there is no way to lookup the PID and map the app name in a query - vlookup esq in excel. unsure if this is even possible?

Further question for you if I may - Can you please tell me how you have got the colours on the worker PID to match dynamically on each of the graphs ? 

Thanks.

Pete

**Comment by icanit** [comment]
Hi, @VR6Pete

This is coincidence, that collors with same pid has same color on my screenshot, i think there no way to make them match dynamicaly across multiple panels :(

**Comment by VR6Pete** [comment]
Damn :) Thanks for your reply though !
