### ISSUE TITLE
this installation package could not be opened contact the application vendor to verify

### ISSUE THREAD

**Issue by Passpes** [martinlindhe/wmi_exporter#133]
Greetings folks,

So I tried the following command after installing "wmi_exporter.exe" to enable iis and processes monitoring:
msiexec /i "C:\Program Files (x86)\wmi_exporter\wmi_exporter.exe" ENABLED_COLLECTORS=process,iis LISTEN_PORT=500

but then I get the following error:
![image](https://user-images.githubusercontent.com/6490137/32782959-6d5f1972-c94a-11e7-9454-e50464b98c69.png)

so any ideas to fix this and getting process and IIS monitoring?

**Comment by carlpett** [comment]
`msiexec` can only run on msi files, it cannot do anything with the exe file.
I would suggest that you uninstall, and then run `msiexec` on the .msi file instead.

**Comment by martinlindhe** [comment]
msiexec only works on the .msi files, so download a .msi from our releases page and use that instead.
