### ISSUE TITLE
Please expose the command line for the monitored processes

### ISSUE THREAD

**Issue by alexandrul** [martinlindhe/wmi_exporter#134]
It would be very useful when having multiple instances of the same process with different command line arguments.

**Comment by brian-brazil** [comment]
This may make sense as an _info metric, but generally Prometheus is not intended for this class of monitoring.

**Comment by alexandrul** [comment]
When having multiple instances of the same process, the command line could be the only way to group them in a human-friendly way (think `java.exe` on some application servers).

The command line can be retrieved with this query: `select Handle, Name, CommandLine from Win32_Process` (`Handle` seems to be identical with `ProcessId`, and `Caption` seems to have the same value as `Name`).

**Comment by alexandrul** [comment]
As a workaround I'm using metricbeat 6.2.1 which is also collecting the command line for monitored processes (a logstash regex is providing the extra context info for my dashboard).

**Comment by carlpett** [comment]
Currently our position is that we will not be implementing this - it will likely lead to an explosion of the number of series, which will potentially have negative consequences for the Prometheus server.
