### ISSUE TITLE
ticksToSecondsScaleFactor

### ISSUE THREAD

**Issue by marcseguin** [martinlindhe/wmi_exporter#138]
Hello, 
what is the idea of the "ticksToSecondsScaleFactor" used as multiplier in some the WMI performance indicators?
Thx

**Comment by carlpett** [comment]
Hi @marcseguin,
WMI reports many of the times as ticks. But for the metrics, we want to report times in seconds instead. So this is just a scaling constant we use to convert from ticks to seconds.

Makes sense?

**Comment by carlpett** [comment]
I'll close this as inactive, but feel free to reopen if this was not what you were looking for!
