### ISSUE TITLE
Feature: CPU metrics

### ISSUE THREAD

**Issue by carlpett** [martinlindhe/wmi_exporter#14]
Possibly relevant WMI class: `Win32_PerfRawData_Counters_ProcessorInformation`, provides these fields:

```
Name (socket#+core#)
AverageIdleTime
AverageIdleTime_Base
C1TransitionsPersec
C2TransitionsPersec
C3TransitionsPersec
ClockInterruptsPersec
DPCRate
DPCsQueuedPersec
IdleBreakEventsPersec
InterruptsPersec
ParkingStatus
PercentC1Time
PercentC2Time
PercentC3Time
PercentDPCTime
PercentIdleTime
PercentInterruptTime
PercentofMaximumFrequency
PercentPerformanceLimit
PercentPriorityTime
PercentPrivilegedTime
PercentPrivilegedUtility
PercentPrivilegedUtility_Base
PercentProcessorPerformance
PercentProcessorPerformance_Base
PercentProcessorTime
PercentProcessorUtility
PercentProcessorUtility_Base
PercentUserTime
PerformanceLimitFlags
ProcessorFrequency
ProcessorStateFlags
```

Haven't found any MSDN documentation of this class, so potentially there might be better ones? It was the only one reported on my test machine, though

**Comment by carlpett** [comment]
`Win32_PerfRawData_PerfOS_Processor` might also be a candidate

**Comment by martinlindhe** [comment]
https://msdn.microsoft.com/en-us/library/aa392397(v=vs.85).aspx mentions "Classes derived from Win32_PerfRawData and from Win32_PerfFormattedData must be used with a refresher object.", not sure we currently have ability to probe these using the current wmi lib. (research needed)

**Comment by brian-brazil** [comment]
The "refresher object" here is Prometheus.

**Comment by martinlindhe** [comment]
Oh :-) guess it sounded more complicated than it is

**Comment by brian-brazil** [comment]
Yeah, it's all written from the standpoint that you're writing a realtime console.

**Comment by martinlindhe** [comment]
Did we resolve this by merging #26 ?

**Comment by carlpett** [comment]
Yes, I think so
