### ISSUE TITLE
missing data in collected time series

### ISSUE THREAD

**Issue by madeinoz67** [martinlindhe/wmi_exporter#140]
version: 0.2.7

I'm seeing on a number of wmi hosts (not all) missing time series data that appears to be determanistic (although not always)

This is only being observed on wmi_exporter nodes, linux node exporter exhibit no missing data.
the wmi nodes are not under any abnormal load during these drops in data.

I'm scraping about 30 wmi_nodes on 3 seperate seperate jobs based on their role , i.e. domain server has general collectors enabled + dns + AD, web servers have general + IIS and then general hosts have default collectors enabled .  all jobs have scrape interval set is 20Sec.  prometheus dashboard is not reporting any missed scrapes.

Mainly being seen on disk and memory metrics, however in some cases also on system_threads.  More than likely is something I'm not doing correctly.  These are mainly on default exporter install, although am seeing on on exporters with IIS enabled.

What is the recommended scrap interval for this exporter?

![2017-12-12_10-45-34](https://user-images.githubusercontent.com/4160293/33864956-3aae17da-df2a-11e7-89f5-406fba8cb375.png)
![2017-12-12_10-53-27](https://user-images.githubusercontent.com/4160293/33865023-bb04e97c-df2a-11e7-9eb7-ada9bc5aeeee.png)

**Comment by martinlindhe** [comment]
This reminds me about an issue that has popped up before,
in that some WMI queries, on some machines took very long time to respond. This could cause gaps in the timeline.

You can debug this by manually starting wmi_exporter.exe on a machine that you know this happens on, and keep an eye on the terminal  output.

You can see more info about this being debugged in this issue: https://github.com/martinlindhe/wmi_exporter/issues/122

**Comment by madeinoz67** [comment]
@martinlindhe thanks for that.  I will look at doing the debugging.

my current work around is to make null values connected so it doesn't show up the gaps on the screen

![2017-12-13_08-27-22](https://user-images.githubusercontent.com/4160293/33915685-9fdf8606-dfdf-11e7-93d1-beaf4b962bc4.png)

**Comment by marbis-leo** [comment]
It's a bug in WMI, see #89

**Comment by leoluk** [comment]
It's a bug in WMI, see #89.

I think I found a workaround, give me a few days to clean up the code and I'll publish it.

**Comment by VR6Pete** [comment]
I’ve seen this myself. Has this now been fixed ?

**Comment by madeinoz67** [comment]
I will close this one as a duplicated of #89
