### ISSUE TITLE
Windows Firewall Rule not working properly

### ISSUE THREAD

**Issue by eriklg** [martinlindhe/wmi_exporter#144]
I enabled the windows firewall after installing the wmi_exporter and it wasn't working properly with the default rule. I had to change the firewall rule to not be specific to the wmi_exporter.exe program but rather to "All programs that meet the specified conditions"

**Comment by carlpett** [comment]
Hi @eriklg,
Thanks for reporting! What version of Windows did this happen on? 
Did I understand correctly that you had the firewall disabled while installing the exporter, and then enabled it after installation?

**Comment by eriklg** [comment]
Hi @carlpett , 
That's correct on the status of the firewall. I am using Server 2012 R2 Standard Edition.

**Comment by carlpett** [comment]
We seem to have dropped this, but since it has been over two years, I'm not sure this is a problem any more. Feel free to re-open if it is still causing issues.
