### ISSUE TITLE
Question: can this project manage multiple remote computers? If you can hope to give some advice.

### ISSUE THREAD

**Issue by liyang010813** [martinlindhe/wmi_exporter#146]
Question: can this project manage multiple remote computers? If you can hope to give some advice.thank you!

**Comment by carlpett** [comment]
Hi @liyang010813,
No, it is intended to be installed locally on each monitored machine, which is in line with Prometheus best practices.

**Comment by liyang010813** [comment]
@carlpett That means you can only monitor your local computer, right? If, then, Prometheus exists on all remote computers, it is not possible to manage it comprehensively.

**Comment by liyang010813** [comment]
@carlpett then this project exist  what's the meaning

**Comment by carlpett** [comment]
I think you may have mixed up the relation between Prometheus and exporters. You'll have one (or more) central Prometheus servers, which scrape your exporters, that are deployed on all your targets (Windows servers, in the case of the wmi_exporter).
So you do not have to manage a prometheus installation on each machine.
