### ISSUE TITLE
IIS collector fails on IIS 10.0 - 2016 Server

### ISSUE THREAD

**Issue by dvictor1** [martinlindhe/wmi_exporter#148]
error is here:
[ERROR] failed collecting iis metrics: <nil> Exception occurred. (Invalid class )

System  : Microsoft Windows Server 2016 Datacenter
ServicePackMajorVersion : 0
OSArchitecture          : 64-bit
BuildNumber             : 14393

**Comment by dvictor1** [comment]
never mind, turned as Windows issue.

**Comment by lfarnell** [comment]
@dvictor1 can you post what you did to fix this issue? Running into this as well.
