### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by martinlindhe** [martinlindhe/wmi_exporter#15]
go get -u github.com/prometheus/common
go build .

```
# github.com/prometheus/common/expfmt
..\..\prometheus\common\expfmt\decode.go:92: cannot convert v.Name (type *string) to type model.LabelValue
..\..\prometheus\common\expfmt\decode.go:103: cannot convert l.Value (type *string) to type model.LabelValue
..\..\prometheus\common\expfmt\decode.go:106: cannot convert l.Name (type *string) to type model.LabelName
..\..\prometheus\common\expfmt\decode.go:171: invalid case io_prometheus_client.MetricType_COUNTER in switch on f.Type (mismatched types io_prometheus_client.MetricType and *io_prometheus_client.MetricType)
..\..\prometheus\common\expfmt\decode.go:173: invalid case io_prometheus_client.MetricType_GAUGE in switch on f.Type (mismatched types io_prometheus_client.MetricType and *io_prometheus_client.MetricType)
..\..\prometheus\common\expfmt\decode.go:175: invalid case io_prometheus_client.MetricType_SUMMARY in switch on f.Type (mismatched types io_prometheus_client.MetricType and *io_prometheus_client.MetricType)
..\..\prometheus\common\expfmt\decode.go:177: invalid case io_prometheus_client.MetricType_UNTYPED in switch on f.Type (mismatched types io_prometheus_client.MetricType and *io_prometheus_client.MetricType)
..\..\prometheus\common\expfmt\decode.go:179: invalid case io_prometheus_client.MetricType_HISTOGRAM in switch on f.Type (mismatched types io_prometheus_client.MetricType and *io_prometheus_client.MetricType)
..\..\prometheus\common\expfmt\decode.go:195: cannot convert p.Name (type *string) to type model.LabelName
..\..\prometheus\common\expfmt\decode.go:195: cannot convert p.Value (type *string) to type model.LabelValue
..\..\prometheus\common\expfmt\decode.go:195: too many errors
```

due to recent changes in prometheus. Cause of appveyor build failure.
Investigating..

ping @carlpett

**Comment by martinlindhe** [comment]
Failure seems to be related to ongoing work in common + golang_client, and might be resolved as soon as this patch lands https://github.com/prometheus/client_golang/pull/233

Failure in common repo: https://travis-ci.org/prometheus/common/jobs/155817891 from original failing commit: https://github.com/prometheus/common/pull/52

**Comment by carlpett** [comment]
I guess this is a friendly reminder that vendoring is a required part of building go applications. We should probably use `promu`: https://github.com/prometheus/promu

**Comment by carlpett** [comment]
Hm, apparently promu doesn't mandate a specific vendoring application? We should probably use it anyway, but then we need to choose one of the dozen or so vendorers

**Comment by carlpett** [comment]
... or maybe it is totally overkill since we do not produce docker images, and do not really cross-compile (apart from possibly x86/x64). But we should at least start vendoring. I just can't find out which vendorer all the other prometheus packages use?
@brian-brazil Any opinions on how a "well-behaved" exporter should look in order to be consistent with the rest of the ecosystem?

**Comment by brian-brazil** [comment]
We use govendor, but this is your exporter so you're free to use what you like.

**Comment by martinlindhe** [comment]
Is it really meaningful to vendor the prometheus client stuff? I mean, is it expected the prometheus masters are breaking from time to time, or was this a exceptional situation?
