### ISSUE TITLE
totals documented as gauge (wmi_system_context_switches_total, wmi_system_exception_dispatches_total)

### ISSUE THREAD

**Issue by ecki** [martinlindhe/wmi_exporter#151]
Hello, for the following two metrics it looks like this is a counter and not a gauge. This also means the "Persec" description is probably wrong?

```
# HELP wmi_system_context_switches_total PerfOS_System.ContextSwitchesPersec
# TYPE wmi_system_context_switches_total gauge
wmi_system_context_switches_total 1.5177897e+07
# HELP wmi_system_exception_dispatches_total PerfOS_System.ExceptionDispatchesPersec
# TYPE wmi_system_exception_dispatches_total gauge
wmi_system_exception_dispatches_total 28226
```

This is wmi_exporter 0.2.8 on Win 10 1703 x64 german.

**Comment by carlpett** [comment]
Hi @ecki,
Thanks for noticing! That is indeed an error, it should be a counter. 
The persec-naming is indeed wrong, and this collector might have been written before that was noticed.

Would you feel comfortable making a PR for this?
