### ISSUE TITLE
Disable services collectors in default configuration

### ISSUE THREAD

**Issue by sandersaares** [martinlindhe/wmi_exporter#154]
In environments where I do not care about service status, the services collector generates a huge amount of metrics when using the default install (as Windows comes with many services). I request that the Windows services collector be disabled by default, to keep the default set tidy and data-size-efficient.

**Comment by martinlindhe** [comment]
We are unlikely to change defaults to suit your specific needs.

Please configure the collectors you need using `-collectors.enabled`.

**Comment by sandersaares** [comment]
This is not about my specific needs. I would think it to be in the interest of this software to provide reasonable defaults. It does not seem reasonable that the majority of the default metrics are relatively static metrics about services.

What is the rationale behind the current set of defaults?

**Comment by steinbrueckri** [comment]
I have the same opinion as martinlindhe. 
A Monitoring agent should monitor services by default.

**Comment by martinlindhe** [comment]
The rationale about the current defaults is that they are supposed to be available on all supported OS:es.
We can not offer a "set and forget" for monitoring. The user needs to think about what they want to monitor and base their decisions on that.

**Comment by MichaelHellmann** [comment]
In my environment I need the textfile collector **only** and I thought by using "--collectors.enabled textfile" all other collectors are disabled but they are still enabled.
So, that option does not overrule the default collectors.
What about a "--collectors.disabled" instead?

**Comment by carlpett** [comment]
@MichaelHellmann Hm, that would be a bug in that case - using `--collectors.enabled` should explicitly set only those collectors and disable all others.

**Comment by carlpett** [comment]
Looking closer, we even have a unit-test for this. Could you paste your full invocation?

**Comment by MichaelHellmann** [comment]
I installed it in my Windows environment by
_msiexec /i C:\Prometheus\wmi_exporter-0.5.0-amd64.msi ENABLED_COLLECTORS=textfile_
and the service looks like this
_"C:\Program Files\wmi_exporter\wmi_exporter.exe" --log.format logger:eventlog?name=wmi_exporter --telemetry.addr :9182 --collectors.enabled textfile_
On http://localhost:9182/metrics I see a lot of wmi_* data.

**Comment by carlpett** [comment]
Thanks. If you find `wmi_exporter_collector_success`, which metrics are returned there?

**Comment by MichaelHellmann** [comment]
I just reinstalled the service and it looks much better now :-)
I guess I made a mistake when I installed it the first time.
Now it looks like this.
Thanks a lot and sorry for the confusion.

```
wmi_exporter_build_info{branch="master",goversion="go1.11",revision="2766f0e3af9a7570d6b812eaf4bf262754c2d47f",version="0.5.0"} 1
# HELP wmi_exporter_collector_duration_seconds wmi_exporter: Duration of a collection.
# TYPE wmi_exporter_collector_duration_seconds gauge
wmi_exporter_collector_duration_seconds{collector="textfile"} 0.0010122
# HELP wmi_exporter_collector_success wmi_exporter: Whether the collector was successful.
# TYPE wmi_exporter_collector_success gauge
wmi_exporter_collector_success{collector="textfile"} 1
# HELP wmi_textfile_mtime_seconds Unixtime mtime of textfiles successfully read.
# TYPE wmi_textfile_mtime_seconds gauge
wmi_textfile_mtime_seconds{file="fa2ad.prom"} 1.544195285e+09
# HELP wmi_textfile_scrape_error 1 if there was an error opening or reading a file, 0 otherwise
# TYPE wmi_textfile_scrape_error gauge
wmi_textfile_scrape_error 0
```

**Comment by carlpett** [comment]
:+1:
