### ISSUE TITLE
[question] Query for missing service

### ISSUE THREAD

**Issue by VR6Pete** [martinlindhe/wmi_exporter#156]
Hi there. 

I would like to identify with Prometheus if a windows service is not present.

**Comment by VR6Pete** [comment]
Whoops. Clicked submit a little too soon. 

I’m looking for advice to be able to identify where a windows service is not present. I’ve tried a few queries against wmi exporter metrics but to no avail. 

Ultimately I’d like to create an alert for if the service does not exist. 

Cheers

Pete

**Comment by carlpett** [comment]
Did you try with the [absent](https://prometheus.io/docs/prometheus/latest/querying/functions/#absent()) function?

**Comment by VR6Pete** [comment]
I’ll give that ago :) wasn’t aware such function existed. Thank you.

**Comment by carlpett** [comment]
No problem :)

**Comment by VR6Pete** [comment]
Still having an issue with this. All the queries I have tried have ommited the instance name and therefore just have a general alert being generated but not against any specific target host. 

Do you have any tips around this? Cheers Pete
