### ISSUE TITLE
How to monitor specific multiple services

### ISSUE THREAD

**Issue by e9d26** [martinlindhe/wmi_exporter#157]
I have a question.
As described in README.md, I understood wmi_exporter can use specify custom query as below.
`.\wmi_exporter.exe "-collectors.enabled" "service" "-collector.service.services-where" "Name='wmi_exporter'"`

but, If I'd like to monitor ***specific multiple services***, how should I write command line argument?
I tried to write as below, but I failed.
`.\wmi_exporter.exe "-collectors.enabled" "service" "-collector.service.services-where" "Name='wmi_exporter' or Name='msiserver'"`

**Comment by carlpett** [comment]
Hi @e9d26,
The argument is put directly into the `WHERE` clause of the WMI query. For troubleshooting, you can use Powershell with `Get-WmiObject -Query "..."`. 
I'm travelling without access to a Windows environment to try right now, but if you are unable to get it working, I'll have a look later this week!

**Comment by e9d26** [comment]
Hi @carlpett 
Thank you for your reply.
I followed your advice and It got working!! Thanks!!

**Comment by MartinRoenneburg** [comment]
Hi @e9d26,
Could you share your solution ?
I just ran into the problem...

**Comment by MartinRoenneburg** [comment]
Got it.
-collector.service.services-where "Name LIKE 'MyServicePrefix%' OR Name='mylittleotherservice'"

I think this could be a good additional example for the readme.
