### ISSUE TITLE
[Question] add new Collector : Win32_PerfFormattedData_Tcpip_NetworkInterface 

### ISSUE THREAD

**Issue by nwies** [martinlindhe/wmi_exporter#162]
hello,

could it be possible to implement Win32_PerfFormattedData_Tcpip_NetworkInterface 
In order to have a bandwidth usage as describe in https://ss64.com/ps/syntax-get-bandwidth.html ?

thanks for your feedback.

**Comment by martinlindhe** [comment]
What exactly is lacking from the existing 'net' collector, based on Win32_PerfRawData_Tcpip_NetworkInterface ?

**Comment by nwies** [comment]
the ability to have a direct to the "CurrentBandwidth" and "BytesTotalPersec" items in order to calculte a % of use. I didn't see same items on the Win32_PerfRawData_Tcpip_NetworkInterface

**Comment by martinlindhe** [comment]
I see them here:

```
Get-WmiObject -class Win32_PerfRawData_Tcpip_NetworkInterface |select BytesTotalPersec, CurrentBandwidth,PacketsPersec

BytesTotalPersec CurrentBandwidth PacketsPersec
---------------- ---------------- -------------
    375756320403       1000000000     293819026
               0                0             0
         3011465           100000         21063
```

**Comment by nwies** [comment]
ok. my bad.
you can close this ticket
thanks a lot.

**Comment by martinlindhe** [comment]
BytesTotalPersec  is exported in the net collector as BytesTotal,
PacketsPersec is exported as PacketsTotal

It seems we don't currently export CurrentBandwidth

**Comment by martinlindhe** [comment]
CurrentBandwidth seems to hold the link speed of the ethernet interface. Not sure why you would need that to calculate current bandwidth.

**Comment by nwies** [comment]
i would Like to have a % of use from the possible bandwidth.
the formula should be :
result = FormatNumber((( BytesTotal * 8  / objItem.CurrentBandwidth) * 100))

**Comment by martinlindhe** [comment]
Okay. We can export CurrentBandwidth to make it possible.

**Comment by nwies** [comment]
thanks

**Comment by martinlindhe** [comment]
I released a new version exporting current_bandwidth, quick test locally gives

```

# HELP wmi_net_current_bandwidth (Network.CurrentBandwidth)
# TYPE wmi_net_current_bandwidth counter
wmi_net_current_bandwidth{nic="Intel_R__Ethernet_Connection__2__I219_V__2"} 1e+09
wmi_net_current_bandwidth{nic="Teredo_Tunneling_Pseudo_Interface"} 100000
```

You can download it here:
https://github.com/martinlindhe/wmi_exporter/releases/tag/v0.2.10

**Comment by martinlindhe** [comment]
You should be able to use the exported values to calculate a % using the prometheus queries

https://prometheus.io/docs/prometheus/latest/querying/basics/
