### ISSUE TITLE
[Question] Does wmi_exporter has log file?

### ISSUE THREAD

**Issue by jinh-dk** [martinlindhe/wmi_exporter#163]
I am running  wmi_exporter on a few windows computers.  

I noticed that on one computer, sometimes Prometheus couldn't reach the exporter.  (diffcult to reproduce, only happened once or twice per week.  The error normally disappeared after some time (5 - 30 minutes). 

Because this computer is a bit special, which is using a separated switch than others, and also doing some special work,   

So it might be network issue, but I am not sure.  I would like to know if wmi_exporter has a log file that I can have a look.  

BTW, does wmi_exporter use or dependent on "_WMI Performance Adapter Service_"?

**Comment by carlpett** [comment]
We output the log to the Windows Event Log, have a look under the Applications section there.
(There's quite a bit of text before each log entry along the lines of "Cannot find ...", that can be ignored, see #22)
