### ISSUE TITLE
Win32_ScheduledJob

### ISSUE THREAD

**Issue by VR6Pete** [martinlindhe/wmi_exporter#164]
Hi there. 

Just wondering if it’s possible to add support for this in the future?

https://msdn.microsoft.com/en-us/library/aa394399(v=vs.85).aspx

Would be useful to monitor such activities across an estate via Prometheus. 

Thanks

Pete

**Comment by steinbrueckri** [comment]
👍

**Comment by VR6Pete** [comment]
Not too sure how this would work now as the "at" command has been deprecated therefore Win32_ScheduledJob returns no items. 

Unsure if the new schtasks.exe has an API to query but I don't think this idea with float.

**Comment by carlpett** [comment]
As noted, that class doesn't seem like a good fit due to deprecation. If we could find another one, that would be a reasonable new feature.

**Comment by VR6Pete** [comment]
I’ve not yet come across one. Probably ok to close this and open a new issue as/when an appropriate class is discovered.
