### ISSUE TITLE
Missing process_* metrics

### ISSUE THREAD

**Issue by hairyhenderson** [martinlindhe/wmi_exporter#165]
It'd quite useful to be able to monitor generic process metrics of the exporter itself, and I'm used to exporters having at least `process_start_time_seconds` exposed.

Obviously this is done by default on Linux by the code in https://github.com/prometheus/client_golang/blob/master/prometheus/process_collector.go, and that can't work because Windows has no `/proc` filesystem.

I'd rather not have to configure wmi_exporter to gather process metrics on itself, though that is a possible workaround.

Ultimately the fix belongs here - https://github.com/prometheus/client_golang/issues/376 - but I'm logging this issue in this repo in case there's some interest in using some of the WMI exporter code for this.

Thanks!

**Comment by carlpett** [comment]
Hi @hairyhenderson,
Sorry for missing this! And it is useful indeed. Should be simple enough.
