### ISSUE TITLE
Prometheus reporting connection refused

### ISSUE THREAD

**Issue by reedhastings** [martinlindhe/wmi_exporter#168]
Trying to find out why Prometheus is reporting "connection refused."  I have tried installing several times specifying ports, no port, ip binding, and still Prometheus will not connect.  Windows firewall is not the issue.  Is there a way I can find out what port wmi exporter is on?  Not even sure what the service name is.

**Comment by martinlindhe** [comment]
wmi_exporter uses port 9182 unless you configured it otherwise.

See https://github.com/martinlindhe/wmi_exporter#installation

**Comment by reedhastings** [comment]
Thank you for the quick reply!  I tried installing using the default port and two other ports.  I cannot connect locally from the machine on 9182, 9100, or 5000 (the ports I tried to install as).  Is there a way to check that the service is installed properly and running using another method?

**Comment by martinlindhe** [comment]
>  Is there a way to check that the service is installed properly and running using another method?

Run `services.msc`

**Comment by carlpett** [comment]
@reedhastings Did you find the problem?

**Comment by carlpett** [comment]
Closing for lack of info, feel free to re-open if there is new developments.
