### ISSUE TITLE
CIM over WMI?

### ISSUE THREAD

**Issue by Outek** [martinlindhe/wmi_exporter#172]
Hi

Im new to Golang/Go, maybe i'm getting some points really wrong in your project.
Do you ever thought about to change from WMI to CIM Queries?

Maybe there are some benefits doing this, maybe it is different with GO, or simply it is of out scope for you.

Maybe remoting is a thing? Run the queries from one node and trigger multiple other server?

**Comment by martinlindhe** [comment]
What benefits do you see from using CIM?

In my point of view, CIM is adding no value to what we already have.

The prometheus model of monitoring is adding a exporter to each system that needs to be monitored. For windows machines that is the wmi_exporter.

CIM on the other hand, is a way to exchange WMI information between windows systems. This is redundant to our cause as far as I can see.

**Comment by Outek** [comment]
Have you ever made some tests with nanoserver? Maybe there is the usecase using CIM.

**Comment by martinlindhe** [comment]
I have not.

Could you please expand on what benefits you see from using CIM here? I fail to see it.

**Comment by Outek** [comment]
I thought, there is no wmi in nanoserver, but this is wrong. 
I thought with cim you can define a probing host to monitor remote nanoservers. So your choice for using wmi over cim is right. 👍

**Comment by martinlindhe** [comment]
Great :-) I'll go ahead and close this issue then. Please add more comments or create a new issue if you feel there is more to discuss!
