### ISSUE TITLE
Exe fails when specifying a custom query via Powershell

### ISSUE THREAD

**Issue by karl-johan-grahn** [martinlindhe/wmi_exporter#173]
We run wmi_exporter.exe via NSSM and Powershell, but it fails when specifying a custom query. Kind of like this:
```
[string] $args = '"-telemetry.addr" ":9182" "-collectors.enabled" "cpu,cs,logical_disk,net,os,process,service,system" "-collector.process.processes-where" `
                      "(Name=''some.exe'') or (Name=''another.exe'') or (Name=''another2.exe'') or (Name=''another3.exe'') or (Name=''another4.exe'') or `
                       (Name=''another5.exe'') or (Name=''another6.exe'') or (Name=''another7.exe'') or (Name LIKE ''Service%'')"'
nssm.exe install "wmi_exporter" "C:\Program Files\wmi_exporter\wmi_exporter.exe" $args
```

It enables the collectors and starts it on the correct port, but with the where clause we just get this error:
```
[ERROR] failed collecting process metrics: <nil> Exception occurred. (Invalid query )
"ERROR: process collector failed after 0.051001s: Exception occurred. (Invalid query )" source="exporter.go:90"
```

Is something wrong with the Powershell syntax? It works when I run the exe locally with the same parameters.

**Comment by carlpett** [comment]
Hi,
You can test the query with `Get-WmiObject -Query ...` to test your queries. In this case, I think the use of `''` (double single-quotes) looks a bit suspicious?

As a side-note, why are you using NSSM? Is it a workaround for the #169 issue?

**Comment by karl-johan-grahn** [comment]
Yes, NSSM is workaround for #169. I think the issue is the splitting of the command across multiple lines using the backtick character, as each line shows up as a separate command. Maybe I should just put everything on a single line

**Comment by karl-johan-grahn** [comment]
We use NSSM for other services too, so it doesn't have to be that, but noted it here in case it had side effects and was the cause of the error reported here, but I don't think so

**Comment by karl-johan-grahn** [comment]
Powershell usage error, the string has to look like this:
```
[string] $args = """-telemetry.addr"" "":9182"" ""-collectors.enabled"" ""cpu,cs,logical_disk,net,os,process,service,system"" ""-collector.process.processes-where"" " `
                   + """(Name='some.exe') or " `
                   +   "(Name='test.exe') or (Name='test2.exe') or (Name='test3.exe') or (Name LIKE 'Service%')"""
```
