### ISSUE TITLE
cannot load field "NumberOfUsers" into a "uint32": unsupported type (<nil>)

### ISSUE THREAD

**Issue by igor103** [martinlindhe/wmi_exporter#176]
Hello,

we've installed wmi_exporter-0.2.10-amd64 with default collectors on Windows Server 2016 Standard.
It starts successfully and exports most parameters however it doesn't export os data (memory, processes, users).

We see the following error in Event Viewer (actually twice per minute):

`ERROR: os collector failed after 0.392678s: wmi: cannot load field "NumberOfUsers" into a "uint32": unsupported type (<nil>)`

The same wmi_exporter-0.2.10-amd64 works completely fine on couple other our 2016 servers and I wonder what's wrong here.

Our own investigations didn't succeed, please help.

**Comment by carlpett** [comment]
Hi @igor103,
Sorry for dropping this one! I haven't encountered this before, but looks like the data being returned by WMI is not as we expect it. If you are still seeing this issue, could you try running this on the machine and attach the output?

`Get-WmiObject Win32_OperatingSystem | Get-Member -Name NumberOfUsers`

**Comment by ilyababin** [comment]
Same error on 0.3.2. OS: Windows Server 2016 64bit

TypeName: System.Management.ManagementObject#root\cimv2\Win32_OperatingSystem

Name          MemberType Definition
----          ---------- ----------
NumberOfUsers Property   uint32 NumberOfUsers {get;set;}

**Comment by carlpett** [comment]
This was fixed in #209
