### ISSUE TITLE
Monitor CPU uasge

### ISSUE THREAD

**Issue by supertwister** [martinlindhe/wmi_exporter#179]
Hello,
Recently i have installed wmi_exporter in my Windows servers. Which metric do i need to use in order to monitor CPU usage? 

I can see the following matrices in my Prometheus, And it seems that none of them is related to what i'm looking for:
wmi_cpu_cstate_seconds_total
wmi_cpu_dpcs_total
wmi_cpu_interrupts_total
wmi_cpu_time_total

Please advise.

**Comment by VR6Pete** [comment]
I am using sum by (mode) (rate(wmi_cpu_time_total{instance=~"$server"}[5m])) in Grafana

Here is my rule for CPU utilisation.

 - alert: High CPU Utilisation
    expr: 100 - (avg by (instance) (irate(wmi_cpu_time_total{mode="idle"}[5m])) * 100) > 90
    for: 20m
    labels:
      severity: warning
    annotations:
      summary: "Instance {{ $labels.instance }} CPU Utilisation High - ({{ $value }})"
      description: "{{ $labels.instance }} has been running above 90% for 20 minutes"

**Comment by carlpett** [comment]
@VR6Pete thanks!
