### ISSUE TITLE
Uninstalling?

### ISSUE THREAD

**Issue by bryanmorris** [martinlindhe/wmi_exporter#180]
Hi,

I really need to uninstall it in order to make installation with more collector flags, but it tells me I don't have the permission, when trying to install a new version it says "The specified account already exists". I'm an Administrator on Windows Server.

This is pretty crucial instruction to provide, imo.

Thanks

**Comment by bryanmorris** [comment]
Actually managed to delete via another entrance to Control Panel. That's weird.

**Comment by carlpett** [comment]
Hm, that's odd. I've seen something similar when the Install/Uninstall window was opened before an update/installation of the msi. Good that it worked out!
