### ISSUE TITLE
Release Request (to include Pull Request #174)

### ISSUE THREAD

**Issue by mbibinski-ttd** [martinlindhe/wmi_exporter#182]
Could a new release be made to include Pull Request #174 (already merged). I am working on a project that would greatly benefit from adding file collector to WMI_Exporter.

Thanks,
Mike

**Comment by carlpett** [comment]
@mbibinski-ttd I hope to finish the final changes today, and then we'll release 0.3.0!
If you are already using wmi_exporter, do note that this version will have a breaking change in flag-syntax (from one dash to two), so prepare to adjust your installation procedures accordingly.

**Comment by carlpett** [comment]
@mbibinski-ttd The release has been made, and artifacts should be published in a few minutes!
