### ISSUE TITLE
WMI exporter becomes unresponsibe when host at 100% CPU

### ISSUE THREAD

**Issue by VR6Pete** [martinlindhe/wmi_exporter#190]
Hi, 

I have noticed a few times that hosts under high CPU loads (maxed out at 100% that the exporter becomes unresponsive.

- Service is running
- unable to access http://localhost:9182 becomes unresponsive and then I get a gap in Prometheus scrapes. 
- Host down alert triggers in Prometheus.

I am running the 0.2.10 exporter version here, once I resolved the cause of the 100% CPU spike wmi exporter became responsive once more.

Thanks.

Pete

**Comment by carlpett** [comment]
This is probably to be expected - if the exporter doesn't get any CPU time, then it will be unable to serve your request.
Not only does our code need to get CPU time, the WMI subsystem also needs to get (quite a lot of) CPU time.

So, I'm not sure there much that we can/should do - can you agree?

**Comment by VR6Pete** [comment]
Yes you probably are right here. 

It was just an observation more than anything else but would rather flag it and discuss in the event this was not normal behaviour.
