### ISSUE TITLE
Pushgateway support

### ISSUE THREAD

**Issue by khurram-aziz** [martinlindhe/wmi_exporter#191]
I guess adding Prometheus Pushgateway support will be useful in scenarios where we want to monitor Windows workstations behind NAT; enterprise workstations scenario.

**Comment by brian-brazil** [comment]
This is not an appropriate use of the pushgateway, see https://prometheus.io/docs/practices/pushing/

**Comment by carlpett** [comment]
As noted by Brian, I do not think we should support this scenario.
