### ISSUE TITLE
textfile collector fails to read file

### ISSUE THREAD

**Issue by wizardmatas** [martinlindhe/wmi_exporter#199]
Hi, WMI exporter fails to export metrics from text file.  Error in event log:

```
Error parsing "C:\\Program Files\\wmi_exporter\\textfile_inputs\\test.prom": text format parsing error in line 1: expected float as value, got "8192\r"
```

file content:
```
node_directory_size_bytes{directory="."} 8192
```
I have tested the same file with the same content on node exporter on linux and it worked. Anyone tried to export metrics from file  ?

**Comment by carlpett** [comment]
Hi!
I think the key is `"8192\r"` - there's a trailing carriage return there. We probably should strip those, but if you want a quick fix, could you try to use unix line endings?

**Comment by brian-brazil** [comment]
Carriage returns are not valid line endings for the text format.

**Comment by wizardmatas** [comment]
Hi, yes file with unix line endings works, thanks !
Do we need fix for that or should we close this as not an issue?

**Comment by martinlindhe** [comment]
`\r\n` is standard line endings on Windows though, so I think we need to add support for this.
