### ISSUE TITLE
Window2012 with 3 disk each size 2T, only monitor 2 disk

### ISSUE THREAD

**Issue by wangyf123** [martinlindhe/wmi_exporter#201]
login into vm, can see C,D,E,F
D,E,F each size is 2T,
while the total disk size on wmi_exporter shows 4T.
![image](https://user-images.githubusercontent.com/6194754/40114835-e842e534-5940-11e8-990c-bf0bd01cada6.png)
![image](https://user-images.githubusercontent.com/6194754/40114859-0170e8bc-5941-11e8-8d5f-5fd67b4514f8.png)
![image](https://user-images.githubusercontent.com/6194754/40114867-0cd17e10-5941-11e8-998a-72795403e772.png)

**Comment by martinlindhe** [comment]
The screenshot shows free bytes, not total bytes

**Comment by martinlindhe** [comment]
Also, It appears like your F: is not mounted, it shows up as HarddiskVolume5 in the metrics.

**Comment by wangyf123** [comment]
![image](https://user-images.githubusercontent.com/6194754/40152486-03423746-59b8-11e8-95e7-c4d7c5fcaf52.png)
![image](https://user-images.githubusercontent.com/6194754/40154697-3e049b80-59c2-11e8-870e-c2cdf2c64b77.png)
![image](https://user-images.githubusercontent.com/6194754/40154718-540f3d04-59c2-11e8-941f-f9807b3ec94a.png)
F: is already in use.

**Comment by wangyf123** [comment]
Reinstall the WMI Exporter, D: and E: appared quickly, and F: appared later. 
It's so wired.

**Comment by wangyf123** [comment]
Where is the location of wmi exporter's running log?

**Comment by martinlindhe** [comment]
You can find logging events in the Event Viewer.

**Comment by wangyf123** [comment]
@martinlindhe Thank you very much.

**Comment by carlpett** [comment]
I'm interpreting this as this issue being resolved? Re-open if this is not the case!
