### ISSUE TITLE
TEXTFILE_DIR Parameter is not working

### ISSUE THREAD

**Issue by geronio12** [martinlindhe/wmi_exporter#203]
Hello 
I start the exporter into my Windows Server 2016 Standard like this: 
msiexec /i wmi_exporter-0.3.2-amd64.msi ENABLED_COLLECTORS=cpu,cs,logical_disk,net,os,process,service,system,textfile

So in the "C:\Program Files\wmi_exporter\textfile_inputs" directory I have a file called  "sbe_metrics.prom"
which contains:
```YAML
 # HELP sbe_server_state The state of the SBE server (State)
 # TYPE sbe_server_state gauge
 sbe_server_state{state="INITIALIZING"} 0
 sbe_server_state{state="HEALTHY"} 1
 sbe_server_state{state="RETIRED"} 0
 sbe_server_state{state="SHUTTING_DOWN"} 0
```
but when I check the endpoint "localhost:9182/metrics", I don't find the metrics of my file that I want to show.
Additionally the metric "wmi_textfile_scrape_error" has value 1
```YAML
# HELP wmi_textfile_scrape_error 1 if there was an error opening or reading a file, 0 otherwise
# TYPE wmi_textfile_scrape_error gauge
wmi_textfile_scrape_error 1
```   
I tried too, start the exporter with out parameters 
msiexec /i wmi_exporter-0.3.2-amd64.msi
Also I tried  with a diferent path
msiexec /i wmi_exporter-0.3.2-amd64.msi TEXTFILE_DIR=C:\metrics
But I get the same unsuccesfull result.
Do you know what is missing, in order to scrape metrics from my file?

**Comment by carlpett** [comment]
@geronio12 Sorry to hear that! Do you get any log output? There should be something there if it fails to parse the file, for example.

**Comment by geronio12** [comment]
@carlpett Thanks for your answer
I downloaded and ran the wmi_exporter.exe file :
```EXE
wmi_exporter.exe --collector.textfile.directory=C:\metrics
```
and I got the log:

```EXE
←[31mERRO←[0m[0040] Error parsing "C:\\metrics\\New Text Document.prom": text fo
rmat parsing error in line 2: unknown metric type "gauge \r"  ←[31msource←[0m="t
extfile.go:216"
```

**Comment by carlpett** [comment]
Yes, CRs are unsupported at this time, but will work in the next release (see #199)
