### ISSUE TITLE
wmi_exporter_collector_success{collector="ad"} 0

### ISSUE THREAD

**Issue by mkaszta** [martinlindhe/wmi_exporter#207]
Hi Team.

I'm experiencing an issue with collecting AD metrics.
Actually, I can't even start the AD collector:

`# HELP wmi_exporter_collector_success wmi_exporter: Whether the collector was successful.`
`# TYPE wmi_exporter_collector_success gauge`
`wmi_exporter_collector_success{collector="ad"} 0`
`wmi_exporter_collector_success{collector="cpu"} 1`
`wmi_exporter_collector_success{collector="cs"} 1`
`wmi_exporter_collector_success{collector="dns"} 1`
`wmi_exporter_collector_success{collector="net"} 1`
`wmi_exporter_collector_success{collector="os"} 1`

I've found out that the WMI is working correctly - confirmed with PowerShell command 
`Get-WmiObject Win32_PerfRawData_DirectoryServices_DirectoryServices `

Could you please help investigate this issue?
I'm pasting the PowerShell result in case you need it:

__GENUS                                                          : 2
__CLASS                                                          : Win32_PerfRawData_DirectoryServices_DirectoryService
                                                                   s
__SUPERCLASS                                                     : Win32_PerfRawData
__DYNASTY                                                        : CIM_StatisticalInformation
__RELPATH                                                        : Win32_PerfRawData_DirectoryServices_DirectoryService
                                                                   s.Name="NTDS"
__PROPERTY_COUNT                                                 : 174
__DERIVATION                                                     : {Win32_PerfRawData, Win32_Perf, CIM_StatisticalInfor
                                                                   mation}
__SERVER                                                         : DCANN1
__NAMESPACE                                                      : root\cimv2
__PATH                                                           : \\DCANN1\root\cimv2:Win32_PerfRawData_DirectoryServi
                                                                   ces_DirectoryServices.Name="NTDS"
ABANRPersec                                                      : 0
ABBrowsesPersec                                                  : 0
ABClientSessions                                                 : 0
ABMatchesPersec                                                  : 0
ABPropertyReadsPersec                                            : 0
ABProxyLookupsPersec                                             : 0
ABSearchesPersec                                                 : 0
ApproximatehighestDNT                                            : 920534
ATQEstimatedQueueDelay                                           : 0
ATQOutstandingQueuedRequests                                     : 0
ATQRequestLatency                                                : 0
ATQThreadsLDAP                                                   : 0
ATQThreadsOther                                                  : 0
ATQThreadsTotal                                                  : 22
BasesearchesPersec                                               : 112023795
Caption                                                          : 
DatabaseaddsPersec                                               : 14096
DatabasedeletesPersec                                            : 22738
DatabasemodifysPersec                                            : 34404765
DatabaserecyclesPersec                                           : 6804
Description                                                      : 
DigestBindsPersec                                                : 0
DRAHighestUSNCommittedHighpart                                   : 0
DRAHighestUSNCommittedLowpart                                    : 982052102
DRAHighestUSNIssuedHighpart                                      : 0
DRAHighestUSNIssuedLowpart                                       : 982052102
DRAInboundBytesCompressedBetweenSitesAfterCompressionPersec      : 0
DRAInboundBytesCompressedBetweenSitesAfterCompressionSinceBoot   : 0
DRAInboundBytesCompressedBetweenSitesBeforeCompressionPersec     : 0
DRAInboundBytesCompressedBetweenSitesBeforeCompressionSinceBoot  : 0
DRAInboundBytesNotCompressedWithinSitePersec                     : 114185664
DRAInboundBytesNotCompressedWithinSiteSinceBoot                  : 114185664
DRAInboundBytesTotalPersec                                       : 114185664
DRAInboundBytesTotalSinceBoot                                    : 114185664
DRAInboundFullSyncObjectsRemaining                               : 0
DRAInboundLinkValueUpdatesRemaininginPacket                      : 0
DRAInboundObjectsAppliedPersec                                   : 7183061
DRAInboundObjectsFilteredPersec                                  : 58630
DRAInboundObjectsPersec                                          : 1904429
DRAInboundObjectUpdatesRemaininginPacket                         : 0
DRAInboundPropertiesAppliedPersec                                : 2781465
DRAInboundPropertiesFilteredPersec                               : 2008825
DRAInboundPropertiesTotalPersec                                  : 4788033
DRAInboundTotalUpdatesRemaininginPacket                          : 0
DRAInboundValuesDNsonlyPersec                                    : 134539
DRAInboundValuesTotalPersec                                      : 4932649
DRAOutboundBytesCompressedBetweenSitesAfterCompressionPersec     : 0
DRAOutboundBytesCompressedBetweenSitesAfterCompressionSinceBoot  : 0
DRAOutboundBytesCompressedBetweenSitesBeforeCompressionPersec    : 0
DRAOutboundBytesCompressedBetweenSitesBeforeCompressionSinceBoot : 0
DRAOutboundBytesNotCompressedWithinSitePersec                    : 294601496
DRAOutboundBytesNotCompressedWithinSiteSinceBoot                 : 294601496
DRAOutboundBytesTotalPersec                                      : 294601496
DRAOutboundBytesTotalSinceBoot                                   : 294601496
DRAOutboundObjectsFilteredPersec                                 : 3073525
DRAOutboundObjectsPersec                                         : 153557526
DRAOutboundPropertiesPersec                                      : 1223944092
DRAOutboundValuesDNsonlyPersec                                   : 226015829
DRAOutboundValuesTotalPersec                                     : 2439561799
DRAPendingReplicationOperations                                  : 0
DRAPendingReplicationSynchronizations                            : 0
DRASyncFailuresonSchemaMismatch                                  : 0
DRASyncRequestsMade                                              : 1616357
DRASyncRequestsSuccessful                                        : 1616357
DRAThreadsGettingNCChanges                                       : 0
DRAThreadsGettingNCChangesHoldingSemaphore                       : 0
DSClientBindsPersec                                              : 8201562
DSClientNameTranslationsPersec                                   : 9926027
DSDirectoryReadsPersec                                           : 436536517
DSDirectorySearchesPersec                                        : 282850503
DSDirectoryWritesPersec                                          : 34448405
DSMonitorListSize                                                : 22
DSNameCachehitrate                                               : 463213790
DSNameCachehitrate_Base                                          : 2095764523
DSNotifyQueueSize                                                : 0
DSPercentReadsfromDRA                                            : 15
DSPercentReadsfromDRA_Base                                       : 436536517
DSPercentReadsfromKCC                                            : 306061
DSPercentReadsfromKCC_Base                                       : 436536517
DSPercentReadsfromLSA                                            : 32444154
DSPercentReadsfromLSA_Base                                       : 436536517
DSPercentReadsfromNSPI                                           : 0
DSPercentReadsfromNSPI_Base                                      : 436536517
DSPercentReadsfromNTDSAPI                                        : 0
DSPercentReadsfromNTDSAPI_Base                                   : 436536517
DSPercentReadsfromSAM                                            : 400088983
DSPercentReadsfromSAM_Base                                       : 436536517
DSPercentReadsOther                                              : 3697329
DSPercentReadsOther_Base                                         : 436536517
DSPercentSearchesfromDRA                                         : 0
DSPercentSearchesfromDRA_Base                                    : 282850503
DSPercentSearchesfromKCC                                         : 64925
DSPercentSearchesfromKCC_Base                                    : 282850503
DSPercentSearchesfromLDAP                                        : 190921334
DSPercentSearchesfromLDAP_Base                                   : 282850503
DSPercentSearchesfromLSA                                         : 773747
DSPercentSearchesfromLSA_Base                                    : 282850503
DSPercentSearchesfromNSPI                                        : 0
DSPercentSearchesfromNSPI_Base                                   : 282850503
DSPercentSearchesfromNTDSAPI                                     : 9310091
DSPercentSearchesfromNTDSAPI_Base                                : 282850503
DSPercentSearchesfromSAM                                         : 48707268
DSPercentSearchesfromSAM_Base                                    : 282850503
DSPercentSearchesOther                                           : 33072995
DSPercentSearchesOther_Base                                      : 282850503
DSPercentWritesfromDRA                                           : 1900404
DSPercentWritesfromDRA_Base                                      : 34448405
DSPercentWritesfromKCC                                           : 0
DSPercentWritesfromKCC_Base                                      : 34448405
DSPercentWritesfromLDAP                                          : 3256675
DSPercentWritesfromLDAP_Base                                     : 34448405
DSPercentWritesfromLSA                                           : 177
DSPercentWritesfromLSA_Base                                      : 34448405
DSPercentWritesfromNSPI                                          : 0
DSPercentWritesfromNSPI_Base                                     : 34448405
DSPercentWritesfromNTDSAPI                                       : 246748
DSPercentWritesfromNTDSAPI_Base                                  : 34448405
DSPercentWritesfromSAM                                           : 29041241
DSPercentWritesfromSAM_Base                                      : 34448405
DSPercentWritesOther                                             : 3161
DSPercentWritesOther_Base                                        : 34448405
DSSearchsuboperationsPersec                                      : 4222795668
DSSecurityDescriptorPropagationsEvents                           : 0
DSSecurityDescriptorPropagatorAverageExclusionTime               : 0
DSSecurityDescriptorPropagatorRuntimeQueue                       : 0
DSSecurityDescriptorsuboperationsPersec                          : 55330
DSServerBindsPersec                                              : 1617688
DSServerNameTranslationsPersec                                   : 139663397
DSThreadsinUse                                                   : 0
ExternalBindsPersec                                              : 0
FastBindsPersec                                                  : 6
Frequency_Object                                                 : 0
Frequency_PerfTime                                               : 2441408
Frequency_Sys100NS                                               : 10000000
LDAPActiveThreads                                                : 0
LDAPBindTime                                                     : 0
LDAPClientSessions                                               : 155
LDAPClosedConnectionsPersec                                      : 52135945
LDAPNewConnectionsPersec                                         : 52136100
LDAPNewSSLConnectionsPersec                                      : 490243
LDAPSearchesPersec                                               : 266969963
LDAPSuccessfulBindsPersec                                        : 43743893
LDAPUDPoperationsPersec                                          : 13910436
LDAPWritesPersec                                                 : 2111914
LinkValuesCleanedPersec                                          : 194
Name                                                             : NTDS
NegotiatedBindsPersec                                            : 39181135
NTLMBindsPersec                                                  : 2
OnelevelsearchesPersec                                           : 18932939
PhantomsCleanedPersec                                            : 0
PhantomsVisitedPersec                                            : 0
SAMAccountGroupEvaluationLatency                                 : 0
SAMDisplayInformationQueriesPersec                               : 0
SAMDomainLocalGroupMembershipEvaluationsPersec                   : 1049774773
SAMEnumerationsPersec                                            : 96
SAMGCEvaluationsPersec                                           : 0
SAMGlobalGroupMembershipEvaluationsPersec                        : 174151936
SAMMachineCreationAttemptsPersec                                 : 246
SAMMembershipChangesPersec                                       : 1814713
SAMNonTransitiveMembershipEvaluationsPersec                      : 53754337
SAMPasswordChangesPersec                                         : 15818
SAMResourceGroupEvaluationLatency                                : 1
SAMSuccessfulComputerCreationsPersecIncludesallrequests          : 246
SAMSuccessfulUserCreationsPersec                                 : 1361
SAMTransitiveMembershipEvaluationsPersec                         : 3012025890
SAMUniversalGroupMembershipEvaluationsPersec                     : 1788099181
SAMUserCreationAttemptsPersec                                    : 36568
SimpleBindsPersec                                                : 5055370
SubtreesearchesPersec                                            : 151893611
Timestamp_Object                                                 : 0
Timestamp_PerfTime                                               : 20380506517759
Timestamp_Sys100NS                                               : 131719886730530000
TombstonesGarbageCollectedPersec                                 : 13161
TombstonesVisitedPersec                                          : 17177
PSComputerName                                                   : xxxxxx

**Comment by carlpett** [comment]
Hi,
This is probably similar to #152. I'm looking into how to make our queries a bit more forgiving to the apparently rather diverse results that WMI gives us.

**Comment by mkaszta** [comment]
Indeed it looks to be similiar but the exe you have pasted there does not work for me.
Is there any way to make it work while you are trying to fix it?

**Comment by carlpett** [comment]
What is needed is to find which fields are missing in your local installation vs what we expect. It looks like the culprits are:
```
Transitiveoperationsmillisecondsrun
TransitiveoperationsPersec
TransitivesuboperationsPersec
```
Are you able to compile Go locally? What you need to do is remove those fields (so we don't try to read them when they aren't there) from the `Win32_PerfRawData_DirectoryServices_DirectoryServices` struct in collector/ad.go.

**Comment by mkaszta** [comment]
I'm not familiar with go, unfortunately.
Would be great if you could help me with this.

**Comment by mkaszta** [comment]
I'd be more than grateful if you could help me with compiling these files for me :)
Thanks in advance!

**Comment by carlpett** [comment]
@mkaszta Please understand that this is something we maintain on our spare time, and therefore, it may take some time to find the evening or weekend where this can be done.

That said, I have now had time to make an attempt to fix the queries so they will handle this type of problems: see #209. The PR is still open, but you can test it already by downloading the build here: https://ci.appveyor.com/api/buildjobs/ormdq6li0bcfviph/artifacts/wmi_exporter-amd64.zip

**Comment by mkaszta** [comment]
Absolutely, I didn't mean to hurry you.
Thank you so much for the files, I'll let you know if it works!
Michał

**Comment by mkaszta** [comment]
Works like a charm, thank you! :)
