### ISSUE TITLE
Windows Monitoring

### ISSUE THREAD

**Issue by maneavinash** [martinlindhe/wmi_exporter#210]
Hi,
We have monitored 2 linux systems through prometheus but we are unable to get windows system monitored. We have wmi_exporter installed on the target machines and but still not getting cpu usage, memory etc as we were monitoring for linux machines. 
Are there any specific metrics being used for windows monitoring ? And also we have noticed there are two collector OS and IIS, could you also explain what exactly they are for?

**Comment by carlpett** [comment]
Hi @maneavinash,
The first thing to check is if Prometheus finds and successfully scrapes the exporters? 
If so, please note that the names of the metrics are not identical with those from node_exporter, so if you have dashboards for the Linux machines, you'll need to do some adaptations to get them to also use Windows metrics.

Regarding the collectors, the wmi_exporter can toggle certain groups of metrics on and off (much like the node_exporter). The collectors are named by the part of the WMI data they operate on.
Some of them, like IIS, are not enabled by default, since those metrics are only available on machines where IIS is installed.

Does this answer your questions?

**Comment by maneavinash** [comment]
Thanks Carlpett, Do I need to install the IIS collector explicitly and from where I could get the installables.

**Comment by avonwyss** [comment]
@maneavinash The IIS collector is part of the normal install but disabled because only works if IIS is installed on the machine. See https://github.com/martinlindhe/wmi_exporter#installation

On the already installed wmi_exporter you can edit the `ImagePath` value in the registry key `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\wmi_exporter` (with the usual precautions when editing the registry) to modify the arguments passed to the service.

**Comment by maneavinash** [comment]
Thanks again Carlpett, We have checked and could see OS and IIS both are already enabled.We could see results for metrics only starting with WMI. We want to monitor the CPU, Memory Usage, I/O stats and this has been done for the Linux machines with the below queries
1)Memory Utilization
100 * (1 - ((node_memory_MemFree + node_memory_Cached + node_memory_Buffers) / node_memory_MemTotal))
2)CPU Utilization
100 * (1 - avg by(instance)(irate(node_cpu{mode='idle'}[5m])))
3)I/O Stats
irate(node_disk_io_time_ms{job='node',instance='{{ .Params.instance }}',device!~'^(md\\\\d+$\|dm-)'}[5m]) / 1000 * 100

Could you please suggest/help the way forward to get these queries formed to monitor Windows System.

**Comment by frenkye** [comment]
@maneavinash you need to use correct variables. The prefix "node_" is from node_exporter, but for windows you have "wmi_" prefix (by this I don't mean just switch the prefix). Look into /metrics and adjust your variables.

**Comment by VR6Pete** [comment]
I wrote a powershell script to dynamically check what windows features are installed and enable the appropriate collectors, will share below..

`cls
$serviceName = "wmi_exporter"
$MSMQCollector = "msmq"
$IISCollector = "iis"
$ImagePathlocation = "HKLM:\SYSTEM\ControlSet001\Services\wmi_exporter\"
$RegString = "ImagePath"
$ImagePathstr1 = '"C:\Program Files\wmi_exporter\wmi_exporter.exe" --log.format logger:eventlog?name=wmi_exporter --telemetry.addr :9182 --collectors.enabled'
$global:CoreCollectorsEnabled = "cpu,cs,logical_disk,net,os,process,service,system" -split ","
$CollectorServiceQuery = @"
--collector.service.services-where "Name='wmi_exporter' or Name='OpenVPNService' or Name='OpenVPNServiceInteractive' or Name='amazon-ssm-agent' or Name='splunkforwarder' or Name='MSMQ' or Name='smtpsvc' or Name='sqlbrowser' or Name='chef-client' or Name='chef-client' or Name='Prizm' or Name LIKE 'sqlagent%' or Name LIKE 'mssql%' or Name LIKE 'sqlbackupagent%' or Name LIKE 'evault infostage%' or Name LIKE 'e360Service%' or Name LIKE 'eAppraisal%' or Name LIKE '%gatewayfileimporter%' or Name LIKE 'healthroster%' or Name LIKE 'bankstaffmessageservice%' or Name LIKE 'bankstaffassistant%' or Name LIKE 'rosterperform_%' or Name LIKE 'rosterperform data gatherer service%' or Name LIKE 'benchmarkinghub%' or Name LIKE 'allocatenhspstuckqueuenotifierservice%' or Name LIKE 'bankstaffassistant%'"
"@
$collectorprocessqry = @"
--collector.process.processes-where "Name='w3wp' or Name='wmi_exporter' or Name='sqlservr' or Name='MSW.MAPS.HealthRoster.BackgroundTasksService' or Name='MSW.MAPS.HealthRoster.BackgroundTasksService' or Name='amazon-ssm-agent' or Name='KeyMessenger' or Name='Magnum.AssistantService.Host' or Name='mqsvc' or Name='openvpnserv2' or Name='openvpnserv' or Name='splunkd'"
"@


Function IsIISInstalled {

return (Get-WindowsFeature -Name Web-Server).Installed

}

Function IsMSMQInstalled {

return (Get-WindowsFeature -Name MSMQ-Server).Installed

}

function BuildArgsRegValue() {
    if (IsIISInstalled) {$CoreCollectorsEnabled = $CoreCollectorsEnabled + $IISCollector}
	if (IsMSMQInstalled) {$CoreCollectorsEnabled = $CoreCollectorsEnabled + $MSMQCollector}
return $CoreCollectorsEnabled -join ","


}
$allcollectors = BuildArgsRegValue
Function RegKeyCreate ($allcollectors){

$ImagePathValue = "$ImagePathstr1 $allcollectors $CollectorServiceQuery $collectorprocessqry"
write-host "$ImagePathValue"

$value1 = (Test-Path $ImagePathlocation)
If ($value1 -eq $true) 
{

Set-ItemProperty -Path $ImagePathlocation -Name "$Regstring" "$ImagePathValue" -Force

}

else {
Write-Host "WMI Exporter Registry key does not exist"
}

 }

Function RestartService() {

If (Get-Service $serviceName -ErrorAction SilentlyContinue) {

    If ((Get-Service $serviceName).Status -eq 'Running') {

        Restart-Service $serviceName
        Write-Host "Restarting $serviceName"

    } Else {

        Write-Host "$serviceName found, but it is not running, lets attempt to restart it"
        Start-Service $serviceName
    }

} Else {

    Write-Host "$serviceName service installed"

}


}

BuildArgsRegValue
RegKeyCreate $allcollectors
RestartService`

**Comment by avonwyss** [comment]
@VR6Pete Thanks for sharing the script. Note that you should never use `ControlSet001` - use `CurrentControlSet` instead which is the effectively used one by WIndows and may be different.

**Comment by carlpett** [comment]
I think the question here has been answered, so let's close this. Let me know if there is still something unresolved.
