### ISSUE TITLE
Cluster Shared Volume metrics missing?

### ISSUE THREAD

**Issue by jrcresawn** [martinlindhe/wmi_exporter#220]
I have two Windows Server 2012 R2 nodes in a Failover Cluster. I would like to use wmi_exporter to retrieve storage metrics from Cluster Shared Volumes, but I have not found them. The PowerShell command Get-ClusterSharedVolume returns a list of the volumes. Does wmi_exporter provide this information? I would like access to these metrics to trigger alerts when available storage is low.

**Comment by carlpett** [comment]
Currently, we only expose local logical volumes, so this would require some new code.
We have a generator that can generate a skeleton implementation if you would like to take a shot at implementing it? Do you know what WMI classes provide the information you need?

**Comment by jrcresawn** [comment]
I have been unable to identify a WMI class which provides the information, but the PowerShell command ``Get-ClusterStorageVolume`` can retrieve storage metrics. Can ``wmi_exporter`` execute PowerShell commands?

[https://blogs.msdn.microsoft.com/clustering/2010/06/18/powershell-for-failover-clustering-csv-free-disk-space-and-other-info/](https://blogs.msdn.microsoft.com/clustering/2010/06/18/powershell-for-failover-clustering-csv-free-disk-space-and-other-info/)

**Comment by jrcresawn** [comment]
Thanks for steering me in the direction of the textfile collector. I wrote a PowerShell script which executes every 5 minutes by Task Scheduler and collects the metrics I need. Is there a place to contribute such a script to wmi_exporter? Either way, I will close this issue at this time.

**Comment by VR6Pete** [comment]
I’ve written a couple of powershell scripts for text exporters. It would be good if these can be submitted for others to share and take inspiration from.

**Comment by carlpett** [comment]
Yes, we should have such a place. As a suggestion without much deep thoughts behind it, we could have a contrib/textfile/ directory with subdirectories for each script. Hopefully with a short readme and sample output. Sounds good? Would it be discoverable enough?
We've been discussing having alerts and dashboard definitions too, so they'd go well under the top contrib/ directory.

**Comment by jrcresawn** [comment]
Would it be wise to follow the lead of node_exporter?
[https://github.com/prometheus/node_exporter/tree/master/text_collector_examples](https://github.com/prometheus/node_exporter/tree/master/text_collector_examples)

**Comment by carlpett** [comment]
I considered that approach as well, but I think there are two benefits with my suggestion:
1. Having a directory per script keeps the README and other auxiliary files together with the script rather than having a single large directory which relies on naming conventions like `cluster-volume_*`.
2. Allows us to add the alerts/dashboards in the same structure.

Am I missing some benefit with their layout?

**Comment by VR6Pete** [comment]
I think a contrib would be the better option here, and a good starting point. 

I am sure once awareness improves then more people will contribute :)

**Comment by jrcresawn** [comment]
I also prefer a contrib directory with one sub-directory per contribution.

**Comment by SMARoovers** [comment]
Was this shared somewhere? Any chance you can share the Powershell script via a Gist @jrcresawn ?

**Comment by jrcresawn** [comment]
Here you go Bas:

https://gist.github.com/jrcresawn/f067004853ea73d0b04f34423fcbb042

**Comment by SMARoovers** [comment]
@jrcresawn Awesome, thank you very much for sharing.

**Comment by jrcresawn** [comment]
You're welcome. I have noticed that Grafana displays no data periodically
with this script. I'm not sure why that is, but any improvements you could
make to it would be appreciated!

**Comment by SMARoovers** [comment]
You could try my own version, which I wrote a few days ago.

https://gist.github.com/SMARoovers/91c99d919cb0769b3d257692ed4ef99e

I'm running it via Task Scheduler but I rather have it started from wmi_exporter itself, the way Telegraf does it.

**Comment by jurkovic-nikola** [comment]
Hello,

Old thread but i went thru same thing. No CSV data...

Here is my simple pulling of FreeSpace / TotalSize from CSV disks. 

Feel free to modify it, change it how it fits your needs. If author wants, he can include it in baseline of repo. 

https://gist.github.com/jurkovic-nikola/0eb6a0191cd3c3febcc5bcb7528f3941
