### ISSUE TITLE
Container Metrics

### ISSUE THREAD

**Issue by sam-cogan** [martinlindhe/wmi_exporter#221]
I've installed WMI_Exporter and it's working great for node metrics.
What I am struggling with now is how I can get container based metrics, such as how much CPU and Memory an individual container is using. Should I be able to get this from the data wmi_exporter gets, or (as I suspect is the case) is this not a level of detail it gets the data for? If the later, are there any options for getting container level data from Windows containers?

**Comment by martinlindhe** [comment]
We currently have two modules for containers, vmware and hyperv. They are not enabled by default but need to be manually enabled (see the README).

Does this answer your question?

**Comment by carlpett** [comment]
Closed by #320
