### ISSUE TITLE
IIS - HTTP 500's

### ISSUE THREAD

**Issue by VR6Pete** [martinlindhe/wmi_exporter#223]
I think I must be going blind here, but I cannot for the life of me find what metric exposes http 403,500,401,404 in WMI Exporter metrics.

I am almost certain I used to see these with older versions of the exporter.

Cheers

Pete

**Comment by carlpett** [comment]
You mean the name of the metric? `wmi_iis_worker_request_errors_total` is the one in that case

**Comment by VR6Pete** [comment]
well that is strange, I do not see that metric name at all in http://localhost:9182/metrics on my server that I have this collecting IIS metrics from.

**Comment by VR6Pete** [comment]
ah thanks - That would explain it ! 

I have a mixture from 2008 R2 / 2012 / 2016 but have confirmed behaviour as you describe. 

hrmmmph ok no worries. I'll have a think how else I can track this.

**Comment by carlpett** [comment]
As far as I know, IIS doesn't expose it for older versions, so you might want to look into updating if possible... Otherwise you'll need to look into log parsing probably.
