### ISSUE TITLE
iis module not working on windows server 2016

### ISSUE THREAD

**Issue by cw-pratik** [martinlindhe/wmi_exporter#232]
I tried installing wmi_exporter and added the iis module to the list while installing the exporter as mentioned in the documentation.

Version used: 0.3.4

Prometheus is giving an error 

>  expected text in HELP, got "INVALID"

**Comment by carlpett** [comment]
Hi @cw-pratik,
Sorry about that. Could you try accessing the exporter directly in the browser and see what it outputs? It sounds like there's some error reported, rather than metrics.

**Comment by cw-pratik** [comment]
@carlpett I tried to look at the output. But could not find any error as such.
Have attached the output too.

[iis-output.txt](https://github.com/martinlindhe/wmi_exporter/files/2231222/iis-output.txt)

**Comment by carlpett** [comment]
Ok, the output looks fine, so probably not something directly tied to the exporter. Are you using some load balancer or proxy solution between your Prometheus instance and exporters?

**Comment by cw-pratik** [comment]
No there is no proxy or load balancer. I tried doing "curl" on the endpoint and am able to get the output.

**Comment by cw-pratik** [comment]
I was using the master branch of prometheus. Moved to the stable release branch and it started working.
Sorry for the trouble.
