### ISSUE TITLE
cannot start WMI exporter: listen tcp :9182: bind

### ISSUE THREAD

**Issue by VR6Pete** [martinlindhe/wmi_exporter#243]
Morning,

Have upgraded to 0.4.2 and a number of instances are now showing as offline (around 50....)

I have tried removing and installing and the following error is showing;

The description for Event ID 102 from source wmi_exporter cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

cannot start WMI exporter: listen tcp :9182: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

any ideas on what this could be? These are production servers so don't really wanting to reboot if there is a way to work around this :) Cheers.

Pete

**Comment by VR6Pete** [comment]
netstat -an doesn't show anything binded to port 9182 either oddly.

**Comment by carlpett** [comment]
Hm, odd. If `netstat` says nothing is listening this shouldn't happen... Does it still happen after the service having been shut off for a while? Just in case there was some race on startup with the old version not shutting down fast enough.

**Comment by VR6Pete** [comment]
Yeah it still doesn’t work. 

If I change the port number to something else the service starts OK but stopping and changing it back fails. 

Have updated the exporter using same mechanism many of times and only started happening with this version.

**Comment by szook** [comment]
On my laptop, I just installed v 0.2.10, verified that the exporter responded (the `wmi_exporter_build_info` metric showed the expected version) , then installed 0.4.2 on top of that and verified it again and it worked as expected.  So it doesn't seem to be anything inherently wrong with the 0.4.2 release. 

I sure sounds like there's some rogue process on your systems that's binding to port 9182.

Have you tried hitting that port (ie, http://localhost:9182) and see if anything interesting responds? 

Have you tried rebooting one of those machines to see if that cleared it up? (I realize that's not always practical on production machines, but if there is a rouge process holding that port open, that should clear that up).

**Comment by VR6Pete** [comment]
I have tried hitting localhost:9182 and no response, I have scheduled a reboot to happen over night on one of the affected servers so will see what happens I guess.

**Comment by szook** [comment]
can you try running `netstat -anoq`  add see if there's anything on 9182?

it sounds like the `-q` will list "bound nonlistening TCP ports" 
the `-o` will show the owning process ID in case you find something.

**Comment by VR6Pete** [comment]
Well a reboot did clear, now to schedule a reboot of ~50 production servers... 

Very strange that nothing was holding onto the port binding.

**Comment by VR6Pete** [comment]
I’ll mark this as closed as a reboot resolved the issue.
