### ISSUE TITLE
wmi_exporter crashed with collectors'system'

### ISSUE THREAD

**Issue by KelvinLin** [martinlindhe/wmi_exporter#246]
Hi 
we have a server happen when collector enabled "system" wmi_exporter will crashed.

here are the manual start error message 

C:\Program Files\wmi_exporter>**.\wmi_exporter.exe --collectors.enabled "system"  --collector.service.services-where "Name='wmi_exporter'"**
Enabled collectors: system                   exporter.go:231"
Starting WMI exporter (version=0.4.2, branch=master, revision=bad1e7f7b0ad2e76eb3467195572c838f2f1ca98) exporter.go:242"
Build context (go=go1.10, user=appvyr-win\appveyor@APPVYR-WIN, date=20180804-06:36:44)  exporter.go:243"
Starting server on :9182                     exporter.go:246"
**panic: runtime error: index out of range**

goroutine 8 [running]:
github.com/martinlindhe/wmi_exporter/collector.(*SystemCollector).collect(0xc0421600c0, 0xc0421660c0, 0x0, 0x0, 0x0)
        c:/gopath/src/github.com/martinlindhe/wmi_exporter/collector/system.go:101 +0x4c7
github.com/martinlindhe/wmi_exporter/collector.(*SystemCollector).Collect(0xc0421600c0, 0xc0421660c0, 0xbe0620, 0x0)
        c:/gopath/src/github.com/martinlindhe/wmi_exporter/collector/system.go:73 +0x43
main.execute(0xc04209a088, 0x6, 0x995b40, 0xc0421600c0, 0xc0421660c0)
        c:/gopath/src/github.com/martinlindhe/wmi_exporter/exporter.go:100 +0x85
main.WmiCollector.Collect.func1(0xc0421660c0, 0xc04201c240, 0xc04209a088, 0x6, 0x995b40, 0xc0421600c0)
        c:/gopath/src/github.com/martinlindhe/wmi_exporter/exporter.go:74 +0x5a
created by main.WmiCollector.Collect
        c:/gopath/src/github.com/martinlindhe/wmi_exporter/exporter.go:73 +0x110

`

**Comment by carlpett** [comment]
Hi @KelvinLin,
Sorry about that. It was actually fixed in #241, but we hadn't made a release with that fix. I released 0.4.3 now, binaries should be available in a few minutes.

**Comment by KelvinLin** [comment]
thank you very much !
