### ISSUE TITLE
/ should serve some welcome page instead of redirecting

### ISSUE THREAD

**Issue by carlpett** [martinlindhe/wmi_exporter#25]
Currently we do a redirect from `/` to `/metrics`. Drawback to this is that there is no request that can be done to check that everything is alright (http server is working, at least) without also incurring the cost of running the wmi queries. 

Our use case is that we have `/` as a http healthcheck endpoint for exporters which we register in Consul. If we want to keep the redirect, we should have _some_ endpoint which indicates that things are ok, at least.

**Comment by martinlindhe** [comment]
I've personally no real opinion on this one. The redirect / -> metrics came while copying boilerplate code (from node_exporter, or one of the other exporters. Don't remember).

If a simple health check page is useful, perhaps put it on /health, rather than on the root?
