### ISSUE TITLE
sql collector : strange values for bufman_buffer_cache_hit_ratio

### ISSUE THREAD

**Issue by vladvasiliu** [martinlindhe/wmi_exporter#250]
Hi,

While trying to set up a dashboard for a MS SQL, I have come upon  wmi_mssql_bufman_buffer_cache_hit_ratio which sometimes has values over 100.

I'm not very familiar with MSSQL, so I was wondering wether this is expected behaviour or if something is wrong ?

I'm using wmi_exporter 0.4.3 on windows 2016 and sql server express 13.0.4001.0.

**Comment by carlpett** [comment]
Definitely sounds strange. Could be that the value needs to be normalized and this isn't done. Could you try this Powershell line?
`gwmi Win32_PerfRawData_MSSQLSERVER_SQLServerBufferManager | select -ExpandProperty Properties | ? Name -eq Buffercachehitratio |  fl -f *`

@szook did you see anything like this in your testing?

**Comment by carlpett** [comment]
Oh, looks like I didn't do that properly... Sorry, could you try this instead?
`gwmi Win32_PerfRawData_MSSQLSERVER_SQLServerBufferManager | select -ExpandProperty Properties | ? Name -eq Buffercachehitratio | select -ExpandProperty Qualifiers | | fl -f *`

The small holes you mean? Possibly, if they are very regular? Hard to determine from the image. It wouldn't impact the actual values, though.

**Comment by vladvasiliu** [comment]
It says an empty pipe element is not allowed. After removing one of the pipes, I get the following:

```
> gwmi Win32_PerfRawData_MSSQLSERVER_SQLServerBufferManager | select -ExpandProperty Properties | ? Name -eq Buffercachehitratio | fl -f *


Name       : Buffercachehitratio
Value      : 117
Type       : UInt64
IsLocal    : True
IsArray    : False
Origin     : Win32_PerfRawData_MSSQLSERVER_SQLServerBufferManager
Qualifiers : {CIMTYPE, CounterType, DefaultScale, DetailLevel...}



> gwmi Win32_PerfRawData_MSSQLSERVER_SQLServerBufferManager | select -ExpandProperty Properties | ? Name -eq Buffercachehitratio | select -ExpandProperty Qualifiers | fl -f *


Name                 : CIMTYPE
Value                : uint64
IsAmended            : False
IsLocal              : False
PropagatesToInstance : True
PropagatesToSubclass : True
IsOverridable        : True

Name                 : CounterType
Value                : 537003264
IsAmended            : False
IsLocal              : False
PropagatesToInstance : True
PropagatesToSubclass : False
IsOverridable        : True

Name                 : DefaultScale
Value                : 0
IsAmended            : False
IsLocal              : False
PropagatesToInstance : True
PropagatesToSubclass : False
IsOverridable        : True

Name                 : DetailLevel
Value                : 100
IsAmended            : False
IsLocal              : False
PropagatesToInstance : True
PropagatesToSubclass : False
IsOverridable        : True

Name                 : DisplayName
Value                : Buffer cache hit ratio
IsAmended            : False
IsLocal              : False
PropagatesToInstance : True
PropagatesToSubclass : False
IsOverridable        : True

Name                 : DisplayName009
Value                : Buffer cache hit ratio
IsAmended            : False
IsLocal              : False
PropagatesToInstance : True
PropagatesToSubclass : False
IsOverridable        : True

Name                 : HelpIndex
Value                : 0
IsAmended            : False
IsLocal              : False
PropagatesToInstance : True
PropagatesToSubclass : False
IsOverridable        : True

Name                 : PerfDefault
Value                : True
IsAmended            : False
IsLocal              : False
PropagatesToInstance : True
PropagatesToSubclass : False
IsOverridable        : True

Name                 : PerfIndex
Value                : 0
IsAmended            : False
IsLocal              : False
PropagatesToInstance : True
PropagatesToSubclass : False
IsOverridable        : True
```

**Comment by carlpett** [comment]
Yeah, apparently I'm not capable of writing Powershell directly in a Github comment... But you figured out my error, thanks.
The interesting thing we get from this is the CounterType value, `537003264`, which maps to the `PERF_LARGE_RAW_FRACTION` type. For these types, we should divide by the corresponding `Base` value.

Could you run `gwmi Win32_PerfRawData_MSSQLSERVER_SQLServerBufferManager` and verify that there is both `Buffercachehitratio` and `BuffercachehitratioBase`? Does `Buffercachehitratio/BuffercachehitratioBase` give a reasonable output?

**Comment by vladvasiliu** [comment]
It does, although the two seem to always be equal. The server is not particularly busy though, so it might not be a problem.

**Comment by joeywizard** [comment]
The value of Buffer Manager\Buffer Cache Hit Ratio (wmi_mssql_bufman_buffer_cache_hit_ratio) is meaningless without the associated base value, which is Buffer Manager\Buffer Cache Hit Ratio Base.  The base value is required to calculate the Buffer Cache Hit Ratio percentage as follows:

100 * Buffer Manager\Buffer Cache Hit Ratio / Buffer Manager\Buffer Cache Hit Ratio Base

To identify the Buffer Manager\Buffer Cache Hit Ratio Base of a SQL Server default instance using PowerShell, run the following command:

Get-WmiObject -Class Win32_PerfRawData_MSSQLSERVER_SQLServerBufferManager | Select-Object -ExpandProperty Properties | Where-Object -FilterScript {$_.Name -match 'Buffercachehitratio_Base'}

Also, here are some other missing base counters in WMI_Exporter that would be useful:

o	Access Methods\Worktables From Cache Base (WorktablesFromCacheRatio_Base)
o	Databases\Log Cache Hit Ratio Base (LogCacheHitRatio_Base)
o	Locks\Average Wait Time Base (AverageWaitTimems_Base)

**Comment by carlpett** [comment]
Based on how other WMI fractional counters behave, I'm guessing that the non-base value is the number of hits, while the base is the total number of cache checks. Rather than exposing the ratio, what we typically do is to expose these two as (correctly named) counters and then you can calculate the hit rate in your PromQL.
In this case, it seems to have slipped through during code review, sadly. I'd be very happy if someone with access to a SQL Server install could submit a PR to fix this :)
