### ISSUE TITLE
IIS metrics not scraped

### ISSUE THREAD

**Issue by anjaneyuludesu** [martinlindhe/wmi_exporter#254]
I used below thing to get iis metrics, but i am not able to see iis metrics are not getting
msiexec /i <path-to-msi-file> ENABLED_COLLECTORS=os,iis LISTEN_PORT=9182

I used wmi_exporter-0.4.3-386 and prometheus-2.3.2

**Comment by carlpett** [comment]
Hi @anjaneyuludesu,
Can you see the metrics by accessing localhost:9182/metrics from the machine where you installed the exporter? Have you checked if there are any errors logged?

**Comment by anjaneyuludesu** [comment]
I used the below commandline the i am able to see 
wmi_exporter.exe --collectors.enabled "cpu,iis"
