### ISSUE TITLE
Can I monitor Windows services?

### ISSUE THREAD

**Issue by chester89** [martinlindhe/wmi_exporter#258]
Hello.
I took this project for a spin and so far it works on my test machine, looking forward to applying it in production.
My question is - I can monitor separate processes, but I can I do the same for Windows services? That would be very useful as I have several services I'd like to keep track of (their network usage, disk IO, memory, etc.)

**Comment by carlpett** [comment]
Hi,
We do have a Service collector (which is enabled by default) that gives you information about the current status such as Running/Stopped, etc.
The actual processes spawned by the service however is not exposed by this collector, you need to use the process collector for it.

**Comment by chester89** [comment]
I see, thanks, I'll look into that
