### ISSUE TITLE
w3wp AppPool name not appended on Server 2016

### ISSUE THREAD

**Issue by DennisGlindhart** [martinlindhe/wmi_exporter#260]
I've updated to the latest WMI exporter (4.3) on a few servers hoping to use this feature:

https://github.com/martinlindhe/wmi_exporter/pull/227

It works perfect on Windows 2012R2 servers, but on 2016 it seems not to work for some reason (both have latest Windows updates).

I've tried uninstall/clean/reinstall several times, using same configuration parameters/collectiors etc. and the servers should be mostly similar except for the Windows Server version.

Anyone who can confirm if they have (or not) working on 2016.

Expected:
`wmi_process_cpu_time_total{creating_process_id="1111",mode="privileged",process="w3wp_apppoolname",process_id="2222"} 1.0`

Actual:
`wmi_process_cpu_time_total{creating_process_id="1111",mode="privileged",process="w3wp",process_id="2222"} 1.0`

**Comment by DennisGlindhart** [comment]
Hi @carlpett ,
They all look like:
`Name                               : 49824_mywebsite.com`

**Comment by carlpett** [comment]
Sorry, I got it wrong - this is in the process collector, not the IIS collector. I was a bit hasty when reading.
Does this query work? `gwmi -Namespace root\WebAdministration WorkerProcess`

**Comment by DennisGlindhart** [comment]
Well, there we have it

```
PS C:\Users\Administrator> gwmi -Namespace root\WebAdministration WorkerProcess
gwmi : Invalid namespace "root\WebAdministration"
At line:1 char:1
+ gwmi -Namespace root\WebAdministration WorkerProcess
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-WmiObject], ManagementException
    + FullyQualifiedErrorId : GetWMIManagementException,Microsoft.PowerShell.Commands.GetWmiObjectCommand
```

Going to Server Manager and installing Role-component **Web Server (IIS)** > **Management Tools** > **IIS Management Scripts and Tools** solves the issue. 

Don't know if the default subcomponent selection is different in newer Windows versions since that was only on my 2012 servers.

I guess this should probably be in some README/Installation instructions somewhere I guess? (Unless it's already there and I've missed it).

Anyways - Thank you very much for the quick help. Really appreciate it (and the software :) )

**Comment by carlpett** [comment]
We've fixed so this is actually logged when it is missing now, so there will be some sort of feedback. If you'd be open to contribute your solution to the new documentation section we'd appreciate it a lot :)
