### ISSUE TITLE
Connection reset by peer.

### ISSUE THREAD

**Issue by mi1ez** [martinlindhe/wmi_exporter#262]
Hi

I am having an issue where I am having the connection reset by a windows server.

I can hit x.x.x.x:9100/metrics from my local box
I can Curl the headers on x.x.x.x:9100/metrics from the Prometheus server - Returns 200 OK
I cannot Curl the content of x.x.x.x:9100/metrics from the Prometheus server - I get a connection reset by peer error

In the list of targets in Prometheus, the error is:

> Get x.x.x.x:9100/metrics: read tcp y.y.y.y:44228->x.x.x.x:9100: read: connection reset by peer

The port is open and can be hit by both my machine and the Prometheus server, does anyone have any suggestions as to why the connection is being reset?

Thanks

Miles

**Comment by carlpett** [comment]
Hi,
Do you have any proxy servers in your environment that you are passing through? Or anything else that might be meddling with the connection? That would be the first suspect.
Otherwise, anything you can tell about the environment in general? Is it cloud-hosted?

**Comment by carlpett** [comment]
Hi,
Yes, as you say, routing seems fine and the port isn't blocked. However, we've seen a few times where there are "security appliances" or proxies that interfere with the traffic.
If this is not the case here, another potential culprit is some misconfiguration in the MTU (maximum transmission unit) somewhere in the network, this could cause "small" packets (like a HEAD request) to work, while larger packets would get dropped.

**Comment by mi1ez** [comment]
Hi
We built a new Prometheus server and this issue gas resolved. No idea what the issue was!
Thanks for your help
Miles
