### ISSUE TITLE
i can't build wmi_exporter

### ISSUE THREAD

**Issue by luowqn** [martinlindhe/wmi_exporter#265]
Hello,I hava a problem. I can't build wmi_exporter
promu build -v .
`F:\学习代码\study\go\src\github.com\martinlindhe\wmi_exporter>promu build -v .
Using config file: F:\学习代码\study\go\src\github.com\martinlindhe\wmi_exporter\.promu.yml
!! binary . not found in config
validation of given binary names for build command failed
github.com/prometheus/promu/cmd.runBuild
        F:/学习代码/study/go/src/github.com/prometheus/promu/cmd/build.go:140
github.com/prometheus/promu/cmd.glob..func1
        F:/学习代码/study/go/src/github.com/prometheus/promu/cmd/build.go:39
github.com/prometheus/promu/vendor/github.com/spf13/cobra.(*Command).execute
        F:/学习代码/study/go/src/github.com/prometheus/promu/vendor/github.com/spf13/cobra/command.go:653
github.com/prometheus/promu/vendor/github.com/spf13/cobra.(*Command).ExecuteC
        F:/学习代码/study/go/src/github.com/prometheus/promu/vendor/github.com/spf13/cobra/command.go:728
github.com/prometheus/promu/vendor/github.com/spf13/cobra.(*Command).Execute
        F:/学习代码/study/go/src/github.com/prometheus/promu/vendor/github.com/spf13/cobra/command.go:687
github.com/prometheus/promu/cmd.Execute
        F:/学习代码/study/go/src/github.com/prometheus/promu/cmd/promu.go:64
main.main
        F:/学习代码/study/go/src/github.com/prometheus/promu/main.go:20
runtime.main
        D:/Go/src/runtime/proc.go:195
runtime.goexit
        D:/Go/src/runtime/asm_amd64.s:2337`

**Comment by martinlindhe** [comment]
You just need to create a empty file named VERSION in the project root

**Comment by luowqn** [comment]
> You just need to create a empty file named VERSION in the project root

Yes,but i can't build.
`Using config file: /home/gostudy/src/github.com/martinlindhe/wmi_exporter/.promu.yml
!! binary . not found in config
validation of given binary names for build command failed
github.com/prometheus/promu/cmd.runBuild
        /home/gostudy/src/github.com/prometheus/promu/cmd/build.go:140
github.com/prometheus/promu/cmd.glob..func1
        /home/gostudy/src/github.com/prometheus/promu/cmd/build.go:39
github.com/prometheus/promu/vendor/github.com/spf13/cobra.(*Command).execute
        /home/gostudy/src/github.com/prometheus/promu/vendor/github.com/spf13/cobra/command.go:653
github.com/prometheus/promu/vendor/github.com/spf13/cobra.(*Command).ExecuteC
        /home/gostudy/src/github.com/prometheus/promu/vendor/github.com/spf13/cobra/command.go:728
github.com/prometheus/promu/vendor/github.com/spf13/cobra.(*Command).Execute
        /home/gostudy/src/github.com/prometheus/promu/vendor/github.com/spf13/cobra/command.go:687
github.com/prometheus/promu/cmd.Execute
        /home/gostudy/src/github.com/prometheus/promu/cmd/promu.go:64
main.main
        /home/gostudy/src/github.com/prometheus/promu/main.go:20
runtime.main
        /usr/local/go/src/runtime/proc.go:201
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1333`

**Comment by carlpett** [comment]
You shouldn't have the `.` at the end, try just `promu build` (or even just `go build`)

**Comment by carlpett** [comment]
:+1: As I understand it it works? Closing this as solved
