### ISSUE TITLE
Release 0.1

### ISSUE THREAD

**Issue by carlpett** [martinlindhe/wmi_exporter#27]
I created a 0.1 milestone as a way to track things that I think are part of a minimum viable first release.

- [x] #14 
- [x] #21 
- [x] #24 
- [x] #37

Anything else that could be seen as required to be useful?

**Comment by martinlindhe** [comment]
Looks great!

**Comment by martinlindhe** [comment]
(Looked over the other issues and the above list looks like a good goal for a 0.1 release)

**Comment by martinlindhe** [comment]
Also, I think we should nuke the https://github.com/martinlindhe/wmi_exporter/wiki/TODO wiki, and use issues with milestones & labels instead

**Comment by carlpett** [comment]
Agreed! Wiki page removed :)

**Comment by carlpett** [comment]
Added one more point: Which collectors should be enabled by default (also update README)? I'm assuming everything except IIS should be on by default? Working on a PR for updating `exporter.go` and the README.

**Comment by martinlindhe** [comment]
@carlpett I think everything enabled except iis sounds reasonable too

**Comment by martinlindhe** [comment]
@carlpett regarding version info in binary.. it "should" work properly now with appveyour but i would like to test it out, can we manually trigger builds with appveyor.. or should we keep fingers crossed and hope it works out when we create the 0.1 tag?

**Comment by carlpett** [comment]
@martinlindhe Looking at the latest build from master it looks like it works:

```
$ ./wmi_exporter.exe -version
wmi_exporter, version 0.1.0 (branch: HEAD, revision: 8974d840d0b96bf9c5c1f912f3c4e2cc6e3bc58f)
  build user:       appvyr-win\appveyor@APPVYR-WIN
  build date:       20161014-07:59:13
  go version:       go1.7.1
```

One thing I just realized, though - should we overwrite the `VERSION` file if there is a tag?

**Comment by martinlindhe** [comment]
dont know.. maybe promu dont require the VERSION file?

**Comment by martinlindhe** [comment]
tested
```
wmi_exporter master * = $ promu build
Unable to find project's version missing `VERSION` or `version/VERSION` file
 >   wmi_exporter.exe
```

ends up with version field being empty in the startup log.

**Comment by martinlindhe** [comment]
so.. could we fill VERSION with current tag in appveyor.yml maybe?

**Comment by martinlindhe** [comment]
seems like other projects using promu has to manually bump the VERSION file, example https://github.com/prometheus/prometheus/blob/master/VERSION :-(

**Comment by carlpett** [comment]
Yes, I think I'd prefer just setting it from the tag and not having it checked in at all. But then we'd need to do something at non-release builds. I like this approach: https://github.com/GitTools/GitVersion, what do you think?

**Comment by carlpett** [comment]
Apparently they have some sort of integration with AppVeyor: http://gitversion.readthedocs.io/en/latest/build-server-support/build-server/appveyor/

**Comment by martinlindhe** [comment]
Seems to suit our needs!
do you want to investigate using gitversion?
also, perhaps we should raise an issue with prometheus/promu if we figure out a way to avoid manually touching VERSION

**Comment by carlpett** [comment]
All boxes checked! :tada:
Good points. I'll give gitversion a look, but let's track that separately and tag 0.1! :cake:

**Comment by martinlindhe** [comment]
Okay, lets merge govendor bump and update VERSION  before tagging!

**Comment by martinlindhe** [comment]
hm wait, VERSION is already "0.1.0" so we can keep it i hope

**Comment by martinlindhe** [comment]
okay, here goes!

**Comment by martinlindhe** [comment]
got some output from appveyor that looked bad, but release binaries was upload so guess we can ignore it?

```
Deploying using GitHub provider
Creating "v0.1.0" release for repository "martinlindhe/wmi_exporter" tag "v0.1.0" commit "e0b6bf5b4fbc5ff5a6bf72ed0508b3b61fe78c7b"...Skipped - release with tag "v0.1.0" already exists
Uploading "wmi_exporter-0.1.0-amd64.msi" to release assets...OK
Uploading "wmi_exporter.exe" to release assets...OK
Build success
```

https://ci.appveyor.com/project/martinlindhe/wmi-exporter/build/161

**Comment by carlpett** [comment]
I think it tries to create the release, but Github automagically created a release for the tag already. So all is well :)

**Comment by martinlindhe** [comment]
okay, all good then!
