### ISSUE TITLE
Getting Invalid Query (0.4.4)

### ISSUE THREAD

**Issue by heydonovan** [martinlindhe/wmi_exporter#278]
Please let me know if there is any additional information needed!

```
PS C:\Program Files\wmi_exporter> .\wmi_exporter.exe --collectors.enabled "service,net" --collector.service.services-where "Name='test123'"
[36mINFO[0m[0000] Enabled collectors: service, net              [36msource[0m="exporter.go:231"
[36mINFO[0m[0000] Starting WMI exporter (version=0.4.4, branch=master, revision=cb9da1ae222558c9f3039b782f00a44e17f2e4b3)  [36msource[0m="exporter.go:242"
[36mINFO[0m[0000] Build context (go=go1.11, user=appvyr-win\appveyor@APPVYR-WIN, date=20181113-16:02:30)  [36msource[0m="exporter.go:243"
[36mINFO[0m[0000] Starting server on :9182                      [36msource[0m="exporter.go:246"
[31mERRO[0m[0003] failed collecting net metrics:<nil> Exception occurred. (Invalid query )  [31msource[0m="net.go:141"
[31mERRO[0m[0003] collector net failed after 1.006425s: Exception occurred. (Invalid query )  [31msource[0m="exporter.go:105"
[31mERRO[0m[0005] failed collecting net metrics:<nil> Exception occurred. (Invalid query )  [31msource[0m="net.go:141"
[31mERRO[0m[0005] collector net failed after 0.870312s: Exception occurred. (Invalid query )  [31msource[0m="exporter.go:105"
```

```
PS C:\Program Files\wmi_exporter> [System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      17134  0
```

**Comment by carlpett** [comment]
Hey @heydonovan! ( 😄 )
Thanks for reporting. Could you confirm that you do get the metrics for the `service` collector, and that it is just the `net` collector that fails?

**Comment by carlpett** [comment]
Thanks! When these "fundamental" classes don't work, usually there is some corruption of your WMI setup (which seems to spontaneously happen on some machines). We've seen this fixed by running `lodctr.exe /r`, so try that and see if it helps.

**Comment by mugen6** [comment]
I had this "invalid query" problem today on Windows 7. The exporter was working for the most part, but it reported the following despite the cpu, net and process collectors being enabled on the client. 

`wmi_exporter_collector_success gauge`
`wmi_exporter_collector_success{collector="cpu"} 0`
`wmi_exporter_collector_success{collector="cs"} 1`
`wmi_exporter_collector_success{collector="logical_disk"} 0`
`wmi_exporter_collector_success{collector="net"} 0`
`wmi_exporter_collector_success{collector="os"} 1`
`wmi_exporter_collector_success{collector="process"} 0`
`wmi_exporter_collector_success{collector="service"} 1`
`wmi_exporter_collector_success{collector="system"} 0`


I tested manually on a random process:

`Get-WmiObject -Query "SELECT * FROM Win32_PerfRawData_PerfProc_Process WHERE Name = 'svchost'"`


And received the same error:

`Get-WmiObject : Invalid query "SELECT * FROM Win32_PerfRawData_PerfProc_Process WHERE Name = 'svchost'"
    + CategoryInfo          : InvalidArgument: (:) [Get-WmiObject], ManagementException
    + FullyQualifiedErrorId : GetWMIManagementException,Microsoft.PowerShell.Commands.GetWmiObjectCommand`

This only affected 5% of my estate; most units returned a valid response. I fixed them by pushing out the following batch script:

`@echo off`
`sc config winmgmt start= disabled`
`net stop winmgmt /y`
`%systemdrive%`
`cd %windir%\system32\wbem`
`for /f %%s in ('dir /b *.dll') do regsvr32 /s %%s`
`wmiprvse /regserver`
`sc config winmgmt start= auto`
`net start winmgmt`
`for /f %%s in ('dir /s /b *.mof *.mfl') do mofcomp %%s`
`cd c:\windows\system32`
`lodctr /R`
`cd c:\windows\sysWOW64`
`lodctr /R`


Unfortunately I didn't see this thread until after I pushed out the script, so I did not test to see if `lodctr.exe /r` worked alone without re-registering dll files etc.

**Comment by carlpett** [comment]
Since we haven't heard back, I'll close this for now. Let us know if this is still a problem and the above suggestion did not help!
