### ISSUE TITLE
prometheus console templates

### ISSUE THREAD

**Issue by nbirnel** [martinlindhe/wmi_exporter#281]
The prometheus console templates examples do not include anything to render wmi_exporter metrics. On https://github.com/prometheus/prometheus/pull/4870 it was suggested that a template for wmi_exporter should go in this repository. 

Would a PR with this be welcome, and would ``prometheus/console_templates`` be a good location?

**Comment by brian-brazil** [comment]
> I believed console templates aren't really used/maintained any more

They're used and maintained (very little maintenance on them), but Grafana is far more popular.

**Comment by nbirnel** [comment]
@carlpett Thanks; I'll make the PR sometime this week. 

The use case is: I have prometheus running. Implementing Grafana is additional time that I do not (yet) have hours approved for. In the meanwhile, some basic console functionality is desirable.

**Comment by carlpett** [comment]
We can close this, right?
