### ISSUE TITLE
missing many metrics

### ISSUE THREAD

**Issue by madejusz** [martinlindhe/wmi_exporter#288]
wmi_exporter version 0.5.0
Tested on: Windows 10 and Windows 2016 Server

WMI started with options:

_wmi_exporter.exe --collectors.enabled="[defaults],dns,msmq,process,tcp"
[33mWARN[0m[0000] No where-clause specified for process collector. This will generate a very large number of metrics!  [33msource[0m="process.go:50"
[33mWARN[0m[0000] No where-clause specified for service collector. This will generate a very large number of metrics!  [33msource[0m="service.go:39"
[36mINFO[0m[0000] Enabled collectors: os, textfile, process, cpu, net, dns, tcp, logical_disk, system, service, msmq, cs  [36msource[0m="exporter.go:231"
[36mINFO[0m[0000] Starting WMI exporter (version=0.5.0, branch=master, revision=2766f0e3af9a7570d6b812eaf4bf262754c2d47f)  [36msource[0m="exporter.go:242"
[36mINFO[0m[0000] Build context (go=go1.11, user=appvyr-win\appveyor@APPVYR-WIN, date=20181118-20:48:48)  [36msource[0m="exporter.go:243"
[36mINFO[0m[0000] Starting server on :9182                      [36msource[0m="exporter.go:246"_

metrics:
$ curl -s windowshost:9182/metrics |egrep -v '^#' |cut -d\_ -f1-2 | sort|uniq
go_gc
go_goroutines 14
go_memstats
process_start
wmi_exporter
wmi_memory
wmi_os
wmi_process
wmi_tcp
$

Many metrics - like  'system' or 'dns' - are missing.

**Comment by carlpett** [comment]
Hi @madejusz,
Thanks for reporting! Did this work on previous versions of wmi_exporter, or is this your first installed version? And to make sure, you don't get any errors at all in the console?
You should have a metric `wmi_exporter_collector_success`, what labels and values do you get there?

**Comment by madejusz** [comment]
Update from my side: look like everything is fine. Someone from windows team install exporter in wrong way. Thanks for help :-)
