### ISSUE TITLE
Install service with filter

### ISSUE THREAD

**Issue by rewt** [martinlindhe/wmi_exporter#290]
Please advise on most efficient means of filtering metrics?  

[It appears filters are able to be passed during install](https://github.com/martinlindhe/wmi_exporter/issues/170), but my attempts thus far have failed.

Can someone please help me debug this command:

`msiexec /i wmi_exporter-0.5.0-amd64.msi ENABLED_COLLECTORS="cpu,os,iis,logical_disk,net,process,tcp,service --collector.service.services-where "Status='error'""`

**Comment by VR6Pete** [comment]
I wrote a Powershell script that tweaks the service ImagePath based on the filters I wanted to configure to get around this issue.

**Comment by rewt** [comment]
> I wrote a Powershell script that tweaks the service ImagePath based on the filters I wanted to configure to get around this issue.

Would you mind sharing?  I'm having trouble understanding the proper syntax.

**Comment by carlpett** [comment]
Hi @rewt,
Yes, there really should be a way to pass arbitrary flags to the installer. I'll try to find some time to do this.
In the meantime, for the workaround not working, I think you might be missing a set of quotes. Try `ENABLED_COLLECTORS="cpu,os,iis,logical_disk,net,process,tcp,service --collector.service.services-where ""Status='error'"""`

**Comment by rewt** [comment]
> Hi @rewt,
> Yes, there really should be a way to pass arbitrary flags to the installer. I'll try to find some time to do this.
> In the meantime, for the workaround not working, I think you might be missing a set of quotes. Try `ENABLED_COLLECTORS="cpu,os,iis,logical_disk,net,process,tcp,service --collector.service.services-where ""Status='error'"""`

those extra quotes did it, thank you!
