### ISSUE TITLE
Better name of Win32_PerfRawData_PerfDisk_LogicalDisk metrics

### ISSUE THREAD

**Issue by martinlindhe** [martinlindhe/wmi_exporter#3]
Currently named "perf"

Suggested names:
* disk
* io

Please add a vote or another suggestion, We'll rename it in a few days.

**Comment by martinlindhe** [comment]
@carlpett

**Comment by carlpett** [comment]
My vote would be `logical_disk`, despite the length :) If we will expose the `PhysicalDisk` family some time (which I think would be useful) , it will need to be possible to distinguish them.

**Comment by martinlindhe** [comment]
Makes sense. I have no objections :-)

**Comment by martinlindhe** [comment]
Do you mind doing the rename, if you are already knee-deep in the code? Otherwise I'll do it on monday or so. Also the perf.go should be renamed to logical_disk.go, and maybe refactor the subsystem name into a const.

**Comment by carlpett** [comment]
Sure! Good point about the const as well.

**Comment by martinlindhe** [comment]
(hopefully resolved in #5)
