### ISSUE TITLE
Problem when upgrading from 0.4.3-386 to 0.5.0-386

### ISSUE THREAD

**Issue by facundofarias** [martinlindhe/wmi_exporter#306]
Hello there,

I have a Windows 2012R2 server, in which I had installed the version 0.4.3-386 and it was working fine. Now, I've tried to upgrade to the version 0.5.0-386, the installation looks successful, but the win32 service is never started, and I cannot even see it on the services list. I've also tried running it as admin, but it didn't work either.

Is there a process to do such upgrade? Should I uninstall the old version and then, try again?
Thanks

**Comment by carlpett** [comment]
Hi,
The upgrade _should_ "just work", so this seems odd. Did you by chance have the services administration tool open when you did the upgrade? From other work with Windows installer, I've seen this can in some circumstances cause Windows to require a reboot, also when there is another pending reboot (such as for Windows Update).
However, both of these typically give some feedback afterwards, so it seems a bit strange...

Separate question, though, why are you using the 386 version on 2012R2? That version of Windows is only available in 64-bit, so I would recommend using the amd64 installer instead.

**Comment by facundofarias** [comment]
Hello @carlpett,
Indeed the Services Administration Tool was opened. Anyway, I've managed to make it work by uninstalling and installing everything from scratch. Maybe is the issue that you have mentioned.
I will also check the 64-bit version.

Thanks for the quick response!
