### ISSUE TITLE
Total I/O time is missing from the logical_disk metrics.

### ISSUE THREAD

**Issue by sachinmsft** [martinlindhe/wmi_exporter#315]
I don't see any metrics for the total I/O time for the disk.
PercentDiskTime field in class Win32_PerfRawData_PerfDisk_LogicalDisk populate the I/O time.

if folks are okay then i can send the PR.

**Comment by carlpett** [comment]
Hi @sachinmsft!
I don't remember exactly, but I recall that the reasoning was that it would basically be the inverse of `PercentIdleTime` that we expose? If that is a bad assumption (based on your username, you might have access to insider knowledge ;) ), we should definitely expand to cover it.
We also expose PercentReadTime and PercentWriteTime, which might also sum up to PercentDiskTime?

**Comment by sachinmsft** [comment]
Thanks @carlpett for prompt reply. I think PercentReadTime and PercentWriteTime can be sum up to PercentDiskTime. I am closing this issue.
