### ISSUE TITLE
Implement containers metrics

### ISSUE THREAD

**Issue by SubodhBhargava** [martinlindhe/wmi_exporter#316]
Implement the optional metrics collector for Windows containers running on the host. As WMI exporter provides A-Z metrics for the host, it would make sense to implement containers metrics also on WMI exporter and make it a single source for all the metrics for Windows subsystem

**Comment by dbahr7** [comment]
Yes, PLEASE!
This would address a big gap in monitoring containers in Microsoft shops. 
There are other container metrics apps, but none of them address windows containers on a windows host.

**Comment by SubodhBhargava** [comment]
Thanks. Can we please get this issue assigned to @sachinmsft

**Comment by sachinmsft** [comment]
@carlpett I have changes ready for container metrics but I am not able to send the PR. Seems I don't have permission to push the changes on this repository. Can you please grant me the access.

**Comment by sachinmsft** [comment]
@carlpett Please ignore above comment, I was making mistake in sending the PR.

**Comment by carlpett** [comment]
Closed by #320
