### ISSUE TITLE
Support for ELK?

### ISSUE THREAD

**Issue by satyagadepalli** [martinlindhe/wmi_exporter#318]
How can i integrate wmi_exporter with ELK stack? Any help?

thx

**Comment by carlpett** [comment]
Hi @satyagadepalli,
I think we'll need some more details on what you are trying to achieve? Do you want the wmi_exporter logs to be sent to your ELK stack?

**Comment by satyagadepalli** [comment]
Yes. Exactly. I want to use the WMI_EXPORTER instead of a ELK off the shelf beats.

**Comment by carlpett** [comment]
Oh, you mean the ELK metrics ingestion bits, not logging? As far as I'm aware, we haven't tested this at all, but anything that can ingest Prometheus metrics will work. 
So I'd start by just installing wmi_exporter and then configuring ELK to read from it. How that is done I'll have to refer you to the ELK docs, though.

**Comment by satyagadepalli** [comment]
Just see https://github.com/elastic/beats/tree/master/libbeat

**Comment by carlpett** [comment]
I'm afraid we're unable to provide detailed guidance on configuring other systems than wmi_exporter here. I'd suggest reading [this post](https://discuss.elastic.co/t/dec-23rd-2018-en-observability-querying-metrics-from-prometheus-with-elastic-stack/161609) on how to work with "metricbeat", which should hopefully cover your usecase.
If you run in to any issues with wmi_exporter itself when doing the integration, please open a new issue with details.
