### ISSUE TITLE
Monitoring Windows service existance

### ISSUE THREAD

**Issue by greenpau** [martinlindhe/wmi_exporter#322]
I want to monitor whether a service, e.g. `myservice`, exists (installed) on a host.

The `wmi_exporter` has a metric called `wmi_service_state` and by running the below I would find the instances where the service is running:

```
wmi_service_state{job="wmi_exporters",name="myservice",state="running"}
```

The `up` metric also exists and I can use it in the following manner (the query does not make much sense; rather, it might be used to answer the question):

```
(
  up{job="wmi_exporters"}
)
   * on(instance,job) group_left(name,state)
(
   wmi_service_state{job="wmi_exporters",name="myservice",state="running"}
)
```

What would be the query to get the `up` instances that do not have `myservice` service?

**Comment by carlpett** [comment]
Hi @greenpau!
I'm not at a computer where I can test out a query, but a question first: Do you care about the distinction if the service is installed but not running vs not installed at all? `wmi_service_state{job="wmi_exporters",name="myservice",state="running"}` will be 0 if it is installed but non-running, while it will be absent if the service is not installed.

**Comment by greenpau** [comment]
> Do you care about the distinction if the service is installed but not running vs not installed at all?

@carlpett, yes I do.  I already monitor for "not running" condition.  It is all about "not installed".

**Comment by lars-nielsen** [comment]
The only way i can see this work is to implement a param on the exporter and configure the scrape job appropriately

```
  - job_name: "wmi_exporters"
    params:
      service_check_existence: [myservice]
```

The the missing "NotInstalled" state can be returned

`wmi_service_state{job="wmi_exporters",name="myservice",state="notinstalled"}`

**Comment by greenpau** [comment]
@lars-nielsen , @carlpett , here is another way of solving this.

```
count(wmi_system_system_up_time{}) by (instance) > 0 UNLESS count(wmi_service_start_mode{name="myservice"}) by (instance) > 0
```
