### ISSUE TITLE
Bug with http request

### ISSUE THREAD

**Issue by apokhmelnykh** [martinlindhe/wmi_exporter#325]
I found this strange behavior. If i request data from url, my browser also request favicon.ico, it is by default.  And wmi_exporter also serve this request, by redirect them to /metrics. Thus it must genereate metrics twice. And it's like URL filtering doesn't work, because i can request any URL and it will be redirected to /metrics.
![image](https://user-images.githubusercontent.com/48472869/54186568-bc960700-44bc-11e9-94f3-a3feff64dbac.png)

**Comment by martinlindhe** [comment]
The prometheus collector would not generate a /favicon.ico request, so you can only see this in testing. You can also configure your browser not to generate favicon.ico requests when there is no such resource given in the HTML.

For firefox, set browser.chrome.favicons to false to disable this behaviour.

**Comment by martinlindhe** [comment]
What is it that you expect about url filtering here?
This is a Prometheus collector and it's only purpose is to expose collected metrics over HTTP.

**Comment by apokhmelnykh** [comment]
> What is it that you expect about url filtering here?
> This is a Prometheus collector and it's only purpose is to expose collected metrics over HTTP.

I mean, if use node_exporter for linux and try to get data from linux-host:9100/blabla i am didn't get anything. And on other side, if i am use windows host with wmi_exporter win-host:9100/blabla i will be redirected on win-host:9100/metrics.

**Comment by martinlindhe** [comment]
If you simply want to check if the wmi_exporter is alive using http, you can use the special host:9182/health url.

Does that solve your issue?

**Comment by martinlindhe** [comment]
> I mean, if use node_exporter for linux and try to get data from linux-host:9100/blabla i am didn't get anything. And on other side, if i am use windows host with wmi_exporter win-host:9100/blabla i will be redirected on win-host:9100/metrics.

If I understand you correctly you are arguing that our behavior when the user requests a non-existing resource on a Prometheus collector is diverging from an expected behavior?

**Comment by apokhmelnykh** [comment]
> > I mean, if use node_exporter for linux and try to get data from linux-host:9100/blabla i am didn't get anything. And on other side, if i am use windows host with wmi_exporter win-host:9100/blabla i will be redirected on win-host:9100/metrics.
> 
> If I understand you correctly you are arguing that our behavior when the user requests a non-existing resource on a Prometheus collector is diverging from an expected behavior?

**Comment by apokhmelnykh** [comment]
> If I understand you correctly you are arguing that our behavior when the user requests a non-existing resource on a Prometheus collector is diverging from an expected behavior?

Yes, it's just about policy how exporter works with non-existing  resources. And it's not a big problem. Thank you.
