### ISSUE TITLE
[featurerequest] file exporter

### ISSUE THREAD

**Issue by blendi-93** [martinlindhe/wmi_exporter#33]
can u pls implement a fileexporter so i dont have to fire u node_exporter and wmi_exporter on windows?

thx.

**Comment by carlpett** [comment]
I guess we'll need to discuss this, but I'm not too keen on duplicating every feature in node_exporter just for its own sake, especially functionality that actually works on Windows in the existing package.
@martinlindhe Opinion?

**Comment by brian-brazil** [comment]
If this is just a node-exporter equivalent we should have it. If it's more like the JMX exporter and does more general WMI stuff it's more questionable.

**Comment by martinlindhe** [comment]
Thanks for the input @brian-brazil 
i need to have a look as I'm not familiar with what this file exporter is doing

/m

**Comment by yosefy** [comment]
+1
it would solve all the missing stuff :)
for example i need to get something form event log.
this feature doesn't exist in wmi_exporter and may not happen soon
so we will just run some powershell and put a metric there

thanks

**Comment by z3rogate** [comment]
+1

**Comment by lubyou** [comment]
+1

**Comment by martinlindhe** [comment]
Hi all :-) Please use the emoticons to add "me too", the +1 comments only add spam to the subscribers

**Comment by madeinoz67** [comment]
I have a requirement for file export functionality where I have an ancient process (pick DB running on windows server) that has scheduled jobs to dump license and user stats reports into a text file that I'd like to get into prometheus.   Seeing that the file exporter is part of node exporter my thoughts are the file-exporter functionality should be mirrored in the WMI-exporter

**Comment by martinlindhe** [comment]
@madeinoz67 

Feel free to submit a pull request

**Comment by carlpett** [comment]
This has now been implemented in #174, and released with wmi_exporter 0.3!
