### ISSUE TITLE
High Virtual memory consumption by WMI exporter(0.3.3)

### ISSUE THREAD

**Issue by vivekbny** [martinlindhe/wmi_exporter#337]
@martinlindhe 

We are seeing high virtual memory caused by the WMI exporter. All the issues so far reported on the exporter has been on WINDOWS 2008 R2 and 6.1 OS Version.

Due to this issue, it is consuming all available resources and therefore staving the application on the servers.

Is there anything we can do to stop this exporter from consuming high memory usage.(We are using the default collectors when installing)

Thanks,
Vivek

**Comment by martinlindhe** [comment]
You can use pprof to analyze the memory usage, see #77

**Comment by vivekbny** [comment]
ok.. sure

**Comment by carlpett** [comment]
In addition, it might make sense to use a later version of the exporter. 0.3.3 is over a year old, and much has changed in the code base since then.

**Comment by carlpett** [comment]
I think we'll close this for now. If there are memory concerns on recent versions, open a new issue.
