### ISSUE TITLE
Add/remove collectors post-install

### ISSUE THREAD

**Issue by voidmonk** [martinlindhe/wmi_exporter#341]
Hi, how can I reconfigure the exporter to add or remove collectors after msi installation?

**Comment by carlpett** [comment]
Hi @voidmonk,
At that point it has been registered as a Windows service, and you'll need to make a change to that registration. You can use the builtin `sc.exe` utility in Windows for this.

**Comment by voidmonk** [comment]
Thanks @carlpett.

Just putting the steps here for reference:

- run `sc qc wmi_exporter` to query the current config (`collectors.enabled` in `BINARY_PATH_NAME`)
- change the config with `sc config wmi_exporter binPath="..."` (specify full `binPath` with new `collectors.enabled` settings)
- restart the exporter service with `sc stop wmi_exporter` and `sc start wmi_exporter`

**Comment by ag-giesa** [comment]
here is an example:
`sc config wmi_exporter binPath= "\"C:\Programme\wmi_exporter\wmi_exporter.exe\" --collectors.enabled \"cs,cpu,logical_disk,memory,service,system,textfile\" --collector.textfile.directory \"C:\batchjobs\prometheus\" --collector.service.services-where=\"Name='wmi_exporter' or Name='spooler'\" "`

**Comment by pauloligorio** [comment]
Hi guys, I have a prometheus and grafana environment, and using the windows node dashboard within grafana.

I would like to monitor iis connections, but I am not able to enable the responsible collector, I tried to carry out the steps mentioned above by @VoidMonk but without success, today the service name is windows_exporter, correct?

How can I enable IIS collector in current version of windows_exporter?

**Comment by breed808** [comment]
You'll need to run the commands provided by @VoidMonk and replace `wmi_exporter` with `windows_exporter`.

**Comment by pauloligorio** [comment]
@breed808 
This to worked for me.
I had to reinstall the collector.

`msiexec /i windows_exporter-0.18.1-amd64.msi ENABLED_COLLECTORS="ad,adfs,cache,cpu,cpu_info,cs,container,dfsr,dhcp,dns,fsrmquota,iis,logical_disk,logon,memory,msmq,mssql,netframework_clrexceptions,netframework_clrinterop,netframework_clrjit,netframework_clrloading,netframework_clrlocksandthreads,netframework_clrmemory,netframework_clrremoting,netframework_clrsecurity,net,os,process,remote_fx,service,system,tcp,time,vmware" TEXTFILE_DIR="C:\custom_metrics" LISTEN_PORT="9182"`

**Comment by spacedustz** [comment]
@pauloligorio 

thank you so much, you're my savior
