### ISSUE TITLE
wmi_exporter and prometheus 

### ISSUE THREAD

**Issue by barca00** [martinlindhe/wmi_exporter#349]
Hello,

sorry I am new to this topic and I am trying to solve the most problems on my own but I am stuck here and just can't find any help anywhere. 

So I got this wmi_exporter service up running, I can see the metrics on my localhost, normally we need to add then this exporter to Prometheus, right? So prometheus can get the data and we can use it then in Grafana. 

If so how do I connect wmi_exporter to export its data to prometheus.

**Comment by carlpett** [comment]
Hi @barca00,
Correct, cince when can see the metrics on localhost, you are almost there :) 
The final step of making the Prometheus server aware of your exporter can be done in many ways depending on how your infrastructure is set up. Take a look at the documentation for the [Prometheus server configuration](https://prometheus.io/docs/prometheus/latest/configuration/configuration/), specifically you'll want to looks at the `*_sd_config` sections. For example, if you are running in any of the major cloud providers, there will be a way to automatically find your VMs.
If none of them fit your usecase, or for quick experimentation, you can use `static_config` and just list the hosts you want to scrape metrics from directly.

**Comment by barca00** [comment]
Thank you for your anwser.

Ok so I start wmi_exporter and open http://localhost:9182/metrics -> it works.

I write this configuration in prometheus.yml file and won't start. Is there any log I can check what is the problem or is just my configuration wrong.
`  - job_name: 'wmi_exporter'
    static_configs:      
    - targets": [ 'localhost:9182' ]`

**Comment by carlpett** [comment]
If the configuration is not parseable, Prometheus should write it to the terminal output before exiting. If you aren't already, try running it via the command prompt (if you just double-click the .exe, it'll probably close before you can read the output).

As for the configuration, are you putting it all on the same line, or is Github mis-formatting it? If it is on one line, that won't work. It also looks like you have a single `"` by `targets`, which would also be a syntax error. Try this:
```yaml
- job_name: 'wmi_exporter'
  static_configs:
  - targets: [ 'localhost:9182' ]
```

**Comment by barca00** [comment]
OK it was a syntax failure. Everything works fine thank you for your help. 

I am just starting to play around with prometheus etc.

**Comment by carlpett** [comment]
Glad it works!
