### ISSUE TITLE
How to query multiple process and service

### ISSUE THREAD

**Issue by shivcena** [martinlindhe/wmi_exporter#354]
Hi Everybody,
I downloaded the "wmi_exporter-0.7.0-386.exe" from the github link and ran the '.exe' file using command prompt.

Also i have followed the  github  prometheus wmi guidance to run the command in the command prompt ,it executed as expected and i am able to check the metrics in "http: //localhost:9182/metrics".

My problem here is , if i run the command "./wmi_exporter-0.7.0-386.exe" alone using the command prompt , i am able to check the memory utilization of my system.For example it is showing the details of the memory utilization like "wmi_cs_physical_memory_bytes 3.4673408e+10" and all the memory details as well in browser metrics.

But if i run the command ".\wmi_exporter.exe --collectors.enabled "process" --collector.process.processes-where "Name LIKE 'firefox%'"" , in metrics it is filtering only the "firefox" browser related things , i am not able to check the system memory utilization details like "wmi_cs_physical_memory_bytes 3.4673408e+10".

Kindly suggest me , how to execute query and check the metrics while running "wmi_exporter.exe". For example i need to write the query, to check the memory consumption of my firefox browser as well as the "available memory" of my local system and pass as an argument to "wmi_exporter.exe" (or) any other way to achieve this.

**Comment by martinlindhe** [comment]
You need to also enable the "cs" collector. Something like this should work:

```
".\wmi_exporter.exe --collectors.enabled "process,cs" --collector.process.processes-where "Name LIKE 'firefox%'""
```

**Comment by shivcena** [comment]
working awesome , Thanks a lot

**Comment by shivcena** [comment]
@martinlindhe : how to query for multiple process , for example for 'firefox' and 'chrome'
I have tried 
.\wmi_exporter.exe --collectors.enabled "process,cs,logical_disk" --collector.process.processes-where "Name LIKE 'firefox%' and 'chrome%'"
and
.\wmi_exporter.exe --collectors.enabled "process,cs,logical_disk" --collector.process.processes-where "Name LIKE 'firefox%' ,'chrome%'"
both are giving exception

**Comment by martinlindhe** [comment]
I think something like this should work for your case, please report back!

```
--collector.process.processes-where "Name LIKE 'firefox%' OR Name LIKE 'chrome%'"
```

**Comment by shivcena** [comment]
Genius!!!! working fine, Thank you very much
