### ISSUE TITLE
0.7.0 MSI: service failed to start

### ISSUE THREAD

**Issue by GSR70** [martinlindhe/wmi_exporter#355]
Installing using the MSI, with no parameters and an escalated command prompt, I get the following message that the service could not start due.
![image](https://user-images.githubusercontent.com/52212209/60113685-8dd03380-972f-11e9-8fea-eb6328571f16.png)

This also generates System event ID 7031:
Log Name:      System
Source:        Service Control Manager
Date:          6/25/2019 11:37:38 AM
Event ID:      7031
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      xyz123.local
Description:
The WMI exporter service terminated unexpectedly.  It has done this 1 time(s).  The following corrective action will be taken in 5000 milliseconds: Restart the service.

**Comment by GSR70** [comment]
Running 'wmi_exporter-0.7.0-amd64.exe' does start and allows the localhost:9182 to display the metrics.  Found that using the 'wmi_exporter-0.7.0-386.msi' instead of 'wmi_exporter-0.7.0-amd64.msi'
did work, although it was a 64-bit OS.

**Comment by carlpett** [comment]
Great that you found a workaround! However, that is odd. What version of Windows is that?

**Comment by GSR70** [comment]
Unfortunately it was Windows Server 2008 R2 Enterprise SP1 (x64) we were using to trial this out on.  Going to assume the same won’t occur for our Server 2016 boxes.

Regards,
Greg

Greg Redl
T:  +1.403.476.1132  | C:  +1.403.608.4264
E: greg.redl@bidstrading.com<mailto:greg.redl@bidstrading.com> | W: www.bidstrading.com<http://www.bidstrading.com/>

**Comment by carlpett** [comment]
2008R2 _should_ work... (In fact, I know of a bunch of Win2003 installations 🙈)
And if the 32 bit version works, I don't fully understand why the 64 bit wouldn't. However, we'd probably need to do a fair amount of digging to figure out what is going wrong, so if you don't have a problem, I understand not wanting to dedicate time to old installations.

**Comment by GSR70** [comment]
Hi Calle,

I appreciate the offer to debug further, but we are planning to decom all Server 2008 by the end of Q3 to get ahead of the Microsoft deadline.  Until then, the 32-bit version is working and will get us through till the OS refresh project is completed.

Regards,
Greg

Greg Redl
T:  +1.403.476.1132  | C:  +1.403.608.4264
E: greg.redl@bidstrading.com<mailto:greg.redl@bidstrading.com> | W: www.bidstrading.com<http://www.bidstrading.com/>
