### ISSUE TITLE
sql collector exception

### ISSUE THREAD

**Issue by AxelSpieth** [martinlindhe/wmi_exporter#356]
When starting the wmi_exporter with the sql colletor enabled:

wmi_exporter.exe --telemetry.addr=":9182" --collectors.enabled="mssql"

I get the folowing messages:

collectors.enabled="mssql"
←[33mWARN←[0m[0000] Couldn't open registry to determine SQL instances:The system
 cannot find the file specified.  ←[33msource←[0m="mssql.go:44"
←[36mINFO←[0m[0000] Enabled collectors: mssql                     ←[36msource←[0
m="exporter.go:237"
←[36mINFO←[0m[0000] Starting WMI exporter (version=0.7.0, branch=master, revisio
n=8841091f9c7c9e88e6a5948a656af1bc29cfcd58)  ←[36msource←[0m="exporter.go:248"
←[36mINFO←[0m[0000] Build context (go=go1.11, user=appvyr-win\appveyor@APPVYR-WI
N, date=20190314-05:46:51)  ←[36msource←[0m="exporter.go:249"
←[36mINFO←[0m[0000] Starting server on :9182                      ←[36msource←[0
m="exporter.go:252"
←[31mERRO←[0m[0001] mssql class collector sqlstats failed after 0.014001s: Excep
tion occurred. (Invalid class )  ←[31msource←[0m="mssql.go:1667"
←[31mERRO←[0m[0001] mssql class collector genstats failed after 0.018008s: Excep
tion occurred. (Invalid class )  ←[31msource←[0m="mssql.go:1667"
←[31mERRO←[0m[0001] mssql class collector accessmethods failed after 0.022003s:
Exception occurred. (Invalid class )  ←[31msource←[0m="mssql.go:1667"
←[31mERRO←[0m[0001] mssql class collector bufman failed after 0.027001s: Excepti
on occurred. (Invalid class )  ←[31msource←[0m="mssql.go:1667"
←[31mERRO←[0m[0001] mssql class collector databases failed after 0.031002s: Exce
ption occurred. (Invalid class )  ←[31msource←[0m="mssql.go:1667"
←[31mERRO←[0m[0001] mssql class collector availreplica failed after 0.036003s: E
xception occurred. (Invalid class )  ←[31msource←[0m="mssql.go:1667"
←[31mERRO←[0m[0001] mssql class collector locks failed after 0.041007s: Exceptio
n occurred. (Invalid class )  ←[31msource←[0m="mssql.go:1667"
←[31mERRO←[0m[0001] mssql class collector dbreplica failed after 0.045004s: Exce
ption occurred. (Invalid class )  ←[31msource←[0m="mssql.go:1667"
←[31mERRO←[0m[0001] mssql class collector memmgr failed after 0.050003s: Excepti
on occurred. (Invalid class )  ←[31msource←[0m="mssql.go:1667"
←[31mERRO←[0m[0001] collector mssql failed after 0.050003s: at least one child c
ollector failed  ←[31msource←[0m="exporter.go:106"

and no data is collected. What wents wrong ?
and what should I do to fix this issue

It is WIN2012 and SQL 2012

BR Axel

**Comment by martinlindhe** [comment]
Hi @AxelSpieth 

What is the output of these powershell command on the affected system?

```
Get-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\Instance Names\SQL'


Get-ItemProperty -Path 'HKLM:\SOFTWARE\Wow6432Node\Microsoft\Microsoft SQL Server\Instance Names\SQL'

```

This registry key is used to query SQL server details for the sql collector to function. The error you posted indicates it's not available on your system.

Are you running a 32-bit sql server on a 64 bit os?

@carlpett if this is 32-bit sql server on 64-bit os, the correct key to query should be `

HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Microsoft SQL Server\Instance Names\SQL`

**Comment by AxelSpieth** [comment]
Hi @martinlindhe 

Get-ItemProperty -Path 'HKLM:\SOFTWARE\Wow6432Node\Microsoft\Microsoft SQL Server\Instance Names\SQL'

Result:

HYDMS1       : MSSQL12.HYDMS1
SQLEXPRESS   : MSSQL10.SQLEXPRESS
PSPath       : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SQL Server\Instance
               Names\SQL
PSParentPath : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SQL Server\Instance
               Names
PSChildName  : SQL
PSDrive      : HKLM
PSProvider   : Microsoft.PowerShell.Core\Registry

Get-ItemProperty -Path 'HKLM:\SOFTWARE\Wow6432Node\Microsoft\Microsoft SQL Server\Instance Names\SQL'

Result:

Get-ItemProperty : Cannot find path 'HKLM:\SOFTWARE\Wow6432Node\Microsoft\Microsoft SQL Server\Instance Names\SQL'
because it does not exist.
At line:1 char:1
+ Get-ItemProperty -Path 'HKLM:\SOFTWARE\Wow6432Node\Microsoft\Microsoft SQL Serve ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (HKLM:\SOFTWARE\...tance Names\SQL:String) [Get-ItemProperty], ItemNotFo
   undException

and it is a 64bit SQL Server on a 64 bit os:

SELECT @@VERSION

Microsoft SQL Server 2014 (SP1-GDR) (KB4019091) - 12.0.4237.0 (X64) 
	Jul  5 2017 22:03:42 
	Copyright (c) Microsoft Corporation
	Standard Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)


BR Axel

**Comment by martinlindhe** [comment]
Could be the casing of the registry key path.

Perhaps changing https://github.com/martinlindhe/wmi_exporter/blob/56be7c63d56a6af0aed08709558e8a54215536b3/collector/mssql.go#L41 from Software to SOFTWARE

**Comment by AxelSpieth** [comment]
@martinlindhe 

I'm not shure how to build a new version aof the collector.
- can you advice me how to do this?
- ca you build a version for me to test this ?

BR Axel

**Comment by AxelSpieth** [comment]
@martinlindhe 
I got it solved to build a new version of the wmi_exporter with 

regkey := `SOFTWARE\Microsoft\Microsoft SQL Server\Instance Names\SQL`


-> nothing changed 
-> any further suggetions


BR

Axel

**Comment by carlpett** [comment]
Hm, strange. And just to double-check: you are running the 64-bit version of wmi_exporter as well (the one called amd64, rather than 386)?

**Comment by AxelSpieth** [comment]
@carlpett 

That's it - i downloaded the 386 version not the amd64 version cause there is no amd processor it's an intel. The namining is a littel bit confusing.

With the amd64 version the sql collector works.

Thanks for helping 

BR Axel

**Comment by carlpett** [comment]
Yes, it is unfortunate that that naming got established (good PR move by AMD, though...). In this case, it is the Go compiler that names the architectures that way. Perhaps we should add some text about it, though.
