### ISSUE TITLE
has the same name as a metric family used by the Pushgateway itself but it has a different help string

### ISSUE THREAD

**Issue by imluyuan** [martinlindhe/wmi_exporter#358]
From Pushgateway log
time="2019-07-12T08:58:36Z" level=info msg="Metric family 'name:\"go_memstats_sys_bytes\" help:\"Number of bytes obtained by system. Sum of all system allocations.\" type:GAUGE metric:<label:<name:\"instance\" value:\"v-eb86f815-d6e6-4ebe-9fcd-6ec7b10ba95f-192.168.0.15\" > label:<name:\"job\" value:\"virt-by-push-for-windows\" > gauge:<value:1.16718e+07 > > ' has the same name as a metric family used by the Pushgateway itself but it has a different help string. Changing it to the standard help string \"Number of bytes obtained from system.\". This is bad. Fix your pushed metrics!" source="diskmetricstore.go:137"

**Comment by carlpett** [comment]
Why (and how?) are you using pushgateway in combination with wmi_exporter? This is not a common or recommended configuration.
Regarding the error itself, the metric comes from the official Prometheus Go library, so I assume we are using a different version than Pushgateway.

**Comment by imluyuan** [comment]
Yep，I use pushgateway in combination with wmi_exporter on openstack. it seems like the  official Prometheus Go library too old or version problem?
because node exporter not problem.

**Comment by imluyuan** [comment]
```
Build Information
branch	HEAD
buildDate	20190413-11:29:19
buildUser	root@00855c3ed64f
goVersion	go1.11.8
revision	d90bf3239c5ca08d72ccc9e2e2ff3a62b99a122e
version	0.8.0
```

**Comment by carlpett** [comment]
How are you getting the metrics from wmi_exporter and node_exporter into the pushgateway? Again, this is not a configuration I've seen before, and it would be interesting to hear about how and why you have chosen this setup.
As for node_exporter working, I would suspect that the pushgateway and node_exporter versions you are using happen to be built with the same version of the library. Note that this is basically just luck, and upgrading one of them could possibly break the other.

**Comment by imluyuan** [comment]
VMS:
0）Install qemu-guset-agent and Linux and windows vm
1）Use crontab save to Scripts
2）Send Http request to wmi_exporter and save file to vm of localhosts

HyperVisor:
0）Use function of "guest-file-open" on HyperVisor to read vms  save files.（This is use HyperViso socket and VM COM port to communication）
 cmd="""virsh qemu-agent-command %s '{"execute":"guest-file-read","arguments":{"handle":%s,"count":10240000}}'""" % (vid,hd)

1）That data is base64，so you need use Python base64.b64decode function
2)  Push data to pushgateway

Last, sorry for my late reply, so busy because of the work
for reference only：
https://wiki.libvirt.org/page/Qemu_guest_agent

**Comment by carlpett** [comment]
Thanks. I'm afraid we aren't going to be able to spend time to support this scenario.
I would recommend letting Prometheus scrape the machines directly instead.
