### ISSUE TITLE
Double server names

### ISSUE THREAD

**Issue by Biomains** [martinlindhe/wmi_exporter#362]
It looks like wmi_exporter gives 2 names for same server in Grafana. With and without domain suffix.
In Promethues, targets are listed without domain suffix. 
In my prometheus.yml, I use without domain suffix.

Not sure why this is happening?

**Comment by carlpett** [comment]
Hi @Biomains,
I'm not sure what you mean, what labels are you seeing duplicated?
Also, what sort of service discovery are you using?

**Comment by Biomains** [comment]
I use static_config, named servers. 
If i look at the variable used in the the grafana dashboards, it's the label "Server".

**Comment by carlpett** [comment]
The exporter itself doesn't expose such a label. Do you perhaps have some relabelling config in your prometheus configuration?

**Comment by Biomains** [comment]
Yes, I see that the variable I gave you was for the Grafana dashboard only...
I am just starting to look at Promethues/Grafana, so there is no relabelling config, it standard/simple setup.

**Comment by Biomains** [comment]
For some reason the issue is gone today. It fixed itself during the night....closing the issue
