### ISSUE TITLE
agents with CloseWait state

### ISSUE THREAD

**Issue by fullenw1** [martinlindhe/wmi_exporter#363]
We have two 2012R2 servers with dozen of **CloseWait** connections.

On Prometheus' side the message is: `Get http://ComputerName:9182/metrics: context deadline exceeded`.

When I restart the **wmi_exporter** service it clears this list of TCP connections, but it starts piling up again.

I uninstalled and reinstalled the agent several times, but the behavior is the same.

There is only one process listening on this port and the owning process is **wmi_exporter**.

**Comment by carlpett** [comment]
Hey @fullenw1,
That's strange. Do you also have other Windows servers where this is **not** happening? Just to understand if this is a issue in your entire environment, or just a subset.
Does Prometheus successfully scrape the exporter until some point where it stops being able to connect?

What version of the exporter and Prometheus are you using? Do you have any reverse proxy or something between Prometheus and the exporter?

**Comment by martinlindhe** [comment]
The error `context deadline exceeded` by itself is prometheus, and it simply means the scrape took more time than the configured scrape timeout. So what is the value of your scrape timeout for wmi_exporter, and what happens if you double it?

**Comment by fullenw1** [comment]
> Do you also have other Windows servers where this is **not** happening?
It happens on 2 servers of 187.

> Does Prometheus successfully scrape the exporter until some point where it stops being able to connect?
No it scrapes nothing

> What version of the exporter and Prometheus are you using?
2.11

> Do you have any reverse proxy or something between Prometheus and the exporter?
No

> what is the value of your scrape timeout for wmi_exporter
2 minutes

> what happens if you double it?
Not tested

> how long does curl http://your-server:9182/metrics take ?
It just times out after 100 seconds and remains in the CloseWait state on the server with the agent.

**Comment by carlpett** [comment]
>>Does Prometheus successfully scrape the exporter until some point where it stops being able to connect?
>
>No it scrapes nothing

Curious. So I understand correctly it doesn't even work for a short while when you start it fresh?

Does WMI itself seem to work if you check with Powershell? Something like `gwmi Win32_PerfRawData_PerfOS_Processor`?

**Comment by fullenw1** [comment]
That's interesting!
Bot are retrurning the same error message after 23 seconds for the first one and nearly 7 minutes for the second one:

`gwmi : Invalid query "select * from Win32_PerfRawData_PerfOS_Processor"
    + CategoryInfo          : InvalidArgument: (:) [Get-WmiObject], ManagementException
    + FullyQualifiedErrorId : GetWMIManagementException,Microsoft.PowerShell.Commands.GetWmiObjectCommand`

I guess we have to rebuild performance counters on those two servers :-)

**Comment by fullenw1** [comment]
Here is what fixed the issue:

1. Rebuild performance counters with this document:
[How to manually rebuild Performance Counters for Windows Server 2008 64bit or Windows Server 2008 R2 systems (Microsoft Support)](https://support.microsoft.com/en-ca/help/2554336/how-to-manually-rebuild-performance-counters-for-windows-server-2008-6)
2. Reinstall Wmi_Exporter

Thanks for leading me to the solution!

**Comment by carlpett** [comment]
Thanks for documenting the solution! :tada:

**Comment by fullenw1** [comment]
I had to do this again a few times, like if wmi_exporter is breaking WMI under some circumstances...

For information, based on the official documentation above, I made a little script to repair WMI:

`Install-Module -Name PSSoftware`

`Get-InstalledSoftware 'wmi exporter'| ForEach-Object -Process {Uninstall-WindowsInstallerPackageWithMsiexec -Guid $PSItem.GUID -Verbose}`

`Start-Sleep -Seconds 2`

`Set-Location -Path 'C:\windows\System32' -Verbose`

`lodctr /R`

`Set-Location -Path 'C:\windows\sysWOW64' -Verbose`

`lodctr /R`

`winmgmt.exe /RESYNCPERF`

`Start-Sleep -Seconds 2`

`Restart-Service -DisplayName 'Performance Logs & Alerts' -Force -Verbose`

`Restart-Service -DisplayName 'Windows Management Instrumentation' -Force -Verbose`

`#Reinstall WMI EXPORTER here`
