### ISSUE TITLE
building locally

### ISSUE THREAD

**Issue by Drewster727** [martinlindhe/wmi_exporter#365]
I believe I have everything needed to build this project locally (go, go libs, promu, gcc, etc...).
However, building seems to want to pull code down from github everytime as opposed to building in my local directory that I've already forked/cloned from github.
Is there any way to simply run a `make build` that does not pull from github? I had assumed I could edit the .promu.yml file for this, but it doesn't seem to be very straightforward to do.

When running `make build` (or `promu build -v`) I can see the following go build command is executed:
```
go build 
-o wmi_exporter.exe 
-ldflags 
-X github.com/martinlindhe/wmi_exporter/vendor/github.com/prometheus/common/version.Version= 
-X github.com/martinlindhe/wmi_exporter/vendor/github.com/prometheus/common/version.Revision=3900504504b7a5392d8b291ffd1ed4714f0898aa 
-X github.com/martinlindhe/wmi_exporter/vendor/github.com/prometheus/common/version.Branch=master 
-X github.com/martinlindhe/wmi_exporter/vendor/github.com/prometheus/common/version.BuildUser=<user_redacted>@<host_redacted> 
-X github.com/martinlindhe/wmi_exporter/vendor/github.com/prometheus/common/version.BuildDate=20190720-18:22:25  
-extldflags '-static' github.com/martinlindhe/wmi_exporter
```

I can swap out martin's name for mine so it refers to my fork repo, but it blows up on build:
```
PS C:\gopath\src\wmi_exporter> go build -o wmi_exporter.exe -v
_/C_/gopath/src/wmi_exporter
# _/C_/gopath/src/wmi_exporter
.\exporter.go:101:18: cannot use ch (type chan<- "github.com/prometheus/client_golang/prometheus".Metric) as type chan<- "github.com/Drewster727/wmi_exporter/vendor/github.com/prometheus/client_golang/prometheus".Metric in argument to c.Collect
```

I'm assuming I need to modify exporter.go and remove the github.com ref to martin's repo and use the local folder, something like:
```
import (
	"fmt"
	"net/http"
	"sort"
	"strings"
	"sync"
	"time"
	"golang.org/x/sys/windows/svc"
	"./collector" <---
```

When I do that, it appears to build locally and generate an executable, but it doesn't seem to work (debug logging doesn't provide any details):
```
An error has occurred while serving metrics:

collected metric process_start_time_seconds counter:<value:1.56365204e+09 >  should be a Gauge
```

If I could get some instructions on how to properly edit/build/debug locally once I've forked the repo, that'd be super helpful. I'm a GO rookie.

Thanks,
Drew
Windows 10 Build 17134

**Comment by martinlindhe** [comment]
See Usage section in readme for how to build locally. Expect the go tool to download source from github, it's designed to do that.

https://github.com/martinlindhe/wmi_exporter#usage

**Comment by carlpett** [comment]
@Drewster727 Go doesn't play very nice with picking your own checkout path. The painless way here is to checkout into `$GOPATH\src\github.com\martinlindhe\wmi_exporter`, and then adding your fork as an extra remote on that repo:
`git remote add fork git@github.com:Drewster727/wmi_exporter`
This lets you build and develop without having to rewrite import paths.

**Comment by carlpett** [comment]
Since you've submitted a PR, I guess this worked :) I'll close this, let me know if there's still anything unclear
