### ISSUE TITLE
please document wmi_system_threads gauge

### ISSUE THREAD

**Issue by GETandSELECT** [martinlindhe/wmi_exporter#367]
Hi

I searched this repo for `wmi_system_threads`

and found only

> `wmi_system_threads` | _Not yet documented_ | gauge | None

I have a dashboard that uses this metric:

![Screenshot 2019-07-22 at 07 46 02](https://user-images.githubusercontent.com/10598483/61609941-eecc2800-ac57-11e9-9c17-aca8db1b3342.png)

Can you add 2-3 lines of docs about this metric? Or reference the official Microsoft term?

Thanks

**Comment by carlpett** [comment]
Hi @GETandSELECT,
Good point. We're aware that docs are still lacking. Sadly though, we have limited time to work on the exporter, so I cannot promise any timeline when we could fix this particular item. Pull requests with improvements are very welcome though, if you'd like to contribute!
Also, note that when we have found official Microsoft docs for the WMI classes we use, we try to link them from the collector doc page (https://github.com/martinlindhe/wmi_exporter/blob/master/docs/collector.system.md in this case). The `Classes` listing is linked.
