### ISSUE TITLE
Question about adding collectors to wmi_exporter

### ISSUE THREAD

**Issue by Biomains** [martinlindhe/wmi_exporter#368]
When i want to expose metrics that is not default, using --collectors.enabled, do i also have to add the default ones? Or are they added anyways?

**Comment by carlpett** [comment]
Hi @Biomains,
The list given is the exact list used, so if you do `--collectors.enabled iis` for example, you'll _only_ get the iis collector. We do have a placeholder you can use, `[defaults]`, which will be expanded to all the default collectors (convenient for making sure you don't need to update a hardcoded list if you upgrade to a newer version of the exporter).
So for example `--collectors.enabled [defaults],iis` would get you all the default collectors, and the iis collector.

**Comment by carlpett** [comment]
Assuming the thumbsup means it worked :) Closing, post an update if there's anything else to clarify
