### ISSUE TITLE
Thermalzone Issue

### ISSUE THREAD

**Issue by Gitihub2019** [martinlindhe/wmi_exporter#373]
Hello,

i want to start the wmi exporter with this parameters: os,iis. and thermalzone.
But the installation stop it at the thermalzone parameter.
`msiexec /i C:\Users\chardamek\Desktop\wmi_exporter ENABLED_COLLECTORS=os,iis,thermalzone`

![1](https://user-images.githubusercontent.com/53786477/62473731-ad806000-b7a1-11e9-8c57-5875d4e5db7f.PNG)

Best regards

**Comment by carlpett** [comment]
Hi @Gitihub2019,
The thermalzone collector hasn't been packed in a release yet. I'm hoping to do so tonight (European time) if all looks good.
As soon as that is done, just upgrade and it will be available!
