### ISSUE TITLE
Collection timed out warnings in Event Viewer

### ISSUE THREAD

**Issue by EHammer98** [martinlindhe/wmi_exporter#390]
I'am getting alot of warnings in Event Viewer from the wmi_exporter after upgrading to 0.8.1 (from 0.7.0, upgraded by removing it via Control Panel and installing the newer version)

Warning: Collection timed out, still waiting for [net os service system]

Image:
![image](https://user-images.githubusercontent.com/24757372/63782543-d224af00-c8eb-11e9-9cda-3bc025e140ee.png)

Does anyone else has the same problems?/Is there a fix for this issue?

**Comment by carlpett** [comment]
Hi @EHammer98,
Part of the 0.8 release was functionality to try to avoid missing the entire scrape if some collectors take unexpectedly long time, and this is what you are seeing the results of. Prometheus passes us how long it will wait for results before giving up, and we now try to return whatever data we managed to gather when that time is almost up. What is your scrapeTimeout configuration in Prometheus?
Also, previous to the update, did you see many "gaps" in the data in Prometheus? Is the server under heavy load?

**Comment by EHammer98** [comment]
@carlpett the scarpe timeout is the default 10s, scrape interval is changed to 5s.
The warnings are on all our servers.
I did have some "gaps" with <0.7.0 on a few servers which are mostly under heavy load.
On the worst, it was 1,5min. (1:30)

**Comment by carlpett** [comment]
Thanks! If you are scraping that frequently, you're probably scraping more often than WMI is able to keep up with. Are you seeing fewer gaps with 0.8?

**Comment by EHammer98** [comment]
@carlpett ah ok i see, i will try to slow it down a bit tomorrow (i am now not at the office).
I will also let you know of the gaps are different ( i don't know that at this moment)

**Comment by EHammer98** [comment]
@carlpett i slowed the scrape interval to 15s, time-out is still the default 10s.
The warnings on my Prometheus servers (where i also have WMI exporter running) are gone now, but my co-worker told me that it is till happening on the other servers (we did restart the WMI-exporter service), it did slow down a bit (about every 15s while it first was every 5s, it was about every 15min. on my Prometheus server).

I have increased it to 30s (scrape interval). I will let you know if it is gone now as soon as my co-worker reports back to me

**Comment by EHammer98** [comment]
I found out that now only 1 server is having these warnings. That's because the CPU is at 100% at a rate of about 15s.

So increasing to 15s was enough to stop it from the other servers, i will leave it now at 30s (from the last test), and figure something out to block the warnings from the WMI-exporter in Event Viewer.

But thanks for the help @carlpett !
