### ISSUE TITLE
v0.8.2 release does not include binaries

### ISSUE THREAD

**Issue by andrewmostello** [martinlindhe/wmi_exporter#395]
It appears as though the tagged v0.8.2 release does not include exe or msi installers as other releases have in the past. I use the msi installer link in the Chocolatey package scripts that I maintain. Will these be posted? Thanks

**Comment by carlpett** [comment]
Seems the build failed. Looking into it.

**Comment by carlpett** [comment]
Something seems to go wrong when it pulls the repo. I'm unable to log into the machine to see exactly what happens without pushing changes, and I'm not able to repro on any other commit.
I'm travelling today and tomorrow, so I don't have that much more time to look into this, so I made a 0.8.3 release instead, and the build+release worked :man_shrugging:

Any problems with not having the 0.8.2 version available?

**Comment by andrewmostello** [comment]
No, that's fine by me. I'll skip right ahead to 0.8.3. Thanks!
