### ISSUE TITLE
Make wmi_system_system_up_time format more Prometheus friendly

### ISSUE THREAD

**Issue by pskiwi** [martinlindhe/wmi_exporter#40]
The metric _wmi_system_system_up_time_ is exported as Pico-seconds since system-start.
To visualize it you have to use something like

`wmi_system_system_up_time{instance="$instance"}/1000000000000`

It would be more convenient to export the system start as Unix timestamp. See [Prometheus-Timestamp-Doc](https://prometheus.io/docs/practices/instrumentation/#timestamps-not-time-since).
This should result in a query like: 
`time() - wmi_system_system_up_time{instance="$instance"}`
Prometheus would also be able to better compress the time series.

**Comment by brian-brazil** [comment]
We should only expose it as a unix timestamp if the source value is an absolute time. If it's the time since boot, then we have to export that instead to avoid confusion

It should be in seconds in any case.

> Prometheus would also be able to better compress the time series.

It should compress it pretty well already.

**Comment by martinlindhe** [comment]
I'm looking at this now. One issue is the WMI call is undocumented (of microsoft) as far as I could google. 

I don't see wmi_system_system_up_time increasing at all on my test system (win7).

@pskiwi could you confirm you really are seeing this value increasing?

Can't find any official docs on this wmi call anymore, but found this archived link:
https://web.archive.org/web/20050830140516/http://msdn.microsoft.com/library/en-us/wmisdk/wmi/win32_perfrawdata_perfos_system.asp

```
SystemUpTime
    Data type: uint64
    Access type: Read-only
    Qualifiers: DisplayName("System Up Time"), CounterType(807666944), DefaultScale(-5), PerfDetail(100)

    Elapsed time (in seconds) that the computer has been running after it was last started. This property displays the difference between the start time and the current time.
```

**Comment by pskiwi** [comment]
You are right, the raw value seems to be constant. It was a lucky coincidence, that the value was correct for me.

In case you didn't know, you could query the values via Power-Shell:
`Get-WmiObject -query "SELECT * FROM Win32_PerfRawData_PerfOS_System";`

the real uptime value seems to be available from the formatted data:
`Get-WmiObject -query "SELECT * FROM Win32_PerfFormattedData_PerfOS_System";`

Maybe you could use this value.

**Comment by martinlindhe** [comment]
Thanks for your input! I'll have a look at using the formatted data instead.

**Comment by martinlindhe** [comment]
@pskiwi I made use of the value from Win32_PerfFormattedData_PerfOS_System which does look more as "seconds since boot" than the first value. It is currently awaiting review at https://github.com/martinlindhe/wmi_exporter/pull/41

In hindsight I suspect the unformatted value might be a timestamp of system startup rather than a "seconds since boot" which the old msdn docs indicates.

**Comment by brian-brazil** [comment]
What the docs say if what you get once you perform the documented calculations, so lots of rates etc are actually counters - which is just what we need for Prometheus. We should generally be using the raw data.

**Comment by martinlindhe** [comment]
@brian-brazil i reworked the patch, now it is an increasing counter with actual seconds since start up.

**Comment by brian-brazil** [comment]
Just to clarify, what is the raw value that is being exposed?

**Comment by martinlindhe** [comment]
The raw value is a timestamp, it seems:
SystemUpTime

We now calc uptime since start with:

(Timestamp_Object(current time) - SystemUpTime(startup time)) / Frequency_Object (1 nanosec)

If we just want a timestamp of time start, we could instead:

(Timestamp_Object(current time) / Frequency_Object (1 nanosec)

**Comment by brian-brazil** [comment]
Yes, exporting it as a timestamp is best if that's the way it is exported.

If someone wants uptime they can do `time() - metric` on the Prometheus end, and reboots can be counted  with `changes(metric[1h])`.

**Comment by martinlindhe** [comment]
Okay, new patch incoming!

**Comment by martinlindhe** [comment]
Reworked. Now it converts the Windows timestamp into a unix timestamp.
Should we use another type than gauge now?

**Comment by martinlindhe** [comment]
@pskiwi Resolved the issue. Exposed are now a timestamp from when system booted. You can then caluclate a "time since boot" with `
time() - wmi_system_system_up_time{instance="$instance"}` as you suggested in first post. Thanks for reporting this!

**Comment by sunilmchaudhari** [comment]
Hi,
On which version you fixed this issue.
I am facing problem in displaying "last booted time" for windows. 
I am showing it as wmi_system_system_up_time{instance=~"$wmi:$port",job=~"$job"}
"wmi_system_system_up_time" is the value in milliseconds.  It gives me 20.4 days but actually system was booted 6 days back.
Please help resolving this.

**Comment by sunilmchaudhari** [comment]
Hi @martinlindhe ,
time() gives me 17.7 days
and time() - wmi_system_system_up_time{instance=~"$wmi:$port"}   gives me -2.7 days.  
Why the starttime is in minus?

**Comment by martinlindhe** [comment]
And what does `time() - wmi_system_system_up_time{instance="$instance"}` give you?

**Comment by sunilmchaudhari** [comment]
That gives me no-values. 
I have different fields in my dashboard.  I have server instead of instance. 
time() - wmi_system_system_up_time{instance="$server"}
This gives me -2.2 days.

**Comment by oktospeaker** [comment]
(time() - wmi_system_system_up_time{instance="$instance"}) / 86400
