### ISSUE TITLE
How to Enable New Collectors

### ISSUE THREAD

**Issue by captainhistory** [martinlindhe/wmi_exporter#404]
I have installed wmi exporter and can't seem to enable new collectors. There's very little documentation and I can't seem to get a good answer scrolling through here or searching online. In the exporter.go file I updated defaultCollectors to pull logon and memory metrics. 

const (
	defaultCollectors            = "cpu,cs,logical_disk,net,os,service,system,textfile,logon,memory"
	defaultCollectorsPlaceholder = "[defaults]"
	serviceName                  = "wmi_exporter"

When I run the .exe those metrics are not shown under my enabled collectors. What are the actual steps to enable these non-default collectors?

**Comment by breed808** [comment]
If you're running the exe you can use the `--collectors.enabled` flag. From the project README:

`.\wmi_exporter.exe --collectors.enabled "service" --collector.service.services-where "Name='wmi_exporter'"`

**Comment by captainhistory** [comment]
How do I do that? Through something like powershell or the cmd line? I see in the documentation some stuff regarding the misexec, but I can't utilize that as my company won't allow the use of the msi file due to firewall security. 

Also, I do have all the files from the distro on my PC, and I can set it up to run as a service instead of from the .exe. If I run it as a service, will it pull the configuration settings from the exporter.go file?

**Comment by breed808** [comment]
Yes, you can run the commands in Powershell or CMD. You'll need to navigate to the directory containing the exe file before running them ***or*** run the command with the full path to the executable. E.G. `C:\Users\captainhistory\Downloads\wmi_exporter-0.8.3-amd64.exe --collectors.enabled=cpu,memory,net,os`

You don't need all the project files on your PC, only the executable. Whether run manually or as a service, the executable will run with the default configuration as specified in `exporter.go`. These settings can be changed with run-time flags, such as `--collectors.enabled` and  `--telemetry.addr`.

**Comment by martinlindhe** [comment]
@captainhistory please see https://github.com/martinlindhe/wmi_exporter#installation

using ENABLED_COLLECTORS you can customize what collectors to enable during installation.

How to specify enabled collectors is documented under https://github.com/martinlindhe/wmi_exporter#examples

**Comment by alekssako** [comment]
You can install via powershell using `msiexec`
msiexec /i C:\path\to\msi\wmi_exporter-x.x.x-amd64.msi ENABLED_COLLECTORS="cpu, cs, logical_disk, memory, net, os, ect...." LISTEN_PORT="9182"

**Comment by xuanyuanaosheng** [comment]
I have installed wmi exporter using the command:
`
msiexec /i wmi_exporter-0.9.0-amd64.msi ENABLED_COLLECTORS="ad,cpu,cs,dns,iis,logical_disk,logon,memory,net,os,service,system,tcp,textfile" `
 and the wmi_exporter is run as **windows service**,  

The service start command is below
`
"C:\Program Files\wmi_exporter\wmi_exporter.exe" --log.format logger:eventlog?name=wmi_exporter --collectors.enabled ad,cpu,cs,dns,iis,logical_disk,logon,memory,net,os,service,system,tcp,textfile --telemetry.addr :9182`

Now I want to change the start command to 

`
"C:\Program Files\wmi_exporter\wmi_exporter.exe" --log.format logger:eventlog?name=wmi_exporter --collectors.enabled cpu,cs,logical_disk,logon,memory,net,os,service,system,tcp,textfile --telemetry.addr :9182`.

**Comment by xuanyuanaosheng** [comment]
https://github.com/martinlindhe/wmi_exporter/issues/440

**Comment by carlpett** [comment]
I understand this as your problem being solved in #440? I'll close this, then.
