### ISSUE TITLE
How can I stop every iis reset to reset counter?

### ISSUE THREAD

**Issue by espekkaya** [martinlindhe/wmi_exporter#416]
Hello,
I have had a problem. When every iis reset, the counter is reseted. How can I stop every iis reset to reset counter? By the way I'm using wmi_iis_requests_total method.

Thank you.

**Comment by carlpett** [comment]
Hi,
You cannot prevent this. How are you using the metrics that causes it to be a problem? `rate` and other functions should handle the resets correctly.

**Comment by espekkaya** [comment]
Hello @carlpett ,
The problem is that current counter reset and start zero. Ok I will use rate functions to correct .

Thank you for your showing the way.
