### ISSUE TITLE
How to monitor the memory usage of each process in windows?

### ISSUE THREAD

**Issue by aricamf** [martinlindhe/wmi_exporter#423]
I've already installed/configured the wmi_exporter on my windows VMs but...how can I monitor the memory usage of each process on Grafana?

I've already created the data source in Grafana and connected with my wmi_exporter.

Thanks

**Comment by martinlindhe** [comment]
Hello @aricamf 
You can use the process collector to get per-process memory usage.

Please see the documentation for the memory collector here: https://github.com/martinlindhe/wmi_exporter/blob/master/docs/collector.process.md

**Comment by aricamf** [comment]
AH! Yes, thanks so much!@martinlindhe!
