### ISSUE TITLE
Trying to figure out how to pull currently logged on user metrics.

### ISSUE THREAD

**Issue by win-admin-85** [martinlindhe/wmi_exporter#428]
Is there a way to pull usernames of the currently logged on users along with timestamp? I can easily pull counts of logon sessions but can't seem to find a way to pull actual usernames.  I would like to be able to see the trends of user activity on servers.

**Comment by carlpett** [comment]
Hi @win-admin-85,
In short, no. That usecase is not a very good fit for metrics-based monitoring, and I'd recommend looking into event-based systems instead. Some form of centralized logging would likely get you quite far, for example.
