### ISSUE TITLE
Feature: Active Directory

### ISSUE THREAD

**Issue by carlpett** [martinlindhe/wmi_exporter#43]
Already in progress, using the `Win32_PerfRawData_DirectoryServices_DirectoryServices` counters. This will just cover the "Active Directory - Directory Services" part of the Active Directory, not the web services etc (there are over 150 counters exposed by this class alone...)

**Comment by carlpett** [comment]
The majority of the work is to map counters to metrics and labels. I've put my current status here: https://gist.github.com/carlpett/53083648d5f08a8d06a7e4f8e25aae25. Grateful for any input! 

The documentation is pretty much non-existent, sadly. Still haven't found of what an "ATQ" is...

**Comment by martinlindhe** [comment]
ATQ = Asynchronous Thread Queue, a type of performance counters
source: https://blogs.technet.microsoft.com/askds/2014/10/24/understanding-atq-performance-counters-yet-another-twist-in-the-world-of-tlas/
