### ISSUE TITLE
OS Name, build, Version, Architecture, Hostname, Domain, Domain role Info missing

### ISSUE THREAD

**Issue by bmkrkolli** [martinlindhe/wmi_exporter#430]
OS Name, Build, Version, Architecture, Hostname, Domain, Domain Role, System Drive Info missing in the metrics.. 
Including this info in metrics will help alert managers to capture this info in the alert.
And if there is any automation layer on top of alerting system then it also help automation to pick up host info and variables dynamically and easily.

**Comment by carlpett** [comment]
Hi @bmkrkolli,
Part of this, OS Name and Build/Version, is adressed in #413. Hostname could be provided by your Prometheus discovery, which may be sufficient?
The domain roles I'm a bit sceptical of adding, what use-cases do you see for it? You'll likely know it already by which collectors you are enabling?
Architecture and System drive are also unclear to me how you'd use them for alert routing? I don't see Prometheus as an inventory management system, which is the only case I can see here?

**Comment by bmkrkolli** [comment]
Example: If Windows 2012 Server x64 Architecture edition has C: drive full situation.. An alert is fired and mapped to an automatic cleanup script/ansible playbook/chef cookbook etc .. to perform cleanup..

The automated script/ansible playbook/chef cookbook needs the values like which drive letter to cleanup and based on architecture, they can easily switch to set of folders, paths that need to be cleaned up to release some space.. Based on domain role which logs and directories can be cleaned up and also run the compatible commands..

**Comment by bmkrkolli** [comment]
Thanks for pointing to #413.. I got what I am looking for..

**Comment by carlpett** [comment]
Nice to hear that PR was sufficient!
