### ISSUE TITLE
FSRM quota collector (following :issue #98)

### ISSUE THREAD

**Issue by nwies** [martinlindhe/wmi_exporter#431]
Hello,
I'm trying to define a collector for FSRMQuota (following :issue #98). for now I testing on a Windows Server 2012 R2.
I was able to generate a collector with the collector-generator, with tweaking it :
I add the nameSpace to "-NameSpace root/microsoft/windows/fsrm"
But I have some troubles.
I have a "invalid class" error. I think the error is due to the "MSFT_FSRMQuota" class is not under "root/cimv2" (as the last collector created thermalzone) but under "root/microsoft/windows/fsrm/msft_fsrmquota"
https://wutils.com/wmi/root/microsoft/windows/fsrm/msft_fsrmquota

on the ".go" file how can I define the "main class" ?

Please find the draft collector I'm working on.
[msft_fsrmquota.go.txt](https://github.com/martinlindhe/wmi_exporter/files/3831306/msft_fsrmquota.go.txt)

Thanks for your help

**Comment by carlpett** [comment]
Hi @nwies,
Thanks for looking at this! To query in another namespace, simply change `wmi.Query(q, &dst)` on line 123 to `wmi.QueryNamespace(q, &dst, "namespace here")`.

**Comment by nwies** [comment]
Hello,

thanks for the feedback.

I modified the line n°123 :

From
if err := wmi.Query(q, &dst, "); err != nil {
to
if err := wmi.Query(q, &dst, "root/microsoft/windows/fsrm/msft_fsrmquota"); err != nil {

But now, I have another problem:
"←[31mERRO←[0m[0026] collector msft_fsrmquota failed after 4.967773s: Exception occurred. (The RPC server is unavailable. )  ←[31msource←[0m="exporter.go:215"
←[31mERRO←[0m[0031] failed collecting msft_fsrmquota metrics:<nil> Exception occurred. (The RPC server is unavailable. )  ←[31msource←[0m="msft_fsrmquota.go:98"


I'm running the exporter on an administrator cmd prompt.

another idea ?

**Comment by carlpett** [comment]
Did you mean `wmi.QueryNamespace(q, &dst, "root/microsoft/windows/fsrm/msft_fsrmquota")`, or actually `wmi.Query(q, &dst, "root/microsoft/windows/fsrm/msft_fsrmquota")`?
They do not mean the same thing. In the latter case, I also get RPC error unavailable.

**Comment by nwies** [comment]
Thanks.

I just see my mistake.

It's working now. 
I will make some updates on the description (string/uint64/...) an I will send a pull request.

thanks

**Comment by carlpett** [comment]
Nice 😄 Looking forward to the PR!
