### ISSUE TITLE
Is there a counter for per-process GDI objects?

### ISSUE THREAD

**Issue by Mario-Hofstaetter** [martinlindhe/wmi_exporter#433]
Is there a counter available for per-process GDI-objects? Since Threads and Handles is already present?

We are currently hunting a memory leak regading that so it would be of great help.
I couldn't find anything to "gdi" in this repository.

Thank you && BR

**Comment by carlpett** [comment]
Hi @Mario-Hofstaetter,
From a quick look around the internet, this does not seem to be exposed via WMI or performance counters. I did find the tool [GDIView](http://www.nirsoft.net/utils/gdi_handles.html) which has a commandline interface to dump the required data however. You could combine this with the [textfile collector](https://github.com/martinlindhe/wmi_exporter/blob/master/docs/collector.textfile.md) to get this into the exporter and then Prometheus.

**Comment by Mario-Hofstaetter** [comment]
Thanks for the idea, will try to look into that.
