### ISSUE TITLE
Wmi_Exporter 0.9.0 doesn't start on Windows 2008R2

### ISSUE THREAD

**Issue by basift** [martinlindhe/wmi_exporter#435]
Hello, wmi_exporter version 0.9.0 doesn't start on Windows 2008R2 in my environment.
It works find on later versions (20012 and 2016).
I was trying to downgrade to the version 0.8.3 but there's no luck as well.
The main problem I don't see any logs which explains what happens, it just freezes on the "starting server" stage.
Please assist
![image](https://user-images.githubusercontent.com/57709357/68757066-f737dc80-0613-11ea-8e27-b8404b920d60.png)

**Comment by carlpett** [comment]
Hi @basift,
What are you expecting to happen after the "Starting server" log entry? What happens if you try to access localhost:9182?

**Comment by basift** [comment]
Hi @carlpett,

Thanks for your answer.
I'm sorry there was a firewall issue, so it works fine on localhost.
