### ISSUE TITLE
Wmi_exporter issue

### ISSUE THREAD

**Issue by veeraprathap12** [martinlindhe/wmi_exporter#439]
we have a problem to run a wmi_exporter on Prometheus.
1)we installed wmi_exporter on laptop
2)we set target IP address where wmi_exporter. But, it posting error context deadline exceeded
![Capture](https://user-images.githubusercontent.com/57307102/68916911-a9af9280-072d-11ea-93c8-9c8219606abc.PNG)

**Comment by carlpett** [comment]
Hi @veeraprathap12,
This type of issue is most often caused by network connectivity issues, such as firewalls. Have you made sure all relevant rules are in place?

**Comment by veeraprathap12** [comment]
thank you so much
