### ISSUE TITLE
Enable collector in addition to defafults

### ISSUE THREAD

**Issue by alens** [martinlindhe/wmi_exporter#44]
is there a option, to install all the default collectors + the IIS as the optional ?

**Comment by carlpett** [comment]
@alens Unfortunately not yet. The installed was modelled on how node_exporter works, but I want to fix this.

**Comment by alens** [comment]
so i need to pass all wanted collectors in the ENABLED_COLLECTORS=os,iis,cpu...  ?

**Comment by carlpett** [comment]
Presently yes, I'm afraid.
