### ISSUE TITLE
How to Enable New Collectors

### ISSUE THREAD

**Issue by veeraprathap12** [martinlindhe/wmi_exporter#440]
For enabling the collectors we used this command I tried to execute this command is executed but I am unable to find TCP metrics on Prometheus. please help me out is there any alternate way to enable this collector. 
![test22](https://user-images.githubusercontent.com/57307102/69393495-ee43ac80-0c9e-11ea-8de4-64079c1c2055.PNG)

when I use to run .exe file it getting metrics of TCP by using the following command. 
.\wmi_exporter-0.9.0-amd64.exe --collectors.enabled "service" --collector.service.services-where "Name='wmi_exporter'"
Here getting metrics but, I am unable to access those metrics into Prometheus. 

when I use to run .msi file unable to get metrics of TCP by using the following command. 
.\wmi_exporter-0.9.0-amd64.msi --collectors.enabled "service" --collector.service.services-where "Name='wmi_exporter'"
even I tried with this command
.\wmi_exporter-0.9.0-amd64.msi  ENABLED_COLLECTORS"service" --collector.service.services-where "Name='wmi_exporter'"

msiexec /i C:\path\to\msi\wmi_exporter.msi ENABLED_COLLECTORS="service1, service2" LISTEN_PORT="9182"

**Comment by martinlindhe** [comment]
Hi!

The service collector is called "service".
You can find installation examples in the README

https://github.com/martinlindhe/wmi_exporter#installation

**Comment by veeraprathap12** [comment]
Basically, we need to enable collectors. for enabling we are using this command still executing but we unable to see the metrics

msiexec /i wmi_exporter-0.9.0-amd64.msi ENABLED_COLLECTORS=os,tcp LISTEN_PORT=9182

**Comment by maelstrom256** [comment]
@veeraprathap12, basically, you can use `sc` utility, in admin shell, to modify service settings.
Run `sc qc wmi_exporter`, to get service info:
```
C:\Windows\system32>sc qc wmi_exporter
[SC] QueryServiceConfig SUCCESS

SERVICE_NAME: wmi_exporter
        TYPE               : 10  WIN32_OWN_PROCESS
        START_TYPE         : 2   AUTO_START
        ERROR_CONTROL      : 1   NORMAL
        BINARY_PATH_NAME   : "C:\Program Files\wmi_exporter\wmi_exporter.exe" --log.format logger:eventlog?name=wmi_exporter  --telemetry.addr :9182
        LOAD_ORDER_GROUP   :
        TAG                : 0
        DISPLAY_NAME       : WMI exporter
        DEPENDENCIES       :
        SERVICE_START_NAME : LocalSystem
```
Set binPath to manage exe name and parameters to defaults (note: launch string may change in future, use this note like example only):
```
sc config wmi_exporter binPath="\"C:\Program Files\wmi_exporter\wmi_exporter.exe\" --log.format logger:eventlog?name=wmi_exporter  --telemetry.addr :9182"
```
Or customize collectors and set conditions, just like this:
```
sc config wmi_exporter binPath="\"C:\Program Files\wmi_exporter\wmi_exporter.exe\" --collectors.enabled \"cpu,cs,iis,logical_disk,memory,mssql,net,os,service,textfile\" --collector.textfile.directory c:\metrics --collector.service.services-where \"Name LIKE 'mssql%' OR Name='ftpsvc' OR Name='w3svc'\" --log.format logger:eventlog?name=wmi_exporter --telemetry.addr 192.168.0.1:9182"
```
using `\"` instead of ordinary `"`.

**Comment by xuanyuanaosheng** [comment]
@maelstrom256  In Windows Server 2012, I test your command, But failed.


![image](https://user-images.githubusercontent.com/4197714/71150823-620cb100-226d-11ea-8afb-7a10fd3ea2f4.png)

**Comment by maelstrom256** [comment]
Just do not use powershell, use cmd. Powershell always unescaping escaped quotes and break things to the bones. I have no found any working way to use it outside piping objects.
Mine one:
```cmd
C:\Windows\system32>sc config wmi_exporter binPath="\"C:\Program Files\wmi_exporter\wmi_exporter.exe\" --collectors.enabled \"cpu,cs,iis,logical_disk,memory,mssql,net,os,service,textfile\" --collector.textfile.directory c:\metrics --collector.service.services-where \"Name LIKE 'mssql%' OR Name='ftpsvc' OR Name='w3svc'\" --log.format logger:eventlog?name=wmi_exporter --telemetry.addr ip:port"
[SC] ChangeServiceConfig SUCCESS

C:\Windows\system32>net stop wmi_exporter && net start wmi_exporter
The WMI exporter service is stopping.
The WMI exporter service was stopped successfully.

The WMI exporter service is starting.
The WMI exporter service was started successfully.```

**Comment by xuanyuanaosheng** [comment]
@maelstrom256  It works. Thanks

**Comment by carlpett** [comment]
This seems to be resolved, thanks everyone for helping out!
