### ISSUE TITLE
Proper use of volumeBlacklistPattern?

### ISSUE THREAD

**Issue by exceedio** [martinlindhe/wmi_exporter#45]
I'm curious about the the proper use of volumeBlacklistPattern or examples when needing to exclude volumes that begin with "HarddiskVolume" (e.g. HarddiskVolume1, HarddiskVolume108, etc.) in the logical disk collector.

This is great work Martin.

**Comment by carlpett** [comment]
Hi! 
It should be sufficient to set the blacklist to `HarddiskVolume.+`, is that not working?
Are you seeing those volumes with disks not mounted anywhere?

**Comment by exceedio** [comment]
Working perfectly.  I didn't notice the correct command line argument format.
