### ISSUE TITLE
wmi_cpu_time_total abnormal

### ISSUE THREAD

**Issue by for-mat** [martinlindhe/wmi_exporter#456]
![image](https://user-images.githubusercontent.com/43637488/72900410-c934ee00-3d62-11ea-95d1-b104eb441eaf.png)
When I got the CPU information, I found that some core's values >  1.  I wonder why. This allows me to get CPU usage when part of the value is <0 .

**Comment by for-mat** [comment]
![image](https://user-images.githubusercontent.com/43637488/72900635-3c3e6480-3d63-11ea-9c7d-35c0a5e7d578.png)

**Comment by for-mat** [comment]
irate(wmi_cpu_time_total{instance=~"10.222.60.12:9182",mode="idle"}[1m])
{core="0,11",instance="10.222.60.12:9182",job="pro_user",mode="idle"} | 1.0004864133894444
-- | --

**Comment by carlpett** [comment]
Hi @for-mat,
What is your scrape interval? Are all scrapes successful, and how long time do they take? (check the `up{instance="10.222.60.12:9182",job="pro_user"}` and `scrape_duration_seconds{instance="10.222.60.12:9182",job="pro_user"}` over the last few minutes)

**Comment by for-mat** [comment]
> 嗨@ for-mat，
> 您的抓取间隔是多少？所有刮擦都成功吗？需要多长时间？（检查`up{instance="10.222.60.12:9182",job="pro_user"}`和`scrape_duration_seconds{instance="10.222.60.12:9182",job="pro_user"}`在最近几分钟内）

![image](https://user-images.githubusercontent.com/43637488/79834825-49113980-83e0-11ea-9db2-b4edbf611ae2.png)
![image](https://user-images.githubusercontent.com/43637488/79834856-575f5580-83e0-11ea-83b9-1beb777b9285.png)
![image](https://user-images.githubusercontent.com/43637488/79834927-6f36d980-83e0-11ea-9743-cc1c891ad3d1.png)

**Comment by for-mat** [comment]
> 嗨@ for-mat，
> 您的抓取间隔是多少？所有刮擦都成功吗？需要多长时间？（检查`up{instance="10.222.60.12:9182",job="pro_user"}`和`scrape_duration_seconds{instance="10.222.60.12:9182",job="pro_user"}`在最近几分钟内）

https://github.com/martinlindhe/wmi_exporter/issues/259#issuecomment-490507074
Here I see the same thing，I tried this sql but failed，What should I do
```
1
  -
avg by (instance) (
  irate(wmi_cpu_time_total{mode="idle", instance="$server"}[5m])
    /
  sum by(instance) (irate(wmi_cpu_time_total{instance="$server"}[5m]))
)
```

**Comment by for-mat** [comment]
1
  -
sum by (instance) (
  irate(wmi_cpu_time_total{mode="idle", instance="$server"}[5m])
    /
  sum by(instance) (irate(wmi_cpu_time_total{instance="$server"}[5m]))
)

**Comment by for-mat** [comment]
resolved
