### ISSUE TITLE
wmi exporter 0.9.0 error Couldn't load collectors: collector 'logical_disknet' not available

### ISSUE THREAD

**Issue by hendraw72** [martinlindhe/wmi_exporter#465]
I am trying to install wmi exporter version 0.9.0 on HP Z820 server running Windows Server 2016.
I run an elevated command prompt and here is the command I use:
msiexec /i C:\Temp\wmi_exporter-0.9.0-amd64.msi ENABLED_COLLECTORS="hyperv,memory,cpu,cs,logical_disknet,os,service,system,tcp,textfile"

The service installed fine but it's can't start, it will try to start and stopped continuously

If I checked event viewer I see this error message:
Event ID 102: Couldn't load collectors: collector 'logical_disknet' not available

Any help is appreciated

**Comment by johi12** [comment]
You’re missing a comma between logical_disk and net.

fre 14 feb. 2020 kl. 20:18 skrev hendraw72 <notifications@github.com>:

**Comment by hendraw72** [comment]
Thanks, that was it!
