### ISSUE TITLE
wmi_process_private_bytes not showing correct data

### ISSUE THREAD

**Issue by aneslozo** [martinlindhe/wmi_exporter#467]
Hi, 

I am using wmi_exporter with process collector on for specific processes. I am tracking one java process which is using 25GB RAM memory (see this directly on Windows) but in my Prometheus and Grafana dashboard, I have information that my process use only 4GB RAM memory which is not correct of course. 

wmi_process_private_bytes{nodename="$nodename"}
wmi_process_virtual_bytes{nodename="$nodename"}

This is biggest value that I get `4294967295` even try for some other process. 

I didn't find that someone reported this issue or I am doing something wrong. I would appreciate some help here. Once set up everything on my side will update the documentation (make PR) with some info for process collector as I saw it is missing. 

Thanks.

**Comment by martinlindhe** [comment]
Thanks for reporting this. Looks like we may be losing precision somewhere.

Noting that 4294967295 is the max value a unsigned 32-bit value can hold.

**Comment by aneslozo** [comment]
Yes, that is correct, but Windows used uint64 and if I saw correctly in collector you are using float64 which should work but will let you check this more in detail. 

I am using Prometheus operator for k8s and mostly default setup with some custom/additional scrape configs. 

This server where the process is running is Windows Server 2019 Datacenter 64-bit and have 31GB RAM memory. 

I am using wmi_exporter-0.9.0 version and I turn on process collector for a few processes not for all.

If you need more info please let me know.

**Comment by aneslozo** [comment]
Hi @martinlindhe,

Any news on this one? Can I help further?

**Comment by carlpett** [comment]
I did a quick test now where I built a process which simply allocates 10 GB of memory and then checked the exporter output. On my machine (Win10 Pro) it seems to work correctly, however 🤔 
Could you check what your output is if you run the corresponding WMI query?
```ps
gwmi -Query 'SELECT * FROM  Win32_PerfRawData_PerfProc_Process WHERE <any filters you use>'
```

**Comment by aneslozo** [comment]
Thanks @carlpett for checking and answering. So I run 

`gwmi -Query 'SELECT * FROM  Win32_PerfRawData_PerfProc_Process WHERE Name LIKE "java%"'`

and got correct data 

`PrivateBytes            : 26345476096`

So now the question is why I have `4294967295` in my Prometheus for the same java process? I will check maybe it is the Prometheus issue and let you know.

**Comment by carlpett** [comment]
Super interesting! Did you check the /metrics endpoint and see if it is correct there? I would *think* that it wouldn't be, if you're seeing the wrong results in Prometheus after the scrape, but best check.

**Comment by aneslozo** [comment]
@carlpett @martinlindhe I need to apologize to you guys. This is my mistake :( I was using wrong wmi_exporter installation which now makes sense why it is showing only 32-bit value. 

Everything is perfect and this is false bug. 

I promise I will update some parts of the documentation because you spent your time on this dummy bug, and it was my dummy mistake.
