### ISSUE TITLE
How can i get SOA number

### ISSUE THREAD

**Issue by eligosfx** [martinlindhe/wmi_exporter#471]
soa number is 0 , always

**Comment by eligosfx** [comment]
The number is 0 , always

**Comment by carlpett** [comment]
Hi @eligosfx,
I don't understand what you are asking. Can you clarify?

**Comment by eligosfx** [comment]
Hi, Sure.
I trying to get the soa number in order to understand if other servers got the dns updates and soa number is equal.
Every zone in DNS has SOA number.

**Comment by carlpett** [comment]
Hi,
Right, but where are you seeing the zero? As far as I know, we don't expose anything zone-specific, since the WMI data we query doesn't have it.

**Comment by eligosfx** [comment]
tnx
