### ISSUE TITLE
wmi_textfile_scrape_error 1 if there was an error opening or reading a file, 0 otherwise

### ISSUE THREAD

**Issue by Baludocker** [martinlindhe/wmi_exporter#472]
I wrote a python script to write the output to .prom file and started wmi_exporter.exe to collect metrics from default directory.
But I keep getting error ***wmi_textfile_scrape_error 1 if there was an error opening or reading a file, 0 otherwise***

Could someone help me in fixing this.

**Comment by carlpett** [comment]
Hi @Baludocker,
You should get some log output telling you what the problem is when reading the file. What does it say?

**Comment by Baludocker** [comment]
**I am seeing parsing error as  text parsing error in line 1 Unexpected end of input stream textfile.go line:252**
<img width="1245" alt="Screenshot 2020-03-03 at 10 04 00 AM" src="https://user-images.githubusercontent.com/43617337/75743261-660d8280-5d36-11ea-80f5-32b2a6b62f88.png">

**Comment by carlpett** [comment]
@Baludocker That means you did not add a trailing newline to your .prom file.

**Comment by Baludocker** [comment]
Yes @carlpett after appending newline to the script I can see the metrics in Prometheus.

**Comment by Baludocker** [comment]
Yes @carlpett after appending newline to the script I can see the metrics in Prometheus
