### ISSUE TITLE
Slow scraping collector - process

### ISSUE THREAD

**Issue by YangLu1031** [martinlindhe/wmi_exporter#487]
I'm trying to use wmi_exporter to collect the cpu usage per process for windows nodes in kubernetes cluster. So I enabled `cs,process` collectors only. 
After bring up 20 pods with pause image of windows server containers, it takes 20s for scraping. 
As our goal is running 80 pods for load test, so it takes around 1m30s. 
After enabled `scrape.timeout.margin=2`, found the process collector takes too long.

Is there any ways we can do to configure correctly or improve it?

**Comment by carlpett** [comment]
Hi @YangLu1031,
How many processes are running on the system? The process collector is probably the heaviest collector of all right now, but your timings seem unexpectedly high anyway.

**Comment by YangLu1031** [comment]
2775, also noticed that there are 161 `windows session manager` processes which seems related to 80 pods.

**Comment by carlpett** [comment]
I did some optimization of the collector yesterday evening in #489. Could you try the CI build [here](https://ci.appveyor.com/api/buildjobs/eas2vt8vlo64swac/artifacts/output%2Famd64%2Fwmi_exporter-0.10.3-process-perflib.1%2B1-amd64.exe) and see if it makes a noticable difference?

**Comment by YangLu1031** [comment]
Thanks, it made huge difference! For 80 pods, it takes around 6.5s

**Comment by carlpett** [comment]
@YangLu1031 v0.11 was released tonight
