### ISSUE TITLE
WMI_exporter failed to collect some metrics in a server 2012R2

### ISSUE THREAD

**Issue by m934030039** [martinlindhe/wmi_exporter#490]
Hello guys,

      I am new to Prometheus + Granfan but I follow the office site to implement it on linux (pure installation) and Windows Server 2012R2 (**pure installation**) and it goes well.

      Some days ago, I repeated the same steps on Prod. M$ server 2012 R2 (w/ some customized applications) but I encountered troubles.

      My observation below
     * http://localhost:9182/metrics do show some data on Prod. M$ Server 2012R2.
[Prod-Server2012R2-port9182-metrics.txt](https://github.com/martinlindhe/wmi_exporter/files/4386942/Prod-Server2012R2-port9182-metrics.txt)

     * Prometheus can reach the Prod. M$ Server 2012R2
![port9090](https://user-images.githubusercontent.com/31229402/77644624-4287d180-6f9c-11ea-84ae-82ad418c4c8d.JPG)

     * Granfan cannot find the Prod. M$ Server 2012R2 but it did find non-Prod. M$ Server 2012R2
![granfan](https://user-images.githubusercontent.com/31229402/77645242-60a20180-6f9d-11ea-9eca-8e790d63d4a1.JPG)

     My analyze below
     * Look Event Viewer and do find some Error about WMI_export
[viwer.zip](https://github.com/martinlindhe/wmi_exporter/files/4386983/viwer.zip)

     * Some Performance Counters is disabled in Performance Monitor in Prod. Windows Server 2012 R2
![perfmon](https://user-images.githubusercontent.com/31229402/77645119-2c2e4580-6f9d-11ea-8ee8-c5c1b128f630.JPG)

     * Does rebuild Performance Counters impact the Prod. application?
https://social.technet.microsoft.com/wiki/contents/articles/19374.windows-performance-monitor-unable-to-add-these-counters.aspx
        I do believe that someone intentionally disable the Performance Counters but he left the company.

**Comment by carlpett** [comment]
Hi,
`lodctr /r` should be fine to run in production.

**Comment by m934030039** [comment]
Hello,

     Thx for the reply.

     Does disable Performance Counters is the root cause?

      It look likes that is the root cause to me.

-Sheng

**Comment by carlpett** [comment]
It is hard to say for certain, but it definitely sounds plausible.

**Comment by m934030039** [comment]
I resolved it and thx Carlpett.

In my case, let me summary my general steps below.
To compare the metrics between GOS on the same HW server.
To read Windows Event Viewer and you should see wmi-exporter Error messages in the VM
To google the message then it will lead you to look up Performance Monitor
Once you open Performance Monitor you will see the prompt Windows contains message below
"Unable to add these counters"
 https://social.technet.microsoft.com/wiki/contents/articles/19374.windows-performance-monitor-unable-to-add-these-counters.aspx
Restart wmi-exporter
Refresh broswer
