### ISSUE TITLE
install

### ISSUE THREAD

**Issue by mahouke** [martinlindhe/wmi_exporter#492]
msiexec /i D:\Soft\wmi_exporter-0.10.2-amd64.msi ENABLED_COLLECTORS="ad,Dns,cpu,cs,logical_disk,net,os,service,system,textfile" 
install completed successfully，Service running error

**Comment by breed808** [comment]
Hi mahouke, can you clarify what error you are experiencing? Is the service failing to start?
If so, start reducing the enabled collectors to see which is causing the service to fail. The dns collector should be lowercase.

**Comment by mahouke** [comment]
Thank you for your help，The service runs normally after dns is changed to lower case.

**Comment by mahouke** [comment]
Sorry for my bad english

**Comment by breed808** [comment]
That's OK, glad to hear it's working for you after the case change.

**Comment by carlpett** [comment]
Thanks @breed808!
