### ISSUE TITLE
Request For Comments: Renaming wmi_exporter?

### ISSUE THREAD

**Issue by carlpett** [martinlindhe/wmi_exporter#499]
Hi everyone!
When @martinlindhe started out the project, we used WMI exclusively to get data to convert to metrics. The last year or so, however, we've increasingly started to move away from WMI due to performance and reliability issues, as well as widened how we collect data, and now use Perflib and HCS in addition to WMI.
As we move towards less and less WMI usage, we'd like to deemphasise it from the project. For this reason, it might make sense to rename the project. We'd like feedback on two things:
- What would be a good name? `windows_exporter` and `winnode_exporter` are ones that have been proposed earlier, but other options would be very welcome.
- How would a name change impact you? There are likely a number of scripts and similar things that have been written over the years that would need to be changed. In some cases perhaps security policies and such. Let us know what sort of issues you'd face! Would it be sufficient to supply artifacts for both the new and old name for some period?

**Comment by carlpett** [comment]
cc @andrewmostello - for the chocolatey bits, what would need to happen there?

**Comment by SuperQ** [comment]
`windows_exporter` sounds like a fine name to me.

**Comment by simmohall** [comment]
sounds like a good idea. I lean towards winnode_exporter as it's similar to the linux counterpart node_exporter

**Comment by discordianfish** [comment]
I like windows_exporter.

PS: When I started the node-exporter at SoundCloud, there was a lot of bikeshedding involved in finding the name. No reason to stick with 'node' since not everybody was a big fan of that name back then either :)

**Comment by Mario-Hofstaetter** [comment]
I also prefer `windows_exporter` , and dislike `node_exporter` 😄 
Hopefully this is future proof?
Since we are early in rolling out the exporter the name changes has no consequence but thats clearly the exception.

**Comment by martinlindhe** [comment]
I prefer windows_exporter

**Comment by andrewmostello** [comment]
> cc @andrewmostello - for the chocolatey bits, what would need to happen there?

I think I would just create a new package with the updated name, and make a reference note and link on the old package. I've been looking into it and I don't think you can rename packages, although I'll keep reviewing the documentation.

**Comment by dalejrodriguez** [comment]
windows_exporter sounds good to me.

**Comment by marcusteixeira** [comment]
Great work!
I also prefer windows_exporter.

**Comment by daviddetorres** [comment]
windows_exporter seems to me more intuitive, but people used to monitor node-exporter will find it more similar with winnode_exporter... Difficult to choose. 

I'd go for winnode_exporter.

**Comment by eikaas** [comment]
I suggest the slightly more Go idiomatic _winexporter_

I'd prefer _win_exporter_ over _windows_exporter_ though, as it's easier to type and I don't think the _win_-abbreviation adds any ambiguity

**Comment by SuperQ** [comment]
As @discordianfish said, there's no need to follow the `node_exporter` name. `windows_exporter` is sufficient. In Prometheus naming, we usually recommend avoiding abbreviations.

**Comment by discordianfish** [comment]
Man, this is the most bikesheddingy issue ever. Going to unsubscribe.

**Comment by carlpett** [comment]
Yes, this should probably have been brought to a conclusion a while ago. Let's go with `windows_exporter`. There's a couple of things that need to happen, but I'll put them in a separate issue.
