### ISSUE TITLE
adfs counter not found

### ISSUE THREAD

**Issue by bosundare** [martinlindhe/wmi_exporter#503]
Installed adfs collector to pull adfs metrics, however, after installation, Error log reports collector adfs failed after 0.00000s; counter not found. 
This was run from the cmdline to install it: 
wmi_exporter-0.10.2-amd64.msi ENABLED_COLLECTORS=cpu,cs,logical_disk,memory,net,os,service,system,textfile,adfs
After installation, I got - 
wmi_exporter_collector_success{collector="adfs"} 0
However, if I only pass on the adfs collector during installation, adfs counter works perfectly.

**Comment by carlpett** [comment]
Hi @bosundare,
I don't understand this bit:
>However, if I only pass on the adfs collector during installation, adfs counter works perfectly.

What do you mean? It works with the same version if you change the collector configuration after installation?

**Comment by carlpett** [comment]
I don't have an ADFS machine to test on, but reading the code I found a bug since 0.10.0. This is a "this should never work" situation, though, so a bit interested to hear if it works otherwise for you.

**Comment by bosundare** [comment]
@carlpett  I tried with the new release and it worked, all the collectors that I passed on during install was successfully scraped.
wmi_exporter_collector_success{collector="adfs"} 1
wmi_exporter_collector_success{collector="cpu"} 1
wmi_exporter_collector_success{collector="cs"} 1
wmi_exporter_collector_success{collector="logical_disk"} 1
wmi_exporter_collector_success{collector="memory"} 1
wmi_exporter_collector_success{collector="net"} 1
wmi_exporter_collector_success{collector="os"} 1
wmi_exporter_collector_success{collector="service"} 1
wmi_exporter_collector_success{collector="system"} 1
