### ISSUE TITLE
Windows shared drive monitoring

### ISSUE THREAD

**Issue by nevesing** [martinlindhe/wmi_exporter#507]
Can this exporter be used to monitor the network shared drive in windows servers? I have multiple shared drives and I want to check whether it is available/accessible for every 15 minutes or so

**Comment by carlpett** [comment]
Hi @nevesing,
No, there are currently no collectors that expose that information. If you can find a Performance Counter or WMI class which has that data, we'd be happy for a pull request to add it!

**Comment by Mario-Hofstaetter** [comment]
@nevesing You can easily do that using powershell + `textfile` collector, its essentially a one-liner. Just use `Test-Path` to check any path/share/driveletter.

e.g.:
```powershell
$path = "\\localhost\someshare";
# 1 = Up
Set-Content -Path "C:\wmi_exporter\textfile_collector\networkshare.prom" -Value "wmi_network_share_up {path=`"$($path.Replace('\','\\'))`"} $([int](Test-Path $path))";
```
❗  Be careful to escape any backlash in `labels` as `\\` or you will get `wmi_textfile_scrape_error 1`. 

Adding proper TYPE and HELP is missing. The label is optional of course but a better choice than creating multiple metrics.

Just run something like this in windows task scheduler every 15 minutes and you are set. You can create the scheduler task with powershell and deploy it to your targets using powershell remoting.

Results in:

```
# HELP wmi_network_share_up Metric read from C:\\wmi_exporter\\textfile_collector\\networkshare.prom
# TYPE wmi_network_share_up untyped
wmi_network_share_up{path="\\\\localhost\\someshare"} 1
```
ready to scrape, and
```
wmi_network_share_up{instance="YourHost:9182",job="YourJob",path="\\localhost\someshare"} 1
```
in prometheus. 

If you plan to use `grafana` just a warning that there are currently issues with the backslash (https://github.com/grafana/grafana/issues/24478), so I'd recommend replacing them with forward slash if that is an option for you.

**Comment by nevesing** [comment]
Thanks @Mario-Hofstaetter I will try this solution

**Comment by Mario-Hofstaetter** [comment]
@nevesing if that technique satisfies your needs don't forget to close this issue 😄

**Comment by nevesing** [comment]
Yes I am able to use it in my local for now. Thanks.
