### ISSUE TITLE
silent install msi

### ISSUE THREAD

**Issue by danielcb** [martinlindhe/wmi_exporter#51]
Hi,
it looks like the msi currently doesn't support /q* /quiet /passive flags for install/uninstall. Adding this would be nice for installs via configuration management tools like salt, ansible, ..

Since the installation doesn't need any manual intervention anyways I figure it could be added easily?

**Comment by carlpett** [comment]
Hm, really? `/quiet` should be supported. Actually, I'm using it on our environment at work, deploying using Saltstack. And testing it with msiexec on my machine now, it seems to work as well. 

What is your environment, and how does the problem show?

**Comment by danielcb** [comment]
Sorry for the delay. Just tested it with [this msi](https://ci.appveyor.com/project/martinlindhe/wmi-exporter/build/job/17ym8bkaiv4t59rm/artifacts):
`msiexec /i /quiet wmi_exporter-0.1.2-amd64.msi`

This just opens the help screen for the msi (i.e. `msiexec /?`)

**Comment by carlpett** [comment]
I think that is actually an invocation syntax error. The path is a parameter to the `/i` option, so they need to be together. Also, I've never managed to get msiexec to accept relative paths, only absolute. So, try this:

```
msiexec /quiet /i <full-path-to-msi>
```

**Comment by danielcb** [comment]
Ok, layer 8.. sorry and thank you! :)
