### ISSUE TITLE
Add ProcessId and DisplayName label to service collector

### ISSUE THREAD

**Issue by gsanchezgavier** [martinlindhe/wmi_exporter#514]
Hi there!
It would be useful for us to have the "ProcessId" and "DisplayName" properties as a labels for the service metrics.
Would you be open to accept a PR for this addition ? Thanks!

**Comment by gsanchezgavier** [comment]
Hi @carlpett I added this [PR](https://github.com/martinlindhe/wmi_exporter/pull/516) to represent what would be the change for this issue, before I added documentation changes I would like hear your comment on this.  

I think that this also could be resolved creating an info metric for the service (wmi_service_info) with the name, processID and DisplayName of the service.

Is there any inconvenient adding this labels that I may not aware of? 
Thanks

**Comment by carlpett** [comment]
Hey @gsanchezgavier,
Sorry for taking a while to look at this, only have a limited amount of time available for the exporter right now. As you suggest, I would prefer to go with a _info approach instead. This would mean we avoid the label changes on the actual state metrics whenever a service is restarted.
Sounds okay?

**Comment by gsanchezgavier** [comment]
It sounds good , I will update the PR with those changes and add documentation for that
