### ISSUE TITLE
Win32 compatibility

### ISSUE THREAD

**Issue by jmirakul** [martinlindhe/wmi_exporter#521]
Hi,
wmi_exporter is a great product that I have been using for some time. Now I have to do an installation on several 32bit Windows servers, however unsuccessfully.
I'am  trying to run wmi_exporter-0.11.1-386.exe on a Windows 2008 standard server as Administrator and get the following message:
C:\Users\Administrator\Downloads\wmi_exporter-0.11.1-386.exe is not a valid Win32 application.

The latest version that works on Win 2008 standard server is wmi_exporter-0.9.0-386.exe.
Have you got any solution?

Kind regards,
Jon

**Comment by carlpett** [comment]
Hi,
Thanks :) This was reported in #486 (fitting issue number!) as well, so I'll close this one as a duplicate. It'd be great if you could chime in on the discussions there!
