### ISSUE TITLE
Enabling unknown collectors leads to crash

### ISSUE THREAD

**Issue by mar1ged** [martinlindhe/wmi_exporter#528]
I run wmi_exporter 0.11.1 (the 64 bit variant) on my Windows 10 x64 1909 using this command line:

```wmi_exporter.exe --collectors.enabled "cpu,cs,logical_disk,logon,memory,net,os,process,remote_fx,system,tcp,terminal_services" --collector.process.whitelist="euca.+"```

Unfortunately it fails with this:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x932956]

goroutine 1 [running]:
github.com/martinlindhe/wmi_exporter/collector.Build(...)
        C:/gopath/src/github.com/martinlindhe/wmi_exporter/collector/collector.go:75
main.loadCollectors(0xc000054060, 0x56, 0xc00009e000, 0xc000158000, 0xc00005e178)
        C:/gopath/src/github.com/martinlindhe/wmi_exporter/exporter.go:235 +0xc6
main.main()
        C:/gopath/src/github.com/martinlindhe/wmi_exporter/exporter.go:322 +0xeeb
???

**Comment by carlpett** [comment]
Hi @mar1ged,
Sorry, this is unclear. We haven't made a release yet which includes those collectors, so that's why it is failing.
This is also a bug in that we do not give a more helpful error when referencing a collector which does not exist.
