### ISSUE TITLE
[featurerequest] Add PercentProcessorTime Counter

### ISSUE THREAD

**Issue by christian-hofstetter** [martinlindhe/wmi_exporter#54]
Hi there,

Would it be possible to add the PercentProcessorTime counter to the CPU collector?

Sample query:
select PercentProcessorTime from Win32_PerfFormattedData_PerfOS_Processor where Name = '_Total'
“PercentProcessorTime,” as appears above, is the percentage of the time the processor is busy doing non-idle threads.

Cheers,
Christian

**Comment by carlpett** [comment]
Hi,
This was discussed recently, see #53.
