### ISSUE TITLE
Feature: Services states

### ISSUE THREAD

**Issue by mikenowak** [martinlindhe/wmi_exporter#55]
Hi Martin,

It would be useful to get Windows Service states exposed in a similar fashion that node_exporter exposes systemd states.

i.e. (example from node_exporter 
```
node_systemd_unit_state{name="syslog.service",state="activating"} 0
node_systemd_unit_state{name="syslog.service",state="active"} 0
node_systemd_unit_state{name="syslog.service",state="deactivating"} 0
node_systemd_unit_state{name="syslog.service",state="failed"} 0
node_systemd_unit_state{name="syslog.service",state="inactive"} 1
```

Some good information at the below urls:

https://msdn.microsoft.com/en-us/library/aa394418(v=vs.85).aspx
https://github.com/bosun-monitor/bosun/blob/master/cmd/scollector/collectors/processes_windows.go

**Comment by carlpett** [comment]
Hi @mikenowak,
Thanks for the suggestion. I had a look, and it looks like it should be quite straightforward. Initially, I'd say we would only expose name and state, the other properties seem less useful. Do you agree about that?

**Comment by mikenowak** [comment]
Hi @carlpett, 

Agreed, yes - thats pretty much all that I am after.

**Comment by carlpett** [comment]
Alright, I have a working prototype now. Some choices made:

- I went with the service name instead of the display name, which makes it somewhat less easy to parse (`name="igfxcuiservice1.0.0.0"`...), but I think there is no guarantee that a display name is unique. 
- I'm lower-casing everything
- I expose the start_mode as a separate metric, which should make for easy alerting if something isn't in the state you want it to.

Example output:

```
# HELP wmi_service_start_mode The start mode of the service (StartMode)
# TYPE wmi_service_start_mode gauge
wmi_service_start_mode{name="aelookupsvc",start_mode="manual"} 1
wmi_service_start_mode{name="alg",start_mode="manual"} 1
wmi_service_start_mode{name="aphidmonitorservice",start_mode="auto"} 1
wmi_service_start_mode{name="appidsvc",start_mode="manual"} 1
[...]
# HELP wmi_service_state The state of the service (State)
# TYPE wmi_service_state gauge
wmi_service_state{name="aelookupsvc",state="running"} 1
wmi_service_state{name="alg",state="stopped"} 1
wmi_service_state{name="aphidmonitorservice",state="running"} 1
wmi_service_state{name="appidsvc",state="stopped"} 1
```

Looks ok?

**Comment by martinlindhe** [comment]
Hi @mikenowak and thanks for the suggestion. Our excellent @carlpett is already on the ball, reviewing his patch now!

**Comment by martinlindhe** [comment]
@mikenowak Could you give v0.1.3 a spin? We just pushed this release containing the service collector

**Comment by mikenowak** [comment]
Good day @martinlindhe, @carlpett,

thank you for quick turnaround - truly outstanding! 

I verified this to work on Win2013 R2 and Win2016 Server.

Here is one more question as my knowledge is incomplete because so far focused on gathering metrics rather than visualising data. 

Is there any real benefit of the node_exporter approach (which exposes all the possible statuses for a given service and a gauge) versus solution implemented herein?

```
node_systemd_unit_state{name="syslog.service",state="activating"} 0
node_systemd_unit_state{name="syslog.service",state="active"} 0
node_systemd_unit_state{name="syslog.service",state="deactivating"} 0
node_systemd_unit_state{name="syslog.service",state="failed"} 0
node_systemd_unit_state{name="syslog.service",state="inactive"} 1
```

**Comment by carlpett** [comment]
@mikenowak It does not matter, as far as I am aware. Prometheus will consider any absent series as zero. However, the case could be made that it would be clearer to always expose all the series. It would also ensure that any other consumers of the endpoint (I'm aware of at least one other client) work the same, as I'm not sure if this is required behavior. I'll give it a fix.

**Comment by carlpett** [comment]
@mikenowak We merged an update which exposes all the states/start modes for clarity

**Comment by mikenowak** [comment]
Thanks, confirmed to work as expected.
