### ISSUE TITLE
network collector (net.go) uint32 -> uint64

### ISSUE THREAD

**Issue by jimliming** [martinlindhe/wmi_exporter#60]
**BytesReceivedPerSec**, **BytesSentPerSec** within **Win32_PerfRawData_Tcpip_NetworkInterface** are uint32. 

https://msdn.microsoft.com/en-us/library/aa394293%28v=vs.85%29.aspx

This seems to cause rollover when collecting from large, 10Gb+, interfaces. **BytesTotal** is uint64 and works fine.

I've been looking around for an alternate wmi path to expose this information as uint64, but nothing has jumped out yet.

**Comment by jimliming** [comment]
egh, that link is to perfformatted data. 

PerfRawData seems to be uint64 all the way down. 

Closing this for now, the issue must be something else.

**Comment by jimliming** [comment]
Looks like the issue is net.go is defining most of the items as uint32, similar to the above link. Changed all uint32's in Win32_PerfRawData_Tcpip_NetworkInterface struct to uint64 is working great. 

seem reasonable? Further down it looks like that was the original intention.

**Comment by carlpett** [comment]
Hi!
Thanks for reporting this. Indeed it looks like the data types are uint64, so it should be enough to just change the types in the `Win32_PerfRawData_Tcpip_NetworkInterface` struct. If you feel like submitting a PR, that would be great! Otherwise we'll try to get to it as soon as possible.

**Comment by carlpett** [comment]
Fixed in #61, thanks!

**Comment by carlpett** [comment]
The initial release of this failed to build due to a broken url. v0.2.2 should be finished shortly, including binaries.

**Comment by martinlindhe** [comment]
Glad this got sorted out. I guess the microsoft docs are incorrect then? Over here, they are listed as 32bit:
https://technet.microsoft.com/en-us/security/aa394340(v=vs.80)

**Comment by carlpett** [comment]
@martinlindhe Hm. It is possible they changed the type in later versions (the docs you linked seem to be for WinXP?). We should test this on both older versions of Windows, as well as different bitnesses. Also, what about the 32-bit version we ship?

**Comment by martinlindhe** [comment]
Hm. Is it for XP? All i could deduce from the article is the metrics was introduced in XP / Windows Server 2003. Is there some newer docs showing them as 64bits?
If  the struct had different sizes for a 32-bit Windows, one might think they would all be 32-bit.
I just hope we don't need to have 2 versions of this :-)

**Comment by carlpett** [comment]
Ah. No, on closer reading, this is the docs for Visual Studio v8.0, also known as Visual Studio 2015.
I checked my local machine, and it reports the types as `uint64` (`gwmi Win32_PerfRawData_Tcpip_NetworkInterface | gm -MemberType Properties | select Definition`). 

So, I dug into the WMI library we're using, and [this line](https://github.com/StackExchange/wmi/blob/master/wmi.go#L308) seems to indicate that all unsigned types are saved to `uint64`, regardless of their actual type? If I understood that correctly, we should be good. I think.

**Comment by martinlindhe** [comment]
Okay, sounds good. I've been meaning to try the project out on some older Windows versions, I'll try to remember checking this out when I'm at it.
