### ISSUE TITLE
Installer fails to download binaries due to broken links

### ISSUE THREAD

**Issue by carlpett** [martinlindhe/wmi_exporter#62]
The url to wix-binaries.zip periodically changes due to new releases of WiX. This currently breaks the installer build. I've contacted Rob Mensching (project lead) and asked about stable urls. If that cannot happen, we'll need to figure out some way to get the latest url.

**Comment by martinlindhe** [comment]
I had a look around, and while WiX now seems to be on Github (https://github.com/wixtoolset/wix3) they don't provide binaries there.
They do provide binaries on their homepage, and exposed in this feed:

http://wixtoolset.org/releases/feed/v3.10

http://wixtoolset.org/downloads/v3.10.3.3007/wix310.exe

This doesn't seem to be packaged the same as the zip archive provided on codeplex though

**Comment by carlpett** [comment]
Yes, Microsoft is closing down CodePlex, so everything is moving to Github. This is probably a work in progress, so let's wait a short while and see if they get their CI working with Github as well.

**Comment by carlpett** [comment]
This was fixed by #84! :cake:
