### ISSUE TITLE
/metrics URL suddenly stopped working

### ISSUE THREAD

**Issue by oliverpool** [martinlindhe/wmi_exporter#63]
Hi,
first of all, thank you for this great tool!

I just have a very strange situation: on 1 of my servers, the export suddenly stopped working (everything was fine for more than a month!).

I tried to update to the latest version (0.2.2), but the issue is still appearing.

## Issue

When I launch the following command:
```
wmi_exporter.exe -log.format logger:eventlog?name=wmi_exporter -collectors.enabled "cpu,cs,iis,logical_disk,net,os,system" -telemetry.addr :9182
```
the `/health` URI returns `{"status":"ok"}`, but the `/metrics` does not respond.

I tried to enable the different collectors only one a a time and I got this result:
* Working fine (`/metrics` responds with the expected metrics):
  - `cs`
  - `os`
* Failing (make the `/metrics` hang):
  - `cpu`
  - `iis`
  - `logical_disk`
  - `net`
  - `system`

## Question

Do you know a "common point" between the failing collectors, to help me further investigate and debug this situation ?

**Comment by oliverpool** [comment]
Or could it be possible to add some king of timeout for the query:

http://www.yusufozturk.info/tag/powershell-wmi-hang-timeout

**Comment by carlpett** [comment]
@oliverpool That is very strange. The only thing common there is whether they use counters that are "RawPerf" or not. Could you check if the `service` collector works (added in 0.2, and also not a raw type)?

For the record, the `/health` endpoint always replies with ok as long as it can start the http server, so it doesn't diagnose the WMI querying capabilities.

**Comment by carlpett** [comment]
Also, could you try issuing this in a Powershell terminal?

`Get-WmiObject Win32_PerfRawData_Tcpip_NetworkInterface`

**Comment by oliverpool** [comment]
> Could you check if the `service` collector works

`service` works fine (also with `os` and `cs`)

> `/health` endpoint always replies with ok

It was to be sure that the http listener was working

> `Get-WmiObject Win32_PerfRawData_Tcpip_NetworkInterface`

It hangs (forever in comparison with another server which replies in a couple of seconds)

**Comment by oliverpool** [comment]
I'm trying the WMI Diagnosis Utility utility described here: https://social.technet.microsoft.com/Forums/windows/en-US/65bb62e8-7816-4206-8417-033025394086/wmi-query-hanging?forum=winserverManagement (but it takes quite a while).


It seems to be a bug in windows (and you can't do much about it :-), the only feature that the `wmi_exporter` could have, is to have some kind of timeout in case of such failure.

**Comment by christian-hofstetter** [comment]
@oliverpool I had similar issues when upgrading to 0.2.0 and having the services metrics enabled. The issue was on the Prometheus side where the --storage.local.memory-chunks was set too low.

**Comment by carlpett** [comment]
I'm wondering if this could be related to the problem reported here: https://github.com/martinlindhe/wmi_exporter/issues/50#issuecomment-270630204.

If the diagnostics utility doesn't come up with anything, try the command mentioned there.

**Comment by martinlindhe** [comment]
@oliverpool on which windows version are you seeing this? Also, 32 or 64-bit?

**Comment by oliverpool** [comment]
> I'm wondering if this could be related to the problem reported here: #50 (comment).

`lodctr.exe /r` didn't solve the issue

The WMI Diagnosis Utility seems also to be hanging.

**Comment by martinlindhe** [comment]
@oliverpool Does restarting the Windows Management Instrumentation service resolve this issue?

**Comment by oliverpool** [comment]
This thread apparently solved the issue: http://www.tek-tips.com/viewthread.cfm?qid=1747388

> Try running regsvr32 wmisvc.dll at the command prompt, followed by winmgmt /resyncperf, and then reboot.

So everything is back to normal: thanks everyone for the help!

---

It was a bug in windows (and we can't do much about it), the only feature that the `wmi_exporter` could have, is to have some kind of **timeout to detect such failure instead of hanging forever**. It could also display some error messages (maybe linking to this issue).

**Comment by martinlindhe** [comment]
@oliverpool thanks for updating us! Closing this as resolved then
