### ISSUE TITLE
missing IIS metrics

### ISSUE THREAD

**Issue by harmw** [martinlindhe/wmi_exporter#64]
Enabled the IIS collector, but on _some_ of my machines the only metric that involves iis are these:

```
wmi_exporter_scrape_duration_seconds{collector="iis",result="success",quantile="0.5"} 0.0549788
wmi_exporter_scrape_duration_seconds{collector="iis",result="success",quantile="0.9"} 0.0810007
wmi_exporter_scrape_duration_seconds{collector="iis",result="success",quantile="0.99"} 0.0810007
wmi_exporter_scrape_duration_seconds_sum{collector="iis",result="success"} 0.462801
wmi_exporter_scrape_duration_seconds_count{collector="iis",result="success"} 9
```

Other machines *do* show the expected information, like this one:
```
wmi_iis_anonymous_users_total
```

Any pointers on how to approach this?

**Comment by carlpett** [comment]
Sorry about that!
The first test would be to run `Get-WmiObject Win32_PerfRawData_W3SVC_WebService` in a powershell terminal. That will show you if the counters are actually available on the machine.

**Comment by harmw** [comment]
Ah, thanks. Well, they are not. So what's next 👍 And how come this happens on _some_ of my machines, given all are provisioned/deployed in the same manner (using Ansible)?

**Comment by carlpett** [comment]
I'm not really sure how this would happen if they are all created identically. There might be some race condition somewhere in the Windows installation, maybe? Hard to guess. But [this article](https://blogs.technet.microsoft.com/askperf/2014/08/11/wmi-missing-or-failing-wmi-providers-or-invalid-wmi-class/) has a number of troubleshooting steps.

**Comment by harmw** [comment]
apparently, simply restart `Windows Management Instrumentation` resolved the issue
