### ISSUE TITLE
Feature Request: CPU Temperature

### ISSUE THREAD

**Issue by jeremyje** [martinlindhe/wmi_exporter#73]
It'd be nice to get metrics from https://msdn.microsoft.com/en-us/library/aa394493(v=vs.85).aspx

**Comment by carlpett** [comment]
Hi!
That would be interesting for sure. However, I don't seem to get any values in those WMI classes. Do your systems report anything there?

**Comment by sandersaares** [comment]
https://github.com/openhardwaremonitor/openhardwaremonitor reports useful hardware stats and appears to do some of it through WMI queries. Perhaps this would be a useful source of inspiration.

**Comment by carlpett** [comment]
@sandersaares I had a quick browse through the code, and as far as I can tell, they don't use WMI for actually getting temperatures etc, but only for probing what hardware is installed? They do register a custom WMI provider as well, which I couldn't see what they actually used for, though. 
Did you see any concrete usage of WMI to get the temperatures that I missed?

**Comment by sandersaares** [comment]
No, I just quickly rifled through the code and saw some WMI but I also did not see too direct of a connection. Guess it is no good then.

**Comment by CasparChou** [comment]
hi @carlpett , actually, we really need this index. I have several windows machine for digital signage. They are installed inside the bus stop smartpole, digital advertising box. They are often overheating and make windows system slowly. I need these cpu temperature index to verify is it overheating or not.

**Comment by StewartThomson** [comment]
The documentation above states that 

> Most of the information that the Win32_TemperatureProbe WMI class provides comes from SMBIOS. Real-time readings for the CurrentReading property cannot be extracted from SMBIOS tables. For this reason, current implementations of WMI do not populate the CurrentReading property. The CurrentReading property's presence is reserved for future use.

I played around [this script](https://gist.github.com/jeffa00/9577816) and found that the temperature returned is unchanging likely because of the issue above.

Unless there's features elsewhere, it looks like WMI doesn't support temperature readings at this time, unfortunately

**Comment by StewartThomson** [comment]
[This is promising](http://stackoverflow.com/questions/21884264/retrieve-intel-pch-temperature-with-powershell/36915900#36915900). Ran some bench marks and the value seems to be updating in real time

**Comment by carlpett** [comment]
With the merge of #359, we can close this. Thanks Stewart!
