### ISSUE TITLE
no msi

### ISSUE THREAD

**Issue by frankie64** [martinlindhe/wmi_exporter#75]
Hi Martin,

your wmi_exporter works fine. but after govendor build, I got only the wmi_exporter.exe. What must I do to get an wmi_exporter.msi. Or, can I config the behavair of wmi_exporter.exe via parameter, or config-file?

thx
Frank

**Comment by carlpett** [comment]
Hi @frankie64!
The installer is built using the `installer/build.ps1` script. You can use that to build it locally, and check the AppVeyor configuration for some notes on how it is called. 
Alternatively, you can start wmi_exporter with a number of flags on the commandline to customize its behavior. Try `wmi_exporter.exe -help` to get a listing of the available flags.

Hope this helps!

**Comment by frankie64** [comment]
Hi Carl,

thx for quick answer. I try to create a wmi_exporter. the build.ps1 stop after a while mit errormessage: wmi_exporter.wxs(36) : error LGHT0103 : The system cannot find the file 'Work\wmi_exporter.exe'.
in folder installer\Work I found a folder not a file wmi_exporter.exe. 

do you have an idea?
~Frank

**Comment by carlpett** [comment]
Hi,
Hm, that is odd. How did you invoke build.ps1? In our automated builds, we do this:
`.\installer\build.ps1 -PathToExecutable .\wmi_exporter.exe -Version $Version -Arch amd64`

This assumes that the `PathToExecutable` parameter points to an existing .exe file, which you get from your `go build`.

**Comment by frankie64** [comment]
Hi,

Sorry, I missunderstand the Paramter PathToExecutable. I give him only the Path ;-(

thx
Frank
