### ISSUE TITLE
Is Windows 2000 supported?

### ISSUE THREAD

**Issue by bbigras** [martinlindhe/wmi_exporter#83]
I got this error on Windows 2000 SP4 (32-bit):

![image](https://user-images.githubusercontent.com/24027/27559678-734b88cc-5a8f-11e7-892b-3dbfdbeb95a2.png)

**Comment by carlpett** [comment]
Hi,
Unfortunately, no. As of Go 1.3, [Windows 2000 is no longer supported by Go](https://groups.google.com/forum/#!topic/golang-dev/e0ImSCtHbcg).
