### ISSUE TITLE
Feature Request: IIS HTTP Status 

### ISSUE THREAD

**Issue by jazzhanns** [martinlindhe/wmi_exporter#85]
Hi,

I have a feature request to extend the WMI Exporter to expose metrics capturing the following:

- The total amount of 4** HTTP Status return codes received from a site for a given HTTP call 

- The total amount of 5** HTTP status return codes received from a site for a given HTTP call

I know at the moment you expose the total amount of HTTP calls for a given type e.g GET. I was thinking it would be good to see something like the following:

wmi_iis_requests_total{method="GET",site="ExampleSite",status="5**"} 

Additionally, I think it would be useful to extend the current IIS exporter to include these metrics in order to get throughput metrics:

BytesSentPerSec
BytesReceivedPerSec
BytesTotalPerSec

which is already included as part of the Win32_PerfRawData_W3SVC_WebService

Apologies if you have this available already!

Cheers

**Comment by carlpett** [comment]
Hi,
Yes, I would also love to have this! However, as far as I am aware, this is not available through WMI :( I will do some extra digging, but I believe this is something that is not possible.

Regarding the throughput, this is something that you can get using PromQL: `rate(wmi_iis_sent_bytes_total[1m])`. Does this work for you?

**Comment by jazzhanns** [comment]
Hi,

Thanks for replying so quickly and for providing me with the throughput query! Hopefully there will be something to capture the status codes :) 

Just as a side note, I was reading this article about monitoring IIS - in particular the section regarding URI cache metrics:

https://blog.serverdensity.com/monitor-iis/

And saw that it mentioned some metrics that are featured as part of this service:

https://msdn.microsoft.com/en-us/library/aa394257(v=vs.85).aspx 
(Win32_PerfFormattedData_InetInfo_InternetInformationServicesGlobal)  

which may be useful to capture for timeout information on requests for IIS etc? 

Thanks again for your help!

**Comment by carlpett** [comment]
Cache metrics seem to originate from this class: `Win32_PerfRawData_W3SVC_WebServiceCache` (None of my servers (2012/2016) have the one you referenced, also the "PerfFormattedData" classes are massaged by Windows a bit, so we prefer the "PerfRawData" ones). This should definitely be possible to add!

Also, I found this class: Win32_PerfRawData_W3SVCW3WPCounterProvider_W3SVCW3WP. It does not give us all the status codes, sadly, but at least it has these:

```Percent401HTTPResponseSent         : 0
Percent403HTTPResponseSent         : 0
Percent404HTTPResponseSent         : 50654
Percent500HTTPResponseSent         : 279```

(Disregard the "Percent", that is how it will eventually be presented in perfmon, but the data is the raw numbers)

So, we can at least get some of the statuses!

**Comment by jazzhanns** [comment]
That's perfect! Thanks for looking into it, it's very much appreciated :) 

Just out of curiosity, when do you think this could be added to the exporter? (I appreciate that there are other responsibilities you have!)

**Comment by carlpett** [comment]
Taking a look at it now. It's not too complicated adding new things - almost all of the effort is figuring out which counters are actually interesting, which ones should be just different labels of the same metric, how to name them, etc.

The major snag right now is figuring out what the difference is between the two classes, actually. Both of them export cache-related counters of the same name. `Win32_PerfRawData_W3SVCW3WPCounterProvider_W3SVCW3WP` is likely the specific caches for each worker process, while `Win32_PerfRawData_W3SVC_WebServiceCache` is globally for the server. However, the worker processes don't sum up to the global one, so there is something else going on here. Possibly the static file handler of IIS uses the cache, but doesn't hit the application pool's worker processes? Not sure.

There might also be a bit of overlap with existing IIS metrics for the worker process stuff, such as requests served etc. I'll probably leave those out, unless there is some compelling reason to add them. I've actually never seen anyone use more than one worker process per application pool, not sure how common use case it is

**Comment by carlpett** [comment]
Okay, so I have a prototype of this now. There are _a lot_ of counters, and with some overlap as I mentioned above. For example `wmi_iis_requests_total{method,site}` which is for a site (resetting with the IIS server), and  `wmi_iis_worker_requests_total{app}`, which is per AppPool worker (resetting each time the AppPool worker is recycled).

I managed to go against the official best practices with the cache metrics, so I'll fix that tomorrow and then submit a PR. The IIS collector is getting fairly large, so there might be some refactoring needed before merging.

**Comment by jazzhanns** [comment]
Thanks for the update and for adding this to the exporter!

 Did you find out the difference between the Win32_PerfRawData_W3SVCW3WPCounterProvider_W3SVCW3WP and Win32_PerfRawData_W3SVC_WebServiceCache cache's? It's quite interesting that they don't add up to each other! And I agree - if there is data already captured by one of the services, we should ignore the same overlap elsewhere - just to lessen confusion of anyone who wants to use it and doesn't know which counter to choose! :)
