### ISSUE TITLE
Feature request: garbage collection metrics

### ISSUE THREAD

**Issue by JorritSalverda** [martinlindhe/wmi_exporter#88]
According to https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/performance the 2 performance counters to monitor for issues related to garbage collection are:

- % Time in GC
- \# Total committed Bytes

Is it possible to expose those 2 performance counters through the wmi exporter?

**Comment by martinlindhe** [comment]
From the linked document alone it's not obvious these metrics exist in WMI. In fact, the document doesnt mention WMI at all, but of "Event tracing for Windows". I've no idea if that is yet another metrics system for Windows.
Could you confirm the metrics are indeed available over WMI? If not, I am not sure the feature request fits with the current scope of this collector.

**Comment by carlpett** [comment]
I think this would be the class `Win32_PerfRawData_NETFramework_NETCLRMemory` (there are a whole bunch of related classes, just replace Memory with Data, Networking, Exceptions, Interop, Jit, Loading, LocksAndThreads, Remoting or Security) . Implementing this would probably be similar to the per-process metrics being done in #79, in the sense that we'll need to do some filtering to avoid exposing thousands of metrics. But clearly useful, especially as a companion to the IIS collector for all the people running IIS-based .NET code.

**Comment by carlpett** [comment]
This was fixed in #128
