### ISSUE TITLE
Error Installing MSI in Windows Server 2016

### ISSUE THREAD

**Issue by eduardohki** [martinlindhe/wmi_exporter#92]
Hi,

The Windows Installer found an error while installing the MSI Package, issuing the following error:

![image](https://user-images.githubusercontent.com/7414593/27931143-96277328-626f-11e7-9558-1c5d4dd2db97.png)

So I can only cancel the installation and quit.

PS: It doesn't happen in earlier versions, only in 2016

**Comment by eduardohki** [comment]
Note: Actually no service 'wmi_service' was ever installed.

**Comment by carlpett** [comment]
We'll need the msi logs to troubleshoot this. Uninstall the package first, if the installation succeeded, then run `msiexec /i <absolute path to .msi-file> /l* c:\msi.log` and upload the msi.log file as a gist.

Also, what edition of Windows Server 2016 are you using? Any particular lock-downs using GPOs or similar?

**Comment by eduardohki** [comment]
We found out that the "WMI Service" was disabled on the server ¬¬
After enabling it it worked fine.

My apologies and thanks for your time!
